### ISSUE TITLE
[Spotify Player] Remove fetch limit from Your Library

### ISSUE THREAD

**Issue by gabrielrenderos** [raycast/extensions#8358] opened 2023-09-12 16:50 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Remove the 50 item limit when fetching data from "Your Library" so it can search and load all the playlists and albums saved, and enable interaction with them directly from Raycast.

### Who will benefit from this feature?

Every person with more than 50 playlists or items in each Library category.

**Comment by erics118** [comment] 2023-10-15 21:10
Duplicate of #7807

**Comment by peduarte** [comment] 2023-11-16 20:12
Thanks @erics118 

For now it's a limitation as stated in #7807 but I do agree we should consider adding pagination. Will have a look

**Closed by peduarte** 2023-11-16 20:12 UTC
Labels: feature request, extension, extension: spotify-player
