### ISSUE TITLE
[Spotify Player] Only recent items showing in "Your Library" search results

### ISSUE THREAD

**Issue by inducingchaos** [raycast/extensions#14663] opened 2024-09-25 13:25 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.83.1

### macOS Version

15.0

### Description

When searching in the "Your Library" function, only recent songs are loaded & others do not show up.

### Steps To Reproduce

Install Spotify ext, search "Your Library", then search for a song or library item.

### Current Behaviour

Showing only recent items

### Expected Behaviour

Show all library items

**Comment by thomaslombart** [comment] 2024-09-30 06:42
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/7222, so I'll mark it as such.

**Closed by thomaslombart** 2024-09-30 06:42 UTC
Labels: bug, extension, extension: spotify-player
