### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by kieranmansfield** [raycast/extensions#6670] opened 2023-05-19 13:49 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

Menu Bar command completely failing on load. 

### Steps To Reproduce

Occurred on start up of Raycast with the command in the Menu bar.

### Current Behaviour

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

**Comment by thomaslombart** [comment] 2023-05-23 07:36
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6562, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-23 07:36 UTC
Labels: bug, extension, extension: todoist
