### ISSUE TITLE
[Jira] Open Issues doesn't show the tickets

### ISSUE THREAD

**Issue by smark91** [raycast/extensions#6041] opened 2023-04-19 15:20 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

This happen since the new extension. The old one worked well

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

Open "Open Issues"
See the error

### Current Behaviour

I receive an error

### Expected Behaviour

Expected to see my assigned Issues

**Comment by thomaslombart** [comment] 2023-04-20 06:46
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.

**Closed by thomaslombart** 2023-04-20 06:46 UTC
Labels: bug, extension, extension: jira
