### ISSUE TITLE
[Music] ...

### ISSUE THREAD

**Issue by raikes** [raycast/extensions#4933] opened 2023-02-23 15:38 UTC
### Extension

https://raycast.com/fedevitaledev/music

### Description

Error: Command failed with exit code 1: osascript -e 
tell application "Music"
	set theName to name of current track
	set theArtist to artist of current track
	set theAlbum to album of the current track
	set existingTracks to get tracks of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	
	if (count of existingTracks) = 0 then
		set theCount to count of tracks of source "Library"
		duplicate current track to source "Library"
		repeat while theCount = (count of tracks of source "Library")
			delay 1
		end repeat
	end if
	
	set theTrack to first track of source "Library" whose name is theName and artist is theArtist and album is theAlbum
	duplicate theTrack to playlist "Tunes"
end tell
 
369:412: execution error: Music got an error: Can’t set source "Library" to current track. (-10006)
    at S0 (/Users/geraint/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:59)
    at /Users/geraint/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:10477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qc (/Users/geraint/.config/raycast/extensions/2bfe94cd-50ab-4e48-a6cd-f1ff47a72706/add-to-playlist.js:5:38131)

### Steps To Reproduce

Attempted to add currently playing track to playlist. 
Dialogue appeared asking which Playlist to add to, on confirmation, the error above was generated and the song was not added to the selected playlist

### Current Behaviour

Error produced and song not added

### Expected Behaviour

Expected song to be added to selected playlist

**Comment by Rawnly** [comment] 2023-02-27 20:53
duplicate of https://github.com/raycast/extensions/issues/4300

**Comment by Rawnly** [comment] 2023-02-27 20:54
@raycastbot close this issue

**Closed** 2023-02-27 20:54 UTC
Labels: bug, extension, extension: music
