### ISSUE TITLE
[github] Search PRs only shows PRs created by me 

### ISSUE THREAD

**Issue by davemaier** [raycast/extensions#8381] opened 2023-09-14 08:28 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

The github extension only searches PRs that are authored by me. Based on the description of the extension this is not the desired behavior and it makes the extension less useful. 

To fix this, `author:@me` needs to be removed in
https://github.com/raycast/extensions/blob/cc95f9186dc40f9b038a0fdb0a24a3f8bf131f68/extensions/github/src/search-pull-requests.tsx#L27

### Steps To Reproduce

1. Open github extensions "Search Pull Requests" command
2. Search for a pull request that you are not the author of

### Current Behaviour

Only PRs that were created by me are displayed

### Expected Behaviour

PRs that were created by other people should also be displayed. (Or the description of the extension should tell that only PRs created by myself are searched)

**Comment by LunaticMuch** [comment] 2023-09-18 06:27
I think the behaviour is expected and the description might be wrong. 
You can surely search for any pull request in GH, but how easy that would be? A query like

```
 is:pr archived:false <text>
 ```

is going to return an _amount_ of results. I am not against such command, but I do not think it was the original intent, albeit a _Search My PR_ would probably have the same exact functionality as the _My pull request_.

**Comment by thomaslombart** [comment] 2023-09-18 07:37
Thanks for bringing this up. It appears that this is a duplicate of issue #4058, so I'll mark it as such.

**Closed by thomaslombart** 2023-09-18 07:37 UTC
Labels: bug, extension, extension: github
