### ISSUE TITLE
[GitHub] Unable to list all issues

### ISSUE THREAD

**Issue by jdk** [raycast/extensions#5521] opened 2023-03-23 00:27 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

Despite creating a token with full permissions, only issues created by myself are listed.

I'm not sure if this is related to a private organization repo, but I've created a token with full permission:

![CleanShot 2023-03-22 at 17 23 22](https://user-images.githubusercontent.com/172534/227068040-fb503cef-a177-40cf-930c-9b4731ad214e.png)

### Steps To Reproduce

No special steps necessary.

### Current Behaviour

You can see in the right hand side, only my avatar shows because these are issues owned and created by me. I'm unable to see other open issues created by my team.

### Expected Behaviour

All issues should be seen

**Comment by thomaslombart** [comment] 2023-03-29 10:10
Thanks for the feedback. This has been confusing other users as well (like [here](https://github.com/raycast/extensions/issues/4058)). Let me check with the team to see what improvements we can make.

**Comment by thomaslombart** [comment] 2023-03-30 09:38
After talking with the team, we can see how it's confusing. We'll see how we can change the GitHub commands to make the extension clearer. Stay tuned!

**Comment by thomaslombart** [comment] 2023-04-20 06:49
I've seen this is actually a duplicate of issue #4058, so I'll mark it as such.

**Closed by thomaslombart** 2023-04-20 06:49 UTC
Labels: bug, extension, extension: github

**Comment by jdk** [comment] 2023-04-20 08:14
@thomaslombart This is not the same as #4058   In an organization repo, no matter what, I am only able to see PRs by me. There are no filters and cant see anything from my team.

**Comment by thomaslombart** [comment] 2023-04-20 08:54
It is the same issue underlying it. The `Search Pull Requests` command was built to help you search your PRs without having the PRs from your team or other PRs in mind. However, after discussing with the team, we realized it was confusing and so we'll revamp the way these commands work. Since both issues are based on the fact that you can only see your PRs, we prefer having one to avoid having too many issues in the repository.
