### ISSUE TITLE
[Extension bug]Can't log in with master password

### ISSUE THREAD

**Issue by albas99** [raycast/extensions#490] opened 2021-12-07 05:50 UTC
I installed the Bitwarden CLI and extension and upon logging in, it prompted me to enter my master password which I did correctly several times, but it kept telling me "Invalid Credentials". After it showed me the first time, I logged in to the Bitwarden Desktop app using the same master password to make sure I'm not mistaken and it logged in successfully, but I kept trying it on the Raycast extension and it kept telling me "Invalid Credentials". Is there any fix to this?

**Comment by pomdtr** [comment] 2021-12-07 09:23
Hi, this is a duplicate of #360 
This error is due to some transformation made by raycast on the text input field.

I will update the extension as soon as the api is updated to support raw text in input fields. Sorry for the inconvenience :/

**Comment by albas99** [comment] 2021-12-07 15:51
Oh, thanks for the clarification, does that mean I should just close the issue or leave it open, maybe for later reference?

> Hi, this is a duplicate of #360 This error is due to some transformation made by raycast on the text input field.
> 
> I will update the extension as soon as the api is updated to support raw text in input fields. Sorry for the inconvenience :/

**Comment by mathieudutour** [comment] 2021-12-13 13:23
Let's close it, #360 will be fixed in the next release

**Closed by mathieudutour** 2021-12-13 13:23 UTC
