### ISSUE TITLE
[YouTube Downloader] YTD chokes on MKV files

### ISSUE THREAD

**Issue by chrismessina** [raycast/extensions#12235] opened 2024-05-07 21:01 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

When attempting to download a file that was originally uploaded as an MKV (I think), the YTD extension fails.

### Steps To Reproduce

I'm on macOS Sonoma 14.4.1 (23E224) running Raycast v1.72.1. I have the current version of the YouTube Downloader.

1. Attempt to download [this video](https://www.youtube.com/watch?v=HZeIhiNbSMg).
2. Notice that the video download completes but produces an error: "Output format mp4 is not available" 

### Current Behaviour

Attempting to download [this video](https://www.youtube.com/watch?v=HZeIhiNbSMg):

![2024-05-07 (13 22 12) Arc](https://github.com/raycast/extensions/assets/22610/4c91b2a7-72b8-46fa-b512-bb2072d56bc5)

...Results in an error: "Output format mp4 is not available"

![2024-05-07 (13 22 21) Arc](https://github.com/raycast/extensions/assets/22610/db343a1e-c425-4fa6-b2fa-a36c2d0a37ca)

The extension probably should not be showing the MP4 formatted files in the Format dropdown if that format is not natively available, OR the extension _should_ be able to convert MKV files to MP4s. 

### Expected Behaviour

The extension should be able to handle MKV-formatted files, ideally by presenting them in the file format download list.

**Comment by vimtor** [comment] 2024-05-11 13:28
Hi @chrismessina!

Sadly, this is a known issue. The problem is related to the new `ffmpeg` version and the library we are using to process the videos.

Check out the temporary solution here: https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625

**Comment by vimtor** [comment] 2024-07-04 07:52
This was fixed by https://github.com/raycast/extensions/pull/12583

@raycastbot close this issue

**Closed** 2024-07-04 07:52 UTC
Labels: bug, extension, status: stalled, extension: youtube-downloader
