### ISSUE TITLE
[YouTube Downloader] Downloading Audio only does not work even though there is the option in the dropdown of formats

### ISSUE THREAD

**Issue by AlNistor** [raycast/extensions#12292] opened 2024-05-11 08:06 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

#### Error:
```
Error: Output format mp3 is not available

capabilities.js:589:20

---
586:           }, [])

### Steps To Reproduce

1. Get a link from youtube
2. Open Raycast
3. Open the Download Video command
4. Link is autopasted
5. Choose Audio format
6. Command + Enter to start download
7. Error is shown

### Current Behaviour

Audio file is not downloaded

### Expected Behaviour

Audio fie is downloaded.

**Comment by vimtor** [comment] 2024-05-11 13:27
Hi @AlNistor!

Sadly, this is a known issue. The problem is related to the new `ffmpeg` version and the library we are using to process the videos.

Check out the temporary solution here: https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625

**Comment by vimtor** [comment] 2024-07-04 07:55
This was fixed by https://github.com/raycast/extensions/pull/12583

@raycastbot close this issue

**Closed** 2024-07-04 07:55 UTC
Labels: bug, extension, status: stalled, extension: youtube-downloader
