### ISSUE TITLE
[jetbrains-toolbox] projects won't open when the IDE is not already launched

### ISSUE THREAD

**Issue by jornetsimon** [raycast/extensions#2964] opened 2022-09-20 17:03 UTC
# Extension – [JetBrains Toolbox Recent Projects](https://www.raycast.com/gdsmith/jetbrains)

Author: @gdsmith 

## Steps To Reproduce

1. With the IDE closed, search for a project and launch it though the extension

## The current behavior
The IDE will remain on the welcome screen.
On the other hand, if the IDE is already launched, the project will open as expected.
If I'm correct, that was working fine before #2863

## The expected behavior
The project should always open

### Raycast version

Version: 1.39.3

**Comment by gdsmith** [comment] 2022-09-21 07:45
@jornetsimon can you confirm that the IDE opens, it's just that it doesn't open the requested project?

**Comment by jornetsimon** [comment] 2022-09-21 07:46
Yes, the IDE opens.

**Comment by gdsmith** [comment] 2022-09-21 07:55
Do you get two toasts, one saying "Opening (IDE name)" and another around 5 seconds after saying "Opening (project name)"? Or do you only get one with the IDE?

**Comment by jornetsimon** [comment] 2022-09-22 05:29
I have only one toast, "Opening Webstorm.app"

**Comment by jornetsimon** [comment] 2022-09-22 05:37
https://user-images.githubusercontent.com/936101/191666038-3535ca14-2279-4851-aa33-fe26098a75ed.mp4

**Comment by jornetsimon** [comment] 2022-09-22 18:35
Not sure why the video didn't work, here's the link https://share.cleanshot.com/oq9E2K

**Comment by gdsmith** [comment] 2022-09-25 15:01
@jornetsimon any chance you can try the linked PR?

**Comment by jornetsimon** [comment] 2022-09-26 06:12
@gdsmith Unfortunately no. https://share.cleanshot.com/in67GR

[open(toOpen)](https://github.com/raycast/extensions/blob/62ea6e77b5b025cfa33bc40ca49892ba684bac38/extensions/jetbrains/src/components/OpenInJetBrainsApp.tsx#L50) stays pending forever on my machine. It's being called with `/Users/psymon/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/222.4167.31/WebStorm.app`

**Comment by gdsmith** [comment] 2022-09-28 07:47
@jornetsimon can you confirm what your setting is for `Pop to Root Search` in Raycast Preferences → Advanced. If it is `Immediately` then can you see if the problem is fixed by selecting a different option there?

**Comment by jornetsimon** [comment] 2022-09-28 08:32
Yes, it does work on the prod build for `Pop to Root Search` >= 15s
Although, it is significantly faster to open the project on the `jb-open-menu-fixes-2` branch

**Comment by gdsmith** [comment] 2022-09-28 11:19
@pernielsentikaer any idea what we can do about this? Seems like Raycast is not giving commands long enough to finish when `Pop to Root Search` is shorter, is there anything we can do about it? 

I do think it's still an improvement code wise and reduces the delay, but I see you have closed the PR.

@jornetsimon in the new branch I shortened the delay between opening the app and opening the project which is why it is faster

**Comment by pernielsentikaer** [comment] 2022-09-30 07:38
Not sure how to get around this; the only thing I can think of is some preference to control this
<img width="770" alt="CleanShot 2022-09-30 at 09 37 26@2x" src="https://user-images.githubusercontent.com/38033107/193217096-313fe4c6-361b-4c65-9eb0-2e604cdf93c3.png">

But I'm not sure that's the best idea.

**Closed** 2022-11-27 21:11 UTC
Labels: bug, extension, status: stalled

**Comment by pernielsentikaer** [comment] 2022-11-29 21:53
Might be possible to fix it with the new argument, PopToRootType, for [closeMainWindow](https://developers.raycast.com/api-reference/window-and-search-bar#closemainwindow)
