### ISSUE TITLE
[Browser Bookmarks] Arc bookmarks unavailable and bursts JS memory limit

### ISSUE THREAD

**Issue by medmouine** [raycast/extensions#10273] opened 2024-01-22 06:40 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

## Environment
Mac Studio 2023
Chip Apple M2 Ultra 
Memory 64 GB 
macOS 14.3 Beta (23D5051b)

Raycast Version 1.65.1

Arc Version 1.26.2 (45413)
Chromium Engine Version 120.0.6099.234

## Additional debug info
- I tried switching the extension setting to a profile with only few items and to a brand-new profile with no bookmarks, but the issue persisted with no apparent differences. 
- I tried restarting and clearing the caches of all apps involved and my host machine, with no result or difference.

## Potential leads
- I have an **excessively large bookmarks collection** which could be the cause of the memory limit burst (over 3000 links with nested folders) (sorry i have ipad baby brain, i am working on it).
- I also suspect the front-end/UI framework could be the bottleneck due to the lack of pagination for the returned dataset. (mostly speculation)

### Current Behaviour

- Recurrent crashes, all reporting the same memory limit error
- Lists all Safari bookmarks (default ones i.e apple, bing, ...) but none of Arc bookmarks

### Expected Behaviour

- Fetch all bookmarks for Arc and its selected profile when enabled and provide text search
- optionally, paginate bookmarks for large responses

**Comment by thomaslombart** [comment] 2024-01-22 08:38
Thanks for bringing this up. It appears that this is a duplicate of issue #6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-01-22 08:38 UTC
Labels: bug, extension, extension: browser-bookmarks
