### ISSUE TITLE
[Music] love and add currently playing music to my library

### ISSUE THREAD

**Issue by kilias07** [raycast/extensions#3793] opened 2022-12-05 11:36 UTC
### Extension

https://www.raycast.com/fedevitaledev/music

### Description

command: love and add currently playing music to your library is not working properly. The song is added to library with radio icon and when I restarted music app or just want to play this new track apple music crashed. I don't if the problem is direct connected with raycast extension but is really frustrating.

### Steps To Reproduce

1. run apple music
2. play some radio
3. click on raycast love and add to my library
4. try to run this song from library

### Current Behaviour

apple music crashed

### Expected Behaviour

song supposed to be added into my library and marked as loved

**Comment by Rawnly** [comment] 2022-12-05 11:49
Thanks for reporting I'll investigate asap

**Comment by Rawnly** [comment] 2022-12-07 00:21
@kilias07  On which version are you currently on? I cannot reproduce the issue on macOS 13.0

**Comment by peterdev22** [comment] 2022-12-07 00:30
@Rawnly It looks like it's only reproducible on non-Apple radio stations

**Comment by Rawnly** [comment] 2022-12-07 01:06
@peterdev22 can you provide a link? I still cannot reproduce :/

**Comment by Rawnly** [comment] 2022-12-18 14:09
@peterdev22 can you check again? I cannot reproduce the issue anymore :/


https://user-images.githubusercontent.com/16429579/208302967-387f855a-919d-4322-9ac4-567e1e55ab8f.mp4

**Comment by peterdev22** [comment] 2022-12-19 01:06
@Rawnly Try playing it from the 'songs' tab instead.

For some reason it works fine if you play it from recently added.

**Comment by Rawnly** [comment] 2022-12-19 01:16
This seems to be more of a Music related problem... I'll have a look again anyway

**Comment by Rawnly** [comment] 2022-12-19 01:21
Ok, I think we shouldn't let people add/love "radio stations" to the Library. 
It seems like it is not something that is not expected in the Music app.

![CleanShot 2022-12-19 at 02 19 07@2x](https://user-images.githubusercontent.com/16429579/208330337-f7a85b78-2f4f-455f-9760-a459769e1512.png)

**Comment by peterdev22** [comment] 2022-12-19 06:31
@Rawnly I do agree, I use Apple music and i have never seen an option to save a radio station to your library.

**Comment by Rawnly** [comment] 2022-12-19 16:47
![CleanShot 2022-12-19 at 17 45 45](https://user-images.githubusercontent.com/16429579/208476887-3269bbfa-e3d6-4762-8b79-3cd8cde29486.png)
It seems like the Music app doesn't return any info about radios...

**Comment by kilias07** [comment] 2022-12-20 09:40
> @kilias07 On which version are you currently on? I cannot reproduce the issue on macOS 13.0
Sorry for such a late answer.

I'm currently on 13.2 Beta, but I noticed this issue already on stable version

**Comment by kilias07** [comment] 2022-12-20 09:56
Yes there is no way to add radio station to loved, but there is a possibility to add a specific song that comes from radio station to library.

https://user-images.githubusercontent.com/68988039/208638219-dc63cbef-d55c-4b32-8e30-7bdbcd635bb8.mp4

**Comment by Rawnly** [comment] 2022-12-20 14:32
@kilias07 thanks for your response, this is so weird. My idea is that maybe radio and "standard" songs have different IDs and the Music player when you try to add a new song from a radio does some sort of "conversion". The music extension is heavily Apple Script based, so we have limited control over what it does. I'll try to investigate further. In the meantime, if anyone has any idea about the problem feel free to report it.

**Comment by Rawnly** [comment] 2022-12-20 14:33
I just noticed that the song is removed from Library too after the crash.

**Comment by Rawnly** [comment] 2023-01-15 02:01
@raycastbot close this issue

**Closed** 2023-02-27 20:56 UTC
Labels: bug, extension, extension: music
