### ISSUE TITLE
[Change Case] ...

### ISSUE THREAD

**Issue by lemikeone** [raycast/extensions#4905] opened 2023-02-21 17:43 UTC
### Extension

https://www.raycast.com/es183923/change-case

### Description

It beaks special characters, like ":" or "ê". 

### Steps To Reproduce

Try to change the case of : "prêtes"

### Current Behaviour

Will change it to : PR TES

### Expected Behaviour

Should change it to : PRÊTES

**Comment by es183923** [comment] 2023-02-21 18:00
see #4841

**Comment by pernielsentikaer** [comment] 2023-02-22 07:48
Closing as duplicate of #4841

**Closed by pernielsentikaer** 2023-02-22 07:48 UTC
Labels: bug, extension, extension: change-case
