### ISSUE TITLE
[Bitwarden] load failed: error:04800066:PEM routines::bad end line

### ISSUE THREAD

**Issue by allinu** [raycast/extensions#13329] opened 2024-07-05 07:29 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Raycast Version

1.78.1

### macOS Version

15.0 Beta Version(24A5279h)

### Description

I have set the Clinet ID and the Client Secret, when I input my master password, it always tell me my master password were not right.

<img width="750" alt="image" src="https://github.com/raycast/extensions/assets/32992109/71552f81-6e2b-45ea-a60d-785e6b330fc2">

and these are log

```
Warning: Ignoring extra certs from `/Users/xxxx/.config/raycast/ca.pem`, load failed: error:04800066:PEM routines::bad end line
Invalid master password.
```

### Steps To Reproduce

1. install extensions
2. set Clinet ID and Client secret
3. input master password

### Current Behaviour

```
Warning: Ignoring extra certs from `/Users/xxxx/.config/raycast/ca.pem`, load failed: error:04800066:PEM routines::bad end line
Invalid master password.
```

### Expected Behaviour

Just please let me login.

**Comment by allinu** [comment] 2024-07-05 07:37
I make sure the master password is right, and I have login with `bw` in the terminal.

**Comment by niloque** [comment] 2024-07-07 09:55
I'd like to add that I have the same issue, while I'm using macOS 14.5 (23F79) and Raycast 1.78.1, so that's not macOS beta issue.

I am sure the master password is entered correctly. In my case however, I'm not using bitwarden-cli installed via Homebrew, but I download the `bw` binary myself and put it to `/usr/local/bin/bw`. The path is properly configured in the extension's config.

**Comment by jomifepe** [comment] 2024-07-19 08:41
Hey, can you make sure you don't have any leading or trailing spaces in your client id and secret? The extension simply looks for an `Invalid master password` response from the CLI, so something must be wrong. The other error that's above the message looks completely unrelated with the extension and it's probably not causing the issue.

**Comment by jomifepe** [comment] 2024-07-19 09:24
It's likely that the issue is on the CLI's side, please try to downgrade to `2026.6.0`, I stopped being able to login with client and secret on `2026.6.1`. Downgrading with homebrew is a bit of a pain, so I suggest npm or downloading it from [here](https://github.com/bitwarden/clients/releases/tag/cli-v2024.6.0) and either replacing the `bw` binary in the installed location (usually `/opt/homebrew/bin/bw` or `/usr/local/bin/bw`) or point the extension to the downloaded one using the preferences.

**Comment by niloque** [comment] 2024-07-19 09:32
Just to confirm: I've downgraded my CLI to `2024.6.0`, logged out from it, logged back in, checked if I can unlock my vault and after it worked, tried again in Raycast extension — worked as well. Thanks for your support, @jomifepe! 👍🏻

**Comment by jomifepe** [comment] 2024-07-26 17:21
@allinu Can you confirm if this works for you?

**Comment by cameronapak** [comment] 2024-07-30 15:26
Just want to say I ran into this issue. 

https://github.com/bitwarden/clients/issues/9919#issuecomment-2251406604 helped me get to version `2024.6.0`. 

Now it works

**Comment by jomifepe** [comment] 2024-07-30 16:54
> Just want to say I ran into this issue.
> 
> [bitwarden/clients#9919 (comment)](https://github.com/bitwarden/clients/issues/9919#issuecomment-2251406604) helped me get to version `2024.6.0`.
> 
> Now it works

Hey, awesome that I worked, be aware that that's pinning your version, so it won't be updated next time.

**Comment by cameronapak** [comment] 2024-07-30 16:57
> > Just want to say I ran into this issue.
> > [bitwarden/clients#9919 (comment)](https://github.com/bitwarden/clients/issues/9919#issuecomment-2251406604) helped me get to version `2024.6.0`.
> > Now it works
> 
> Hey, awesome that it worked for you, be aware that it's pinning your version, so it won't be updated next time.

Thanks for the heads up! When since I'm following this thread, I'll know when it's fixed and will unpin. Thanks!

**Comment by jomifepe** [comment] 2024-08-12 10:04
@allinu Feel free to comment if the issue persists.

@raycastbot close this issue

**Closed** 2024-08-12 10:05 UTC
Labels: bug, extension, extension: bitwarden
