### ISSUE TITLE
Spotify Beta Server Errors - unusable

### ISSUE THREAD

**Issue by ahatzz11** [raycast/extensions#6035] opened 2023-04-19 12:22 UTC
### Extension

https://raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Server error.
    at X0 (/Users/alexhatzenbuhler/.config/raycast/extensions/56a2815e-83a0-44c6-8f3c-04ef778f3298/nowPlaying.js:58:268)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. On my mac
2. After I authorized spotify
3. Perform any action with the spotify beta

Happy to give more details if needed. I've tried to re-authorize and reboot spotify running on my mac.

### Current Behaviour

Server error over and over

### Expected Behaviour

Things to work properly!

**Comment by peduarte** [comment] 2023-04-19 13:06
Hi, thanks for the issue. I'm unable to reproduce. Are you on our [Slack](https://raycast.com/community)? Can you DM me on there, or join the #spotify-beta-testers channel so we can debug together? Thanks!

**Comment by peduarte** [comment] 2023-04-21 10:19
Closing due to lack of detail, but feel free to re-open with more info. Thanks

**Closed by peduarte** 2023-04-21 10:19 UTC
Labels: bug, extension, extension: spotify-beta
