### ISSUE TITLE
[GitHub] ... Open issues are not showing

### ISSUE THREAD

**Issue by jSagvold28** [raycast/extensions#4980] opened 2023-02-25 14:43 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

I have a total of 4 issues open and they arent showing up in Raycast

### Steps To Reproduce

1. Open raycast
2. go to github issues
3. look

### Current Behaviour

No issues fount

### Expected Behaviour

Display open issues

**Comment by thomaslombart** [comment] 2023-02-27 10:58
Could you give more details about your open issues? I can't reproduce it so it's a bit hard to debug it.

**Comment by jSagvold28** [comment] 2023-02-27 13:04
Weird, it happened a few times I just restarted my mac and it seemed work well. Thank you for your time!

**Comment by thomaslombart** [comment] 2023-02-27 13:52
That's weird. I'll close this issue, but don't hesitate to reopen it or reach out in case it happens again.

**Closed by thomaslombart** 2023-02-27 13:52 UTC
Labels: bug, extension, extension: github
