### ISSUE TITLE
[Google Chrome] ...

### ISSUE THREAD

**Issue by rschmidtner** [raycast/extensions#6043] opened 2023-04-19 16:08 UTC
### Extension

https://www.raycast.com/Codely/google-chrome

#### Error:
```
Error: Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1
      set active tab index of _wnd to 2
    end tell
    return true
  
96:99: execution error: The variable NaN is not defined. (-2753)

    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1

```

### Steps To Reproduce

I installed the Google Chrome extension with the Raycast store. Than I run the "Search Tabs" command. Running the command shows me a list of my open tabs. As soon as I select one and hit enter I end up with the picture below:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/67690427/233135321-efc97d61-28c0-423f-ba86-c12376b05fe9.png">

System: macOS Ventura Version 13.3.1 (22E261)
Chrome Version: Version 112.0.5615.137 (Official Build) (x86_64)

**Comment by andreaselia** [comment] 2023-04-19 16:29
@rschmidtner is it a normal/newly opened tab that this is happening with, or a tab within a group?

**Comment by karolre** [comment] 2023-04-20 19:56
Because I cannot reproduce the issue, I have prepared the pull request which should provide more info allowing to help understand the root cause: https://github.com/raycast/extensions/pull/6068

**Comment by karolre** [comment] 2023-04-25 07:21
I was able to find a root cause thanks to more extensive error logging. The issue is related to the fact that in some cases MacOS generates windows identifiers which are represented in exponential form: `1,304973562E+9`. Full exception below.

```
Error: Issue with tab: '[tab name]~~~[tab url]~~~~~~1,304973562E+9~~~4'
Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
      set index of _wnd to 1
      set active tab index of _wnd to 4
    end tell
    return true
  
96:99: execution error: The variable NaN is not defined. (-2753)

Command failed with exit code 1: osascript -e 
    tell application "Google Chrome"
      activate
      set _wnd to first window where id is NaN
```

Now I need to find a way to resolve it.

**Comment by karolre** [comment] 2023-04-25 22:54
Raised PR to fix the issue: https://github.com/raycast/extensions/pull/6172

**Comment by rschmidtner** [comment] 2023-04-26 17:16
@andreaselia it is a normal tab, not one within a tab group

**Comment by rschmidtner** [comment] 2023-04-26 17:24
Is PR #6172 live already? If so it  did not solve the issue for me (still getting the same error)

**Comment by andreaselia** [comment] 2023-04-26 19:18
> Is PR #6172 live already? If so it did not solve the issue for me (still getting the same error after reinstallation of the extension)

@rschmidtner the PR is still open pending review, the updates will go live automatically when the PR is merged in.

**Closed** 2023-04-27 04:20 UTC
Labels: bug, extension, extension: google-chrome

**Comment by rschmidtner** [comment] 2023-04-27 21:58
Works like a charm, thanks folks!
