### ISSUE TITLE
op CLI on Apple Silicon

### ISSUE THREAD

**Issue by Arelav** [raycast/extensions#11619] opened 2024-04-03 20:55 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

On Apple Silicon, the default path is `/opt/homebrew/bin` not `/usr/local/bin`
As the result I have `op` installed in my path the extension cannot find it and shows me welcome screen how to check the installation using `la -la /usr/local/bin/op`

### Steps To Reproduce

* Install 1p CLI using official instructions.
* check `op --version` in terminal and confirm it's installed properly
* Add 1password app from Raycast store

### Current Behaviour

Showing welcome screen
![CleanShot 2024-04-03 at 14 54 27@2x](https://github.com/raycast/extensions/assets/1059539/4deaf910-dd86-4b31-b6c7-23e340c57c49)

### Expected Behaviour

If all requirements provided it should work both on Intel and Apple Silicon Homebrew setups

**Comment by Arelav** [comment] 2024-04-03 20:58
UPDATE: I'm not sure it's the correct place to report a bug. It's app implementation not Raycast bug.
I pressed report bug from 1password Raycast store page and get into this page. I was expecting to report extenstion bug not for Raycast.

**Comment by Luk4h** [comment] 2024-04-08 12:02
Hello @Arelav, to solve your problem you can just modify in the extension settings the "1Password CLI Path" to your "/opt/homebrew/bin". I am working on some improvements to the extension and an auto fix for this will also be shipped. For now refer to the fix I told you.

**Comment by Luk4h** [comment] 2024-04-08 13:53
Can you confirm that the issue is now resolved with the latest version?

**Comment by Luk4h** [comment] 2024-04-08 14:16
@raycastbot close this issue

**Closed** 2024-04-08 14:17 UTC
Labels: bug, extension, extension: 1password

**Comment by Arelav** [comment] 2024-04-08 23:34
> Can you confirm that the issue is now resolved with the latest version?

I confirm it works now. Thank you.
