### ISSUE TITLE
[OneNote] I installed both OneNote and this Extension 

### ISSUE THREAD

**Issue by iSteveyang** [raycast/extensions#4853] opened 2023-02-17 18:03 UTC
### Extension

https://www.raycast.com/alewandowski/onenote

### Description

But it says I don't have MS OneNote app
Does it require any permissions? I didn't see a notice asking for permission

![image](https://user-images.githubusercontent.com/20753221/219737072-f01a26d2-f84f-4dd6-9ce4-746ab114ead4.png)

### Steps To Reproduce

1. MacOS 13.2.1 MacBook Pro 16-inch 2019
2. MS OneNote 16.70,  Raycast 1.47.3

**Comment by alewandows** [comment] 2023-02-17 19:26
Hi 👋, 
Thanks for the feedback. 

Could you please check if these 2 directories exist on your system? 
~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft/UserInfoCache/
~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex

The extension browses the content of these folders. 
To do so, it needs full disk access permission. 
Hope it will help!

**Comment by iSteveyang** [comment] 2023-02-18 14:39
Hi 👋, thanks for your prompt reply, both folders you mentioned are on my system and both have content in them, Raycast also has full disk access permission. 
I reboot my Mac, reinstalled the extension and "Microsoft OneNote is not installed" is still there🤔
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/20753221/219871064-65fd206e-1d51-438c-898c-e379a34abce0.png">
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/20753221/219871075-435a36d9-8040-4a90-b962-b9fdf425b471.png”>

**Comment by benstegink** [comment] 2023-02-21 03:24
@alewandows I think this is also dependent on having it installed from the App Store? I have the Microsoft 365 Enterprise version installed and I don't have either of those paths. Instead, those files are in Library/Microsoft OneNote/ instead of Library/com.microsoft.onenote.mac. So I'm also getting that OneNote isn't installed :(

**Comment by alewandows** [comment] 2023-02-24 07:46
@benstegink Thanks for the feedback. I will update the code in order to look up files in these folders. Could you please send me an output of the whole paths that I need, and their content ?

**Comment by benstegink** [comment] 2023-02-24 13:31
@alewandows so I was wrong...the UI shows one thing, but when I navigate through he terminal it show another. However, like @iSteveyang, Raycast is saying that OneNote isn't installed.

![image](https://user-images.githubusercontent.com/6474247/221190836-82365f37-bff3-479b-b9c3-39ebbff5f620.png)

**Comment by alewandows** [comment] 2023-02-24 14:42
@benstegink OK, that's a progress... 
Could you please give me an output of the content of these 2 folders ? 

~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft/UserInfoCache/
~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application Support/Microsoft User Data/OneNote/15.0/FullTextSearchIndex

Thanks again for helping

**Comment by benstegink** [comment] 2023-02-24 15:35
@alewandows absolutely, here you are:
![image](https://user-images.githubusercontent.com/6474247/221219756-8b4cc3b1-a0f1-4347-aae2-186b268b8464.png)

![image](https://user-images.githubusercontent.com/6474247/221219967-24f65e7c-ad66-4883-9e42-dc85b81df48b.png)

**Comment by benstegink** [comment] 2023-04-15 16:14
@alewandows, any hope of a fix for this? It's still an issue for me ☹️

**Comment by alewandows** [comment] 2023-04-17 06:09
Hi @benstegink , 
Unfortunately I was not able to reproduce the bug. 
I don't give up but don't have much time to work on it for now.

**Comment by holygrolli** [comment] 2023-04-17 21:29
I was eager to try this extension and was confronted with this issue immediately. I debugged the extension and got the error
```
23:06:15.866 Error: too many attached databases - max 10
    at f.handleError (/Users/xyz/.config/raycast/extensions/onenote/index.js:5384:19)
    at f.run (/Users/xyz/.config/raycast/extensions/onenote/index.js:5305:20)
    at create_or_update_db (/Users/xyz/.config/raycast/extensions/onenote/index.js:9188:8)
    at async Object.<anonymous> (/Users/xyz/.config/raycast/extensions/onenote/index.js:9674:12)
```

A `ls ~/Library/Containers/com.microsoft.onenote.mac/Data/Library/Application\ Support/Microsoft\ User\ Data/OneNote/15.0/FullTextSearchIndex` showed me around 15 files. Cleaning up the `FullTextSearchIndex` by deleting the files was leaving me with a not working search functionality in OneNote. I had to close all my notebooks and open only the required ones. Now the extension and OneNote work.

It would be nice to have a simple filter, which notebooks you want to use. I don't know where the 10 dbs limit comes from.

Hope this helps

**Comment by benstegink** [comment] 2023-04-17 21:37
Ahhh, thanks @holygrolli , that would probably be my issue as I have about 20 open notebooks. Not sure that with my use case I can get down to 10 :( It would be nice to be able to raise that limit; or like you mentioned, be able to configure which 10 to search even if you have more open.

I can try to verify this on my side by closing some of my notebooks temporary and cleaning up those files

**Closed** 2023-06-19 22:30 UTC
Labels: bug, extension, status: stalled, extension: onenote

**Comment by yoghurtdewdew** [comment] 2023-08-25 08:46
I have the same problem!
