### ISSUE TITLE
[Apple Reminders] ...

### ISSUE THREAD

**Issue by aeadedoyin** [raycast/extensions#11061] opened 2024-03-02 18:03 UTC
### Extension

https://www.raycast.com/raycast/apple-reminders

#### Error:
TypeError: t?.find is not a function

Nd:create-reminder.tsx:59:37

---
56:   mutate?: MutatePromise<{ reminders: Reminder[]

### Steps To Reproduce

It just happened not sure how to reproduce.
Just clicked on "Create Reminder" and got the screenshot.

![CleanShot X - 2024-03-02 at 07 03 08 PM@2x](https://github.com/raycast/extensions/assets/20503883/28cb83f8-98de-4a06-9c4a-0e71c091ed89)

**Comment by RayBB** [comment] 2024-03-02 20:50
Duplicate of https://github.com/raycast/extensions/issues/11057

**Comment by thomaslombart** [comment] 2024-03-03 12:14
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/11057, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-03 12:14 UTC
Labels: bug, extension, extension: apple-reminders
