### ISSUE TITLE
[GitHub] Trying to see the created issues I see in a first instance the issues but then I see the error view

### ISSUE THREAD

**Issue by sadotsoy** [raycast/extensions#7405] opened 2023-07-05 17:24 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

I've tried with a token with all the scopes. 

```JS
TypeError: Cannot read properties of null (reading 'name')

cy:IssueActions.tsx:31:39

---
28:   children?: React.ReactNode;
29: };
30: 
31: export default function IssueActions({ issue, mutateList, mutateDetail, children }: IssueActionsProps) {
32:   const { github } = getGitHubClient();
33: 
34:   const viewer = useViewer();
---

    at ray-list-item
Cn:index.js:20:21682
DA:created-issues.js:1284:5567
```

### Steps To Reproduce

1. Run *Created Issues* command.

**Comment by sadotsoy** [comment] 2023-07-05 17:30
I'd like to contribute to the extension, let me know how can I do that :)

**Comment by thomaslombart** [comment] 2023-07-06 08:33
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/4831, so I'll mark it as such.

Here's our guide about contributing to extensions if you want to fix it though: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension)

**Closed by thomaslombart** 2023-07-06 08:33 UTC
Labels: bug, extension, extension: github

**Comment by sadotsoy** [comment] 2023-07-06 16:15
thanks @thomaslombart, I'll check it :)
