### ISSUE TITLE
[1Password] Switch accounts or use multiple accounts

### ISSUE THREAD

**Issue by rahulkeerthi** [raycast/extensions#4808] opened 2023-02-15 11:50 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Ability to switch accounts, or search multiple accounts at the same time

### Who will benefit from this feature?

Anyone with multiple accounts (e.g. work + personal)

**Comment by pernielsentikaer** [comment] 2023-02-15 12:00
Duplicate of #4744

**Closed by pernielsentikaer** 2023-02-15 12:00 UTC
Labels: feature request, extension, extension: 1password
