### ISSUE TITLE
[Browser Bookmarks] ...

### ISSUE THREAD

**Issue by zeroibc** [raycast/extensions#9494] opened 2023-12-01 02:53 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1

**Comment by thomaslombart** [comment] 2023-12-01 02:54
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6810, so I'll mark it as such.

**Closed by thomaslombart** 2023-12-01 02:54 UTC
Labels: bug, extension, extension: browser-bookmarks
