### ISSUE TITLE
[Jira] Most commands fail after recent raycast update (1.49.3)

### ISSUE THREAD

**Issue by cybercode** [raycast/extensions#5907] opened 2023-04-12 17:13 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

I don't know if the error is related to the update or a change on atlassians side, but most  commands fail with various errors:

# Reported Issues
> Error: Rendering failed:
> Missing required component property "title"

# Search Issues
-   ok

# Open Issues
> Error: Rendering failed:
> Missing required component property "title"

# Recently Updated Issues
> TypeError: Cannot read properties of null (reading 'name')
> 
> Zy:IssueListItem.tsx:15:40
>     at ray-list-section
> cs:index.js:23:15636
> Or:index.js:5:5486

# Watched Issues
> Error: Rendering failed:
> Missing required component property "title"

# Active Sprint
> TypeError: Cannot read properties of null (reading 'name')
> 
> t\_:IssueListItem.tsx:15:40
>     at ray-list-section
> cs:index.js:23:15636
> Or:index.js:5:5486

# My Filters
-   OK

### Steps To Reproduce

1. Search for "Jira"
2. Select any of the above commands

It will flash what looks like the correct search bar (placeholder text, optional droplets) and then display "Something Went Wrong".

Note that I uninstalled and reinstalled/reconnected the extension to jira.

### Current Behaviour

Most commands crash with fatal errors.

### Expected Behaviour

They should return a list of issues

**Comment by thomaslombart** [comment] 2023-04-12 18:29
I can't reproduce any of these errors. The `Cannot read properties of null (reading 'name')` makes me think of the following issue: https://github.com/raycast/extensions/issues/5726 so probably not related to the latest update.

**Comment by thomaslombart** [comment] 2023-04-12 18:48
I've pushed a fix that could maybe solve this issue. Do you still have the error?

**Comment by cybercode** [comment] 2023-04-12 19:07
@thomaslombart do I need to clone the extension repos and run in dev mode to test?

**Comment by thomaslombart** [comment] 2023-04-12 19:10
@cybercode No, your extensions should automatically be updated. If it's not the case, you can run the `Check For Extensions Updates` command.

**Comment by thomaslombart** [comment] 2023-04-12 19:17
Oh, that's interesting. It seems like `issuetype` can be... `null` sometimes, which is surprising. I'd assume a Jira issue would always have an issue type. Now that you have the local extension enabled, would you mind adding a `console.log` in the `IssueListItem.tsx` component (like below) and share the result with me? It'll be really helpful to clarify my assumptions 😊

```tsx

export default function IssueListItem({ issue, mutate }: IssueListItemProps) {
  console.log(issue.fields);
  const updatedAt = new Date(issue.fields.updated);
  const assignee = issue.fields.assignee;

  const keywords = [issue.key, issue.fields.status?.name, issue.fields.issuetype?.name, issue.fields.priority?.name];

  if (issue.fields.assignee) {
    keywords.push(issue.fields.assignee.displayName);
  }

  return (
    // ...
```

**Comment by cybercode** [comment] 2023-04-12 19:46
it's way too much data (and kind of proprietary 😎 ). Anyway, doing some debugging —I dumped the `issuetype` field in the console.log and ever entry as an `iconUrl` field. Also set optional chaining on every reference to `issuetype.iconUrl` in the extension and it still crashes pointing at the function entry point. So I think the message may be a misdirection.

**Comment by thomaslombart** [comment] 2023-04-12 19:54
Thank you for this useful information! What is the priority? This one also has an `iconUrl`.

**Comment by cybercode** [comment] 2023-04-12 20:07
you found it the problem:
```diff
modified   src/components/IssueListItem.tsx
@@ -41,7 +41,7 @@ export default function IssueListItem({ issue, mutate }: IssueListItemProps) {
           tooltip: `Assignee: ${assignee ? assignee.displayName : "Unassigned"}`,
         },
         { date: updatedAt, tooltip: format(updatedAt, "EEEE d MMMM yyyy 'at' HH:mm") },
-        { icon: issue.fields.priority.iconUrl, tooltip: `Priority: ${issue.fields.priority?.name}` },
+        { icon: issue.fields.priority?.iconUrl, tooltip: `Priority: ${issue.fields.priority?.name}` },
       ]}
       actions={<IssueActions issue={issue} mutate={mutate} showDetailsAction={true} />}
     />
```
let me see if I can track down the particular "issue" and we can look at the data.

**Comment by thomaslombart** [comment] 2023-04-12 20:11
Ah, so that's the culprit. Is it possible that a Jira issue doesn't have any priorities?

**Comment by cybercode** [comment] 2023-04-12 20:12
yes:
"Priority None"

**Comment by thomaslombart** [comment] 2023-04-12 20:18
All right, thank you for this! I'll make a proper fix tomorrow 😊

**Comment by cybercode** [comment] 2023-04-12 20:21
You also need to fix `IssueActions.changePriority`.

**Closed** 2023-04-13 08:49 UTC
Labels: bug, extension, extension: jira

**Comment by cybercode** [comment] 2023-04-13 12:01
@thomaslombart thank you. confirmed.
