### ISSUE TITLE
[Color Picker] Add Color Contrast Feature

### ISSUE THREAD

**Issue by ssylvia** [raycast/extensions#8267] opened 2023-09-06 14:29 UTC
### Extension

https://www.raycast.com/thomas/color-picker

### Description

It would be great if you could easily compare two colors to determine their contrast ratio and check if it meets WCAG standards for readability. You can compare the last two picked colors or choose two colors from the color palette.

### Who will benefit from this feature?

Developers and Designs who are creating accessible apps/website for others.

**Comment by fgeierst** [comment] 2023-09-07 07:51
Duplicate of #5924

**Closed** 2023-11-06 08:04 UTC
Labels: feature request, extension, status: stalled, extension: color-picker
