### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by itsvikkyyy** [raycast/extensions#11068] opened 2024-03-03 01:14 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

It gets automatically logged out, specially when I Connect my device to VPN. I have to login back again every time.

### Steps To Reproduce

If this is an actual bug, and just not in my scenario, you should be able to get the results with connecting VPN and disconnecting after using it for sometime.

**Comment by thomaslombart** [comment] 2024-03-19 13:47
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-19 13:47 UTC
Labels: bug, extension, extension: spotify-player
