### ISSUE TITLE
[Window Management] Next/Previous Desktop no longer moves window to next or previous desktop

### ISSUE THREAD

**Issue by wkwhwh** [raycast/extensions#12493] opened 2024-05-21 13:18 UTC
### Extension

raycast://extensions/raycast/window-management/

### Raycast Version

1.74.1

### macOS Version

14.5

### Description

When using Next Desktop or Previous Desktop the desktop changes but the window is no longer moved, it stays on the desktop it was.

![CleanShot 2024-05-21 at 14 10 00](https://github.com/raycast/extensions/assets/7226788/1fb40d4f-64e7-48b5-88d3-d8ef96706d4e)

### Steps To Reproduce

1. On an active app call Raycast with cmd + space
2. Write "Next Desktop" to call move to next desktop for that window and press Enter

### Current Behaviour

"Next Desktop" moves focus to next desktop but doesn't move the window, same for "Previous Desktop".

### Expected Behaviour

"Next Desktop" and "Previous Desktop" should move focus to the next or previous desktop but also move the current active app.

**Comment by kimbirkelund** [comment] 2024-05-22 05:16
I'm experiencing the same issue.

**Comment by 1activegeek** [comment] 2024-05-23 16:58
I'm also noticing this issue today. The odd thing is, the Raycast settings window will move properly doing this with the keyboard shortcut assigned, but no other windows on my desktop will.

**Comment by kimbirkelund** [comment] 2024-05-23 17:00
I'm seeing the same. That is weird.

**Comment by imvasen** [comment] 2024-05-23 19:30
same

**Comment by mathieudutour** [comment] 2024-05-24 08:59
That's a bug in macOS 14.5. We are looking for a workaround but I'll be closing this issue as it's not related to 3rd party extensions

**Closed by mathieudutour** 2024-05-24 08:59 UTC
Labels: bug, extension, status: stalled

**Comment by michael-jeremiah-walker** [comment] 2024-05-26 14:37
having this same error as well!

would be great to get it resolved, even if it means adapting to the new MacOS requirements.

**Comment by newro** [comment] 2024-06-09 04:42
The ability to moving windows is one of my most used features.
Recently (since the latest macOS update, as mentioned in the issue) it hasn't worked, which is very inconvenient.
Is the solution to wait for a macOS bug fix?
Is BTT or other apps suffering from the same issue?

**Comment by monsterhxw** [comment] 2024-07-31 22:06
same issue

**Comment by maximeprn** [comment] 2024-08-30 00:26
same issue...

**Comment by 1activegeek** [comment] 2024-08-30 00:33
@monsterhxw @maximeprn I would suggest opening a new ticket/issue. This was actually resolved and was working for me, so the core issue was resolved.
- Could be that you are on an outdated version of Raycast? 
- Could be that you have not updated the extension? 
- Could be that you are running macOS Beta? (I now have the issue again, but this is new to the macOS beta which isn't officially "supported" by anyone since we're still in beta)

If it's none of those things - then you should open a new ticket and upload the logs so the devs can get some details as this issue listed here was in fact fixed.

**Comment by maximeprn** [comment] 2024-08-30 00:51
> * Could be that you are running macOS Beta? (I now have the issue again, but this is new to the macOS beta which isn't officially "supported" by anyone since we're still in beta)

I am indeed using macOS Beta, so it must be the reason for this!

**Comment by hitzhangjie** [comment] 2024-11-30 10:21
1.86.1 still not fixed.

**Comment by lcxnash** [comment] 2024-11-30 12:16
This feature suddenly started working normally for a short period about two months ago, but recently it stopped working again. I can’t remember whether it was after a macOS update or a Raycast update. I hope it can be thoroughly fixed soon.

**Comment by hitzhangjie** [comment] 2024-11-30 13:19
This problem is caused by broken macOS windows management API. The team has found a solution to work around this.
<img width="554" alt="image" src="https://github.com/user-attachments/assets/dfa32de0-3dc2-40d8-8266-0adc9e0209e8">

Before I use hammerspoon to write scripts to move windows to different spaces, now it had the same problem. And the reason is the same. macOS new version changed the API.

**Comment by souvikmaji** [comment] 2024-12-01 03:44
@hitzhangjie can you please link the issue?

**Comment by elif14** [comment] 2025-01-07 19:42
Sequoia 15.2 and Raycast 1.88.4 still not fixed.

**Comment by 1activegeek** [comment] 2025-01-07 19:57
> Sequoia 15.2 and Raycast 1.88.4 still not fixed.

Try updating to 15.3 - could actually be a bug and a bug on both sides. 
I'm on 15.3 and 1.88.4 and it's working fine.

**Comment by drekuru** [comment] 2025-02-26 23:16
Experiencing same issue on OS: 15.3.1 and Raycast: 1.93.0

**Comment by kmdupr33** [comment] 2025-02-28 15:12
me too

**Comment by mathieudutour** [comment] 2025-05-19 07:27
This issue is not related to the API or extensions. Could you please use the `Send Feedback` command inside Raycast or use the #help or #bugs channel in our [Slack Community](https://www.raycast.com/community) 😊
