### ISSUE TITLE
Almost All Authy OTP records say Corrupted

### ISSUE THREAD

**Issue by gabeperez** [raycast/extensions#10423] opened 2024-01-29 14:35 UTC
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Almost all of my OTP records in this extension say "Corrupted," which makes the extension useless. I tried re-installing 3 times and got the same results.
<img width="550" alt="Screenshot 2024-01-29 at 23 34 36" src="https://github.com/raycast/extensions/assets/10750190/5c2359a7-3f33-4c20-a506-38c01a037c4d">

### Steps To Reproduce

1. Set Up Account
2. Finish Account Set Up
3. See all OTP with status Corrupted.

**Comment by gdsmith** [comment] 2024-01-29 14:55
@gabeperez have you tried changing your backup password?

**Comment by alecloudenback** [comment] 2024-03-13 02:01
duplicate of #10544?

**Closed** 2024-05-12 02:15 UTC
Labels: bug, extension, status: stalled, extension: authy
