### ISSUE TITLE
[Bitwarden] Unlock via Touch ID when native Vault App is unlocked

### ISSUE THREAD

**Issue by sewqawsdewq332** [raycast/extensions#9306] opened 2023-11-17 20:34 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Request to enable unlock via Touch ID when native Vault App is unlocked, similar to how the browser extensions work.

### Who will benefit from this feature?

Mac based users with Touch ID enabled.

### Anything else?

[](https://bitwarden.com/help/biometrics/)

**Comment by jomifepe** [comment] 2023-11-22 10:56
Hello, thanks for the suggestion. Multiple people have asked for this, and here's why it's not implemented yet: https://github.com/raycast/extensions/issues/8075#issuecomment-1694508921

**Comment by jomifepe** [comment] 2023-12-29 16:17
Duplicate of #8075 

@raycastbot close this issue

**Closed** 2023-12-29 16:17 UTC
Labels: feature request, extension, extension: bitwarden
