### ISSUE TITLE
[Browser Bookmarks] Bookmarks other than Favorites and Reading List are not recognized.

### ISSUE THREAD

**Issue by elgar328** [raycast/extensions#6469] opened 2023-05-11 03:54 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

It worked fine in previous versions. After updating, bookmarks other than Favorites and Reading List are not recognized at all.

The image below shows bookmarks in the Safari browser.
<img width="305" alt="image" src="https://github.com/raycast/extensions/assets/93251045/623b61d4-acc9-49b8-9374-bda24eb270bf">

In raycast, only favorites and reading lists are recognized.
<img width="402" alt="스크린샷 2023-05-11 오후 12 45 13" src="https://github.com/raycast/extensions/assets/93251045/f6b34865-a2fd-4bfd-a76f-65b809b2e932">

### Steps To Reproduce

MacBook Pro 14 (2021)
Apple M1 Pro
16GB ram
Ventura 13.3.1 (a)

Browser Bookmarks
May 10, 2023 (latest version)

**Comment by thomaslombart** [comment] 2023-05-15 09:06
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6313, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-15 09:06 UTC
Labels: bug, extension, extension: browser-bookmarks
