### ISSUE TITLE
[Jira] Epic drop down list is empty

### ISSUE THREAD

**Issue by TiboCiteo** [raycast/extensions#13187] opened 2024-06-27 07:37 UTC
### Extension

https://www.raycast.com/raycast/jira

### Raycast Version

1.77.3

### Description

When I try to create a Jira issue, all drop-down lists and auto-complete features work except for the 'Epic' drop-down list.

### Steps To Reproduce

When I try to create a Jira issue, all drop-down lists and auto-complete features work except for the 'Epic' drop-down list.

### Expected Behaviour

'Epic' drop-down list display epics

**Comment by thomaslombart** [comment] 2024-07-03 08:48
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/12646, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-03 08:48 UTC
Labels: bug, extension, extension: jira
