### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by jessekinzer** [raycast/extensions#6723] opened 2023-05-22 18:12 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

Having some issues with the Todois extension: The items that are scheduled for today seem to be showing up in separate sections all labeled tomorrow. Instead of under today. 

https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1684431056677139

https://raycastcommunity.slack.com/files/U04PT7DNUNM/F0595BU0SGG/image.png

### Steps To Reproduce

1. Activate Raycast
2. Type "Home" 
3. Navigate to the todoist "Home" page
4. type command + P
5. Switch mode to today. 
6. Type command + P 
7. switch to tomorrow 
https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1684431056677139

### Current Behaviour

The items that are scheduled for today seem to be showing up in separate sections all labeled tomorrow. Instead of under today. 

### Expected Behaviour

All items scheduled for today should be present in the Today tab.

**Comment by thomaslombart** [comment] 2023-05-23 07:34
Thanks for bringing this up. It appears that this is a duplicate of issue #4359, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-23 07:34 UTC
Labels: bug, extension, extension: todoist
