### ISSUE TITLE
Worker terminated due to reaching memory limit

### ISSUE THREAD

**Issue by romanskorobagatko** [raycast/extensions#14435] opened 2024-09-12 19:34 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.82.5

### macOS Version

14.6.1

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Open bookmarks search
2. Type in a search query

### Current Behaviour

Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

**Comment by thomaslombart** [comment] 2024-09-22 07:40
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-09-22 07:40 UTC
Labels: bug, extension, extension: browser-bookmarks
