### ISSUE TITLE
[Spotify Player] regularly needs to be reauthenticated

### ISSUE THREAD

**Issue by danielraffel** [raycast/extensions#14828] opened 2024-10-07 21:36 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.83.2

### macOS Version

15.0.1

### Description

Spotify regularly says something went wrong and I have to re-login to authenticate it. I am not sure why this is happening. Part of me wonders if it's because I'm using Tailscale and it takes a moment for it to connect and create a "VPN" connection. Maybe this tries to connect and doesn't retry gracefully. I'm not really sure but it's a hunch since creating a VPN can take a few seconds. 

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"\n    at Zn (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:5:6290)\n    at D0\n    at _r (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2593)\n    at ray-navigation-stack\n    at Eo (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2094)\n    at Suspense\n    at Nr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:7:2335)\n    at ray-root\n    at Ii (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:3103)","breadcrumbs":[]}: OAuth request creation is not available when command is launched in background


```

### Steps To Reproduce

1. successfully auth Spotify in raycast using a machine that's on tailscale
2. restart machine and wait a few days, notice that Raycast will ask for auth 

### Current Behaviour

Spotify can't authenticate 

### Expected Behaviour

Spotify should have a token from previously being authenticated

**Comment by thomaslombart** [comment] 2024-10-08 07:34
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-10-08 07:34 UTC
Labels: bug, extension, extension: spotify-player
