### ISSUE TITLE
[Single Disk Eject] ...

### ISSUE THREAD

**Issue by adamjrichman** [raycast/extensions#2317] opened 2022-07-20 19:33 UTC
# Extension – [Single Disk Eject](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/single-disk-eject/)
Author: @johndturn

## Description

Does not work in Big Sur. I would try to eject different types of drives, especially OWC Envoy m.2 drives, and it would show as successful, but they are not removed from Finder and when I go to disconnect them, Finder yells at me for not ejecting the disk. So the success is not actually accurate. This happened on previous versions of Raycast as well. 

### Raycast version
Version: 1.38.0

**Comment by johndturn** [comment] 2022-07-20 19:52
I believe that I know what the issue is here. I think that for disks that take a longer time to eject, the timeout is triggered early and shows success when it's not quite there. 

I'll work on this soon and get a fix out for it. Thanks for bringing it up.

**Comment by johndturn** [comment] 2022-07-28 03:57
@adamjrichman I believe this will be fixed once https://github.com/raycast/extensions/pull/2404 is merged. Feel free to follow there.

**Comment by johndturn** [comment] 2022-07-29 22:36
@adamjrichman This has been merged, and delivered. Please let me know if you still experience issues.

**Closed** 2022-10-03 04:37 UTC
Labels: bug, wontfix, extension
