### ISSUE TITLE
[Arc] "Open in Arc" action incorrectly opens in Little Arc

### ISSUE THREAD

**Issue by IGassmann** [raycast/extensions#5085] opened 2023-03-01 20:59 UTC
### Extension

https://www.raycast.com/the-browser-company/arc

### Description

When using the "Search Arc" command and then performing the "Open in Arc" action in a result instead of the "Open in Little Arc" action, Raycast will incorrectly open the selected item in a Little Arc window.

### Steps To Reproduce

1. Use "Search Arc" command 
2. Type "some search text"
3. Press CMD + K
4. Select "Open in Arc" and press Enter

### Current Behaviour

Open a Little Arc window

### Expected Behaviour

Should open a normal Arc window.

**Comment by thomaspaulmann** [comment] 2023-03-06 09:09
Seems to be a duplicate of #4576

**Closed by thomaspaulmann** 2023-03-06 09:09 UTC
Labels: bug, extension, extension: arc

**Comment by IGassmann** [comment] 2023-03-06 10:43
@thomaspaulmann I don't think that is the same issue. Both seem to be pretty distinct issues.
