### ISSUE TITLE
[Zoom] "RangeError: Invalid time value" in Upcoming Meetings 

### ISSUE THREAD

**Issue by davidmankin** [raycast/extensions#2742] opened 2022-08-31 16:25 UTC
# Extension – [Zoom](https://github.com/raycast/extensions/tree/2e371837b4ea93b23bddec1d56729a689082be3b/extensions/zoom/)
Author: @thomaslombart

## Description
I tried to see upcoming meetings in zoom.  Note that my organization uses a custom hostname for zoom.  However the login process to authorize the extension went smoothly. 

## Error:

The guts of the error are too big for an issue. See this gist:

https://gist.github.com/davidmankin/2797948feacab559080145805ad62f2b

```
RangeError: Invalid time value

Ez:upcoming-meetings.js:66:62949

[...elided...] 
---

Ioe:upcoming-meetings.js:79:3634
upcoming-meetings.js:79:4063
    at Array.reduce (<anonymous>)
BH:upcoming-meetings.js:79:4024
upcoming-meetings.js:79:7545
Object.useMemo:react-reconciler.production.min.js:5:27195
exports.useMemo:react.production.min.js:25:208
Coe:upcoming-meetings.js:79:7540
Ql:react-reconciler.production.min.js:5:20846
```

## Steps To Reproduce

1. Install Zoom extension to Raycast
1. Choose "upcoming meetings"
2. Login and authorize
3. Choose "upcoming meetings" again

## The current behavior

Error message: "Something went wrong"

## The expected behavior

🤷  I've never seen it work. 

### Raycast version
Version: 1.39.1

**Comment by thomaslombart** [comment] 2022-09-01 12:48
Thanks for reporting! This issue is a duplicate of https://github.com/raycast/extensions/issues/2721.

**Comment by davidmankin** [comment] 2022-09-01 14:11
Oops I should have looked first. Sorry! (In my defense a bit, the “report issue” in the extension came right here with without a reminder to look for duplicates.)

**Closed** 2022-09-03 13:43 UTC
Labels: bug, extension
