### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by Peterb999** [raycast/extensions#7383] opened 2023-07-04 02:23 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

I've installed ffmpeg and still get the message "ffmpeg is not installed." Help! Thanks. 

### Steps To Reproduce

I'm running Raycast 1.54.1 in MacOS 13.4.1

**Comment by vimtor** [comment] 2023-07-08 10:22
I think this is a duplicate of #7230. I will add an option for the user to specify where `ffmpeg` is installed 😀

**Comment by vimtor** [comment] 2023-08-07 17:07
This has been fixed in #7350

**Comment by vimtor** [comment] 2023-08-07 17:07
This has been fixed in #7350

@raycastbot close this issue

**Closed** 2023-08-07 17:07 UTC
Labels: bug, extension, extension: youtube-downloader
