### ISSUE TITLE
[Spotify Player] Crashing when searching

### ISSUE THREAD

**Issue by ericrbg-harmonic** [raycast/extensions#15476] opened 2024-11-21 17:18 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.86.0

### macOS Version

Sequoia 15.1

#### Error:
```
TypeError: Cannot read properties of null (reading 'id')

Es:PlaylistsSection.tsx:13:35
---
10:   limit?: number
```

### Steps To Reproduce

1. Open the search dialog
2. Search "audio video disco"
3. Crash.

If it is relevant, I have it on the "songs first" priority mode.

**Comment by thomaslombart** [comment] 2024-11-22 11:01
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/15458, so I'll mark it as such.

**Closed by thomaslombart** 2024-11-22 11:01 UTC
Labels: bug, extension, extension: spotify-player
