### ISSUE TITLE
[Jira] Recently Updated Issues and My Filters actions fail every time

### ISSUE THREAD

**Issue by treuherz** [raycast/extensions#6958] opened 2023-06-06 08:36 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

Both actions fail every time with the following error

#### Error:
```
Error: Rendering failed:
Missing required property "title" for Unknown
```

I'm not aware of anything strange or special about my Jira workspace but this is the only one I've ever used with Raycast

### Steps To Reproduce

1. Connect the Jira extension to an Atlassian Cloud workspace
2. Run the My Filters or Recently Updated Issues actions

### Current Behaviour

I get the "Something went wrong" screen with the above error

### Expected Behaviour

It shows a list of search filters, or a list of recently updated issues

**Comment by thomaslombart** [comment] 2023-06-06 09:52
Thanks for bringing this up. It appears that this is a duplicate of issue #6634, so I'll mark it as such.

**Closed by thomaslombart** 2023-06-06 09:52 UTC
Labels: bug, extension, extension: jira

**Comment by treuherz** [comment] 2023-06-06 10:05
Ah, sorry! I found it on "Recently updated" and was searching too literally for the error string.
