### ISSUE TITLE
Data is not getting loaded [Spotify Beta] ...

### ISSUE THREAD

**Issue by akishaha** [raycast/extensions#6010] opened 2023-04-18 11:51 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-beta

#### Error:
```

```

**Comment by peduarte** [comment] 2023-04-18 11:57
Hey there, could you provide enough information so we can understand what the issue is, please?

**Comment by peduarte** [comment] 2023-04-21 09:51
Closing due to lack of detail, but feel free to re-open with more info. Thanks

**Closed by peduarte** 2023-04-21 09:51 UTC
Labels: bug, extension, extension: spotify-beta
