### ISSUE TITLE
[Amazon AWS] Unable to run "assume -c"

### ISSUE THREAD

**Issue by rcb1gh** [raycast/extensions#6298] opened 2023-05-03 14:00 UTC
### Extension

https://github.com/raycast/extensions/blob/949a86e860cf200f6d24140b5ca5d3cdd7727f51/extensions/amazon-aws

### Description

Running into this error when trying to run "Run Profile Script"

<img width="739" alt="image" src="https://user-images.githubusercontent.com/132468806/235937762-4377b47e-6751-4c61-b823-1e9a1bf5bcf8.png">

Running this on M1 MacBook Pro

```
Error: Command failed: /bin/zsh -l -c "assume -c default"
zsh:1: command not found: assume


zsh:1: command not found: assume
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

### Steps To Reproduce

Unsure as to what to do...

### Current Behaviour

- Running Run Profile is failing.
- All other AWS calls are failing.

### Expected Behaviour

Expect all the AWS functions to work! (trying to use this for DynamoDB listing...)

**Comment by JonathanWbn** [comment] 2023-05-03 16:49
@rcb1gh The "Run Script Command" is intended to be customized to your personal use case. So the `command not found: assume` is expected behavior if you have not configured anything for this command.

The other commands, however, are expected to work (like "DynamoDB"). Could you share what is failing when running that one?

**Comment by rcb1gh** [comment] 2023-05-04 03:42
Ok! Got it -- I do have DynamoDB tables on this profile, and while it shows up in the dropdown, I'm unable to view the DynamoDB tables. There are root credentials. I see a lock icon that is crossed out -- not sure why that is. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/132468806/236107945-d61737b1-40b5-4b3b-80a2-14916d8cd604.png">

<img width="54" alt="image" src="https://user-images.githubusercontent.com/132468806/236108027-91d01849-38e2-4b34-85dc-cdb1930547a7.png">

**Comment by JonathanWbn** [comment] 2023-05-04 05:53
Could you please share your `.aws/config` **with all secret values redacted** to understand how your secrets are managed (mfa, source profiles, region...)? If you e.g. use `aws-vault` you would have to start a session with `aws-vault` first. In that case the locked lock would be replaced with an unlocked lock icon.

**Comment by JonathanWbn** [comment] 2023-05-06 06:25
@rcb1gh The issue you describe is being fixed with https://github.com/raycast/extensions/pull/6358

**Comment by rcb1gh** [comment] 2023-05-06 10:14
Hey, sorry for the delay, was flying. Attaching my redacted config here.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/132468806/236618100-6b6bfd9f-875e-4b54-9383-1f9dbbb986f4.png">

Glad to hear that it's being fixed! Thanks : )

**Closed** 2023-05-08 05:11 UTC
Labels: bug, extension, extension: amazon-aws

**Comment by andreacavagna01** [comment] 2023-09-08 10:27
Why I'm not seeing any profile selector in the Extension? Is there a documentation for that?
