### ISSUE TITLE
[Jira] No longer caches the last project you created a ticket in

### ISSUE THREAD

**Issue by qbunt** [raycast/extensions#6587] opened 2023-05-16 16:00 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

When creating multiple tickets, you have to select the same project over and over again. In the past (previous, deprecated version of the extension), this project ID would be pre-selected when you triggered the `Create Ticket` command. We have hundreds of projects but I primarily work on only a few, I suspect this could be a similar situation for many people using the extension.

I think ideally this list would sort by last used instead of purely alphabetical like it is today.

### Steps To Reproduce

1. Invoke the `Create Issue` command in Raycast
2. Observe that the project selection has been reset from the last time it was invoked

### Current Behaviour

Project selection is reset for every invocation of the `Create Issue` command

### Expected Behaviour

Retain the last selected project in the `Create Issue` command in the Jira extension

**Comment by thomaslombart** [comment] 2023-05-16 20:15
Thanks for bringing this up. It appears that this is a duplicate of issue #5988, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-16 20:15 UTC
Labels: bug, extension, extension: jira

**Comment by qbunt** [comment] 2023-06-26 21:58
@thomaslombart this issue is still occurring, I don't think it is actually related to https://github.com/raycast/extensions/issues/5988. The selected project is always set to the first alphabetical project in the list, rather than last selected
