### ISSUE TITLE
[Todoist] Inconsistencies between Native App and Extension Due Dates

### ISSUE THREAD

**Issue by OkDubs** [raycast/extensions#6888] opened 2023-05-31 22:26 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

In the case one has completed their tasks for the day, in the event an additional task is added for "today" at an explicit time, the extension seems to incorrectly assign the task for "tomorrow" rather than "today". This happens regardless if this addition is done via the native app or the Raycast Extension. 

### Steps To Reproduce

1. When initial tasks of the day are completed
2. A new task is added for a later time in that same day
3. Due dates of the task are listed as "tomorrow" in the Raycast Extension. 

### Current Behaviour

Tasks added for "tomorrow" at the initially listed time rather than appearing for "due today"

### Expected Behaviour

Tasks should be listed for "due today" at the particular time that was initially given.

**Comment by thomaslombart** [comment] 2023-06-01 08:35
Thanks for bringing this up. It appears that this is a duplicate of issue #4359, so I'll mark it as such.

**Closed by thomaslombart** 2023-06-01 08:35 UTC
Labels: bug, extension, extension: todoist
