### ISSUE TITLE
[ChatGPT] ...

### ISSUE THREAD

**Issue by weitanai** [raycast/extensions#6688] opened 2023-05-20 08:34 UTC
### Extension

https://www.raycast.com/abielzulio/chatgpt

#### Error:
```

```

### Steps To Reproduce

1. download  chatgpt extension
2. config openai_key
3. open chatgpt extension
4. can not connect

### Current Behaviour

can not connect with network

### Expected Behaviour

get chatgpt connect

**Comment by Nauxscript** [comment] 2023-05-20 09:32
hi there 👋! 
I couldn't reproduce this bug and it's working perfectly.
But I found that you are in china now, just like me, so maybe you should use some magic we call 🪜, and make sure you are in the `enhance mode` if you are using clashx pro.

据我所知，使用 ClashX pro 如果不开 `enhance mode` 即 `增强模式`，也是会出现无法访问的情况，原因是软件内部的请求没有走代理通道，如果你使用的是 ClashX pro, 记得打开该模式；如果使用的是其他的代理工具，请咨询相关的开发者。

**Comment by Nauxscript** [comment] 2023-05-20 09:32
@raycastbot close this issue

**Closed** 2023-05-20 09:32 UTC
Labels: bug, extension, extension: chatgpt
