### ISSUE TITLE
Zotero extension: Failed to query / SyntaxError: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by JohnAtl** [raycast/extensions#927] opened 2022-02-16 21:14 UTC
# Extension – [zotero](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/zotero)

Author: @sadanand-singh

## Description
Just installed the extension. Added my Zotero API Key and User ID.
Tried to search and received the error message.

<img width="344" alt="Screen Shot 2022-02-16 at 4 05 56 PM" src="https://user-images.githubusercontent.com/5720074/154357958-5d29e48a-33ac-4dc0-aaed-55217a775a27.png">

## Steps To Reproduce

1. Install and configure extension
2. Attempt to search

## The current behavior
Gives an error when trying to search.

## The expected behavior
No errors, just search.

### Raycast version

Version: 1.28.0

**Comment by sadanand-singh** [comment] 2022-02-17 06:21
do you have anything in your library? I have only seen this error when there is nothing in the library. Otherwise I have not been able to replicate this.

**Comment by sadanand-singh** [comment] 2022-02-17 06:21
Also by the way - I am the main author. :)

**Comment by JohnAtl** [comment] 2022-02-17 15:00
Yes, 2871 references.

**Comment by sadanand-singh** [comment] 2022-02-20 23:55
Can' reproduce this. Can you please provide something to reproduce? may be a sample zotero account credentials with your api key etc?

**Comment by JohnAtl** [comment] 2022-02-21 00:05
Are these settings correct?

<img width="283" alt="Screen Shot 2022-02-20 at 7 05 00 PM" src="https://user-images.githubusercontent.com/5720074/154870500-9252e669-b2c6-48ce-9929-2a7cc585a24b.png">

**Comment by sadanand-singh** [comment] 2022-02-21 00:11
Not really sure. I have typically given full permissions. All 3 in first and read/write for group. May be try with that and see if it works. If that works, I should probably find the exact required settings and update the README. Thanks.

**Comment by hofstee** [comment] 2022-04-07 22:31
You've probably put your Zotero username in the Zotero User ID field when configuring the application. You want the userID from 
`Your userID for use in API calls is [numbers]` on the [keys settings page](https://www.zotero.org/settings/keys).

**Comment by sadanand-singh** [comment] 2022-05-11 14:49
This can be closed by #1653 Since web API would not be needed anymore.

**Comment by sadanand-singh** [comment] 2022-05-24 14:40
Fixed by #1653

**Comment by sadanand-singh** [comment] 2022-05-24 14:40
#1653 closes this.

**Comment by sadanand-singh** [comment] 2022-05-29 16:40
This should be closed since new extension is based on local sqlite file

**Closed** 2022-07-30 14:27 UTC
Labels: bug, wontfix, extension
