### ISSUE TITLE
[iMessage 2FA] Feature Request: Mark 2FA codes as read

### ISSUE THREAD

**Issue by JoshKn** [raycast/extensions#10864] opened 2024-02-21 15:27 UTC
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

Automatically marking 2FA codes as read when you copy them to your clipboard would be a really nice feature to have. As I don't like having unread notifications, I need to go into the messages app to mark the code as read.
 I love this extension because it makes it so easy to handle with 2FA codes, so the requested feature is the only thing missing for me personally.

### Who will benefit from this feature?

Anyone who uses the extension and likes to have an organized iMessage inbox.

**Comment by angelineflorajohn** [comment] 2024-02-22 15:31
To add onto @JoshKn's feature request, I'd like to have the option to delete the 2FA (and not just mark it as read).

**Comment by navtoj** [comment] 2024-02-22 16:58
@raycastbot close this issue

<br>

| @JoshKn | Duplicate of #4404 |
| ------- | ------------------ |

> I investigated it, but couldn't get it to work. I pushed my [work-in-progress branch](https://github.com/raycast/extensions/tree/2fa-mark-as-read). If you'd like, you can take it and try again.

_Originally posted by @thomaspaulmann in https://github.com/raycast/extensions/issues/4404#issuecomment-1407726768_

<br>

| @angelineflorajohn | Duplicate of #9838 |
| ------------------ | ------------------ |

> I'm not sure this is possible at the moment.
>
> The extension reads texts from the Messages sqllite db, which is an unofficially supported method of interacting with Apple Messages. While we could in theory delete them from the database, they wouldn't sync to other iCloud devices.

_Originally posted by @ronaldheft in https://github.com/raycast/extensions/issues/9838#issuecomment-1868008324_

**Closed** 2024-02-22 16:58 UTC
Labels: feature request, extension, extension: imessage-2fa
