### ISSUE TITLE
[Dropbox] Error message during authentification

### ISSUE THREAD

**Issue by parisetflorian** [raycast/extensions#11651] opened 2024-04-05 09:51 UTC
### Extension

https://www.raycast.com/chyroc/dropbox

### Description

During authentication, I received an error message that this app has been blocked pending approval.

**Comment by sxn** [comment] 2024-04-15 08:18
hey @parisetflorian, thanks for bringing this up! 
This issue looks like a duplicate of https://github.com/raycast/extensions/issues/11651, so I'll close this one.

**Closed by sxn** 2024-04-15 08:18 UTC
Labels: feature request, extension, extension: dropbox
