### ISSUE TITLE
[Browser Bookmarks]...

### ISSUE THREAD

**Issue by avelino** [raycast/extensions#9386] opened 2023-11-23 11:20 UTC
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: maxObjectCount exceeded
    at Ve.parseBuffer (/Users/avelino/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:34:60380)
    at a8 (/Users/avelino/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:39:24495)
    at /Users/avelino/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:39:25037
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```

### Steps To Reproduce

....

**Comment by thomaslombart** [comment] 2023-11-23 12:33
Thanks for bringing this up. It appears that this is a duplicate of issue #8640, so I'll mark it as such.

**Closed by thomaslombart** 2023-11-23 12:33 UTC
Labels: bug, extension, extension: browser-bookmarks
