### ISSUE TITLE
[Folder Search] Query string is duplicated when Folder Search is opened as a fallback command.

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#6333] opened 2023-05-04 21:15 UTC
### Extension

https://www.raycast.com/GastroGeek/folder-search

### Description

When opening Folder Search as a fallback command for a query, it duplicates the query text. [See example below](https://imgur.com/a/kOghQ8t):
<p>
<a href="https://imgur.com/a/kOghQ8t"><img src="https://i.imgur.com/7C9rc8D.png"></a>

### Steps To Reproduce

1. Enter a search query in Raycast
2. Select Folder Search as the fallback command
3. Folder Search opens with the query duplicated

### Current Behaviour

The query string is duplicated when opening Folder Search as a fallback command.

### Expected Behaviour

Folder Search should not open a search with the initial query duplicated.

**Comment by omarshahine** [comment] 2023-05-11 15:33
@nukesean  cannot repro this (but saw this happen exactly once today, and am not sure how or why it happened).

Is this consistent repro?

**Comment by nukesean** [comment] 2023-05-12 22:50
@omarshahine Really? That's surprising, because yes, it is consistent for me. It happens 100% of the time on all three of my computers: an Intel iMac, an M1 Mac Mini, and an M1 MacBook Air, all running macOS Ventura.

**Comment by omarshahine** [comment] 2023-05-14 15:45
So I was able to get it to repro only when there are "no results".

question, do you get any results at all from Folder Search when searching (non fallback)? 

Did you try and change your search scope from This Mac to your use profile?

It seems to be an issue on first use.

**Comment by nukesean** [comment] 2023-05-15 07:45
Yes, the command works perfectly fine except for this issue; i.e., it returns the desired results if I (1) launch it directly and then enter my search, or (2) launch it as a fallback command and then manually delete the duplicated text.

The duplication from fallback happens regardless of whether there are "no results." For example, I just searched for "dropbox" as a fallback, and it once again produced "dropboxdropbox."

Yes, I've switched the scope back and forth from This Mac to my user profile several times since I first installed it almost a year ago.

**Comment by omarshahine** [comment] 2023-06-10 18:01
I have a bug fix for this that I am testing. It's now happening to me a lot, the fix is a hack but it seems to work.

Is anyone here willing to test it out?

**Comment by pernielsentikaer** [comment] 2023-06-13 08:26
Merged and closed, please give it a shot @nukesean - you can run `Check for extension Updates` to ensure you have the newest update

**Closed by pernielsentikaer** 2023-06-13 08:26 UTC
Labels: bug, extension, extension: folder-search

**Comment by pernielsentikaer** [comment] 2023-06-13 10:48
I can see that, same happens here - we'll take a look 🙂

**Comment by omarshahine** [comment] 2023-06-16 16:50
@pernielsentikaer 

Thanks, my regex has a bug in it that I managed to not notice, but then I also fixed that and also still reproduce the issue. So I'm at a loss as to what to do. I think the Raycast team may need to take a look as I suspect it's a bug in Raycast. If it's fixed I can back out this hack.

**Comment by omarshahine** [comment] 2023-06-16 19:08
Ooh exciting, I have a fix that works this time. Will test for a few days and create a new PR

**Comment by omarshahine** [comment] 2023-06-21 07:50
@nukesean can you update your extension and verify the fix?

**Comment by nukesean** [comment] 2023-06-24 06:14
@omarshahine I can confirm the duplicated portion is deleted within a few ms of the command opening. Thanks!

**Comment by omarshahine** [comment] 2023-06-24 06:27
Fantastic
