### ISSUE TITLE
[Notion] Actions to view/hide properties not appearing when creating a database page

### ISSUE THREAD

**Issue by imdadkadir** [raycast/extensions#8443] opened 2023-09-18 11:51 UTC
### Extension

https://www.raycast.com/notion/notion

### Description

![SCR-20230918-lnbb](https://github.com/raycast/extensions/assets/51536591/960a52e9-9796-4b06-a29d-a2801feebcf5)

Actions to view/hide properties not appearing when creating a database page

### Steps To Reproduce

Use 'Create Database Page' extension

### Current Behaviour

![SCR-20230918-lnbb](https://github.com/raycast/extensions/assets/51536591/ef6b3465-ec0c-4a9b-b9ae-e76d2ef4b150)

### Expected Behaviour

![SCR-20230918-lnww](https://github.com/raycast/extensions/assets/51536591/323e0cd7-64a2-4204-bd71-f1949499e187)

**Comment by erics118** [comment] 2023-09-21 23:43
It's not a feature right now. it would require a lot of changes for this to be possible.

dupe of #5016

I may have a possible way of implementing this, after #8340 is merged

**Closed** 2023-11-21 00:12 UTC
Labels: bug, extension, status: stalled
