### ISSUE TITLE
[Notion] Add page to database fails to load

### ISSUE THREAD

**Issue by JuanseHevia** [raycast/extensions#15025] opened 2024-10-22 03:10 UTC
### Extension

https://www.raycast.com/notion/notion

### Raycast Version

v 1.84.3

### macOS Version

Sequoia 15.0.1

#### Error:
```
TypeError: Cannot read properties of undefined (reading 'options')

rm:PagePropertyField.tsx:24:2

---
21:   users: User[]

### Steps To Reproduce

1. Open the extension
2. Open the "Create new page in database"

### Current Behaviour

TypeError: Cannot read properties of undefined (reading 'options')

rm:PagePropertyField.tsx:24:2

---
21:   users: User[];
22: }): JSX.Element;
23: export function PagePropertyField({
24:   type,
25:   databaseProperty,
26:   itemProps,
27:   relationPages,
---

    at ray-form
te:index.js:20:19513
sm:create-database-page.js:74:14392

### Expected Behaviour

I should see an input form for adding pages to any of my databases

**Comment by bkeys818** [comment] 2024-10-22 11:11
Okay, this is due to our latest update. To confirm, can you reproduce this error every time you open the "Create new page in database" command?

**Comment by JuanseHevia** [comment] 2024-10-22 14:10
Yes, the same happens when I run that command.

**Comment by bkeys818** [comment] 2024-10-24 13:14
Could you directly email me the following folder? You can find my email on my GitHub profile page.

`/Users/${user_name}/Library/Application Support/com.raycast.macos/extensions/5f2e08d5-fdf1-4171-b252-aa53065621b4`

**Comment by JuanseHevia** [comment] 2024-10-24 23:41
Just sent!

**Comment by JuanseHevia** [comment] 2024-10-25 15:31
Hi!

Is there any alternative we can consider that does not imply me running a
development branch locally? I wouldn't want any undesired effects in my
personal computer.

**Comment by bkeys818** [comment] 2024-10-26 14:33
Unless someone else has been able to repeat the issue, I'm unsure what else we could do.

If it makes any difference, the branch I linked is only one commit ahead of main. All that commit does is add some additional error throws.

**Comment by JuanseHevia** [comment] 2024-10-26 15:07
Got it, thanks for the support Ben.

Funny thing, I just cleared the content cache and the problem is solved!

**Comment by bkeys818** [comment] 2024-11-02 15:17
Odd, glad you found a fix! Hopefully that will be able to help out someone else too.

**Comment by bkeys818** [comment] 2024-11-02 15:17
@raycastbot close this issue

**Closed** 2024-11-02 15:18 UTC
Labels: bug, extension, extension: notion
