### ISSUE TITLE
[Apple Notes] ... Search Notes Function - Database Error

### ISSUE THREAD

**Issue by pionear10** [raycast/extensions#10879] opened 2024-02-22 14:15 UTC
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

I cannot use the "search notes" feature. I get the following error message and no results ever get shown.

![search notes](https://github.com/raycast/extensions/assets/160870490/0ad86a77-e588-4695-b8fa-f88eaf406d37)
"Database disk image is malformed"

### Steps To Reproduce

I'm on a Mac Sonoma 14.2.1 running Raycast Version 1.68.1
I go to the raycast search window and click on "search notes" and I get the error message attached above

### Current Behaviour

See Above

### Expected Behaviour

I expect it to show me results from my notes in accordance with my search terms.

**Comment by tobalsan** [comment] 2024-02-26 11:05
Got the same issue with a Mac Studio M2 Max, macOS Ventura 13.6.3, Raycast 1.68.1.

**Comment by ChaithzKRU** [comment] 2024-03-22 08:55
Got same issue.

**Comment by thomaslombart** [comment] 2024-03-22 11:17
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6916, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-22 11:17 UTC
Labels: bug, extension, extension: apple-notes
