### ISSUE TITLE
[Spotify Player] ... Something went wrong

### ISSUE THREAD

**Issue by HafsahNasir** [raycast/extensions#13388] opened 2024-07-09 12:43 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.7.8.1

### macOS Version

Sonoma 14.0

#### Error:
```
Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant","error_description":"Refresh token revoked"}

a1.refreshTokens:OAuthService.js:134:18

---
131:         if (!response.ok) {
132:             const responseText = await response.text()

### Steps To Reproduce

Whenever I run the menu bar player, or the now playing command this error shows up. I've tried uninstalling and re-installing the extension however this only solved the problem for 2-3 days before it happened again.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by thomaslombart** [comment] 2024-07-09 13:08
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/13167, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-09 13:08 UTC
Labels: bug, extension, extension: spotify-player
