### ISSUE TITLE
[Battery Optimizer] MacOS 15 compatibility

### ISSUE THREAD

**Issue by cancel-cloud** [raycast/extensions#14490] opened 2024-09-16 18:55 UTC
### Extension

https://www.raycast.com/Qetesh/battery-optimizer

### Raycast Version

1.82.5

### macOS Version

15.0

### Description

The extension does not work on MacOS 15.0
I do not want to pressure anyone or say that it is not working on the release day of a new OS version, i thought, that may my screenshot and report could help others, that they're not alone with the problem i encountered.
![Screenshot 16 09 2024 at 20-51-26@2x](https://github.com/user-attachments/assets/f7b18d03-6919-4a61-9d85-0966a977e78f)

### Steps To Reproduce

1. update to latest MacOs version
2. set battery charging limit

### Current Behaviour

![Screenshot 16 09 2024 at 20-51-26@2x](https://github.com/user-attachments/assets/d314205c-8871-41fa-8afc-b87bca204cde)

### Expected Behaviour

it should set the pre set charging max amout to 80%

**Comment by VatsalSy** [comment] 2024-09-17 11:47
Yes, I was able to reproduce this problem. 😢 

I could have a look unless if @Qetesh already has an idea how to do it? Unfortunately, since this is a side thing, I must find time to do it... :(

**Comment by VatsalSy** [comment] 2024-09-17 11:47
@raycastbot assign me
@raycastbot keep this issue open

**Comment by VatsalSy** [comment] 2024-09-17 11:49
@raycastbot rename this issue to "[Battery Optimizer] MacOS 15 compatibility"

as this is not a one off problem with setting the charge limit. None of the three commands are working...

**Comment by marvinpowell** [comment] 2024-09-19 19:28
+1 having the same issue here with MacOS 15.

**Comment by j3lte** [comment] 2024-09-19 21:17
Unfortunately the developer can't fix this easily, because it relies on [BCLM](https://github.com/zackelia/bclm), where the issue originates: https://github.com/zackelia/bclm/issues/49. Until that tool gets updated, it won't be fixed here...

**Comment by Amine-hmala** [comment] 2024-09-26 17:41
+1  having the same issue .

**Closed** 2024-11-25 18:37 UTC
Labels: bug, extension, status: stalled, extension: battery-optimizer

**Comment by mohammad-malik** [comment] 2025-05-11 14:25
This wasnt fixed? :/

**Comment by j3lte** [comment] 2025-05-11 18:34
@mohammad-malik see [this comment](https://github.com/raycast/extensions/issues/14490#issuecomment-2362214662)

**Comment by mohammad-malik** [comment] 2025-05-12 10:39
Yeah but this was supposed to have added support for batt, but doesn't seem like that happened
