### ISSUE TITLE
[Spotify Player] 'hide icon when idle' flag not functioning as intended

### ISSUE THREAD

**Issue by xhi-nico** [raycast/extensions#10477] opened 2024-01-31 15:28 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

When attempting to use the 'hide icon when idle' flag under the 'Menu Bar Player' command, the menu bar player does not appear, even when Spotify is active and playing music. 

If I disable the flag temporarily and re-enable it while music is playing, the menu bar spotify player appears correctly. As soon as I quit spotify, the icon will disappear as intended, though will NOT re-appear when you start playing music again. 

### Steps To Reproduce

1. Quit Spotify
2. Enable 'hide icon when idle' flag
3. Open Spotify and start playing music
4. the menu bar player does not activate

**Comment by xhi-nico** [comment] 2024-05-11 14:15
still an active issue, not stale.

**Comment by thomaslombart** [comment] 2024-05-23 12:12
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10466, so I'll mark it as such.

**Closed by thomaslombart** 2024-05-23 12:12 UTC
Labels: bug, extension, extension: spotify-player
