### ISSUE TITLE
[Linguee] Something went wrong

### ISSUE THREAD

**Issue by bulutfatih** [raycast/extensions#5002] opened 2023-02-26 21:54 UTC
### Extension

https://www.raycast.com/geekdada/linguee

#### Error:
```
CanceledError: canceled
```

I get this error too often. Mostly when I open it first time and try to type something, after a few characters, it crashes. Or try a few consecutive requests can cause error. I don't understand, but it happens quite often.
You can see the video. I got this error at least 5 times in a minute.

https://user-images.githubusercontent.com/28598997/221439641-ef5bd158-ab0b-4868-a914-e3b839d50ed0.mp4

### Steps To Reproduce

1. Open English-German dictionary
2. Try to type `fernsehgerät`. (don't copy paste)

**Comment by bulutfatih** [comment] 2023-02-26 22:19
Added reproduce step with a better one, @geekdada.

**Comment by geekdada** [comment] 2023-02-26 23:45
The old implementation doesn't allow Raycast to cancel an ongoing request, which I suspect is the cause of your issue. The PR migrates the related part to the Raycast suggested way. Please have a look later when you see this issue is closed.

**Comment by geekdada** [comment] 2023-03-06 21:29
@raycastbot close this issue

**Closed** 2023-03-06 21:29 UTC
Labels: bug, extension, extension: linguee

**Comment by bulutfatih** [comment] 2023-03-06 22:39
@geekdada Thank you so much for your effort! I appreciate it. 🚀
