### ISSUE TITLE
[Hypersonic] Loading forever after Action

### ISSUE THREAD

**Issue by mv-stns** [raycast/extensions#10139] opened 2024-01-13 11:49 UTC
### Extension

https://www.raycast.com/reboot/hypersonic

#### Error:
```
Error: Command "Active Tasks" must be activated before it can be run in the background

```

After doing any Action, like adding a Task, label, filtering or anything else, Hypersonic keeps loading forever.

### Steps To Reproduce

1. Use Hypersonic
2. Add Task
3. Loadingbar appears in Hypersonic
4. Keeps loading until Raycast has been reopend (cmd + space x2)

### Current Behaviour

Slow Workflow, unwanted more commands to see propagation to notion

### Expected Behaviour

Fast refreshes

**Comment by mv-stns** [comment] 2024-01-13 11:53
https://github.com/raycast/extensions/assets/21103251/e50a979c-06d4-43d1-be04-0d710c0afed7

Heres a Video Demonstrating my Issue, me spamming buttons to finish tasks or create multiple

**Comment by mv-stns** [comment] 2024-01-21 14:13
Is hypersonic being actively worked on? @prrrcl

**Comment by biknandy** [comment] 2024-02-14 01:59
@mv-stns @prrrcl I figured out a fix for this is there some way I can create a PR for this? The problem is in [refreshMenuBar](https://github.com/raycast/extensions/blob/7e22f15094fd7cb6cb75c30852ad4833bac07999/extensions/hypersonic/src/features/todo-list/utils/refresh-menu-bar.ts#L1) function, there's no catch there so if a user has the menu bar action disabled or some error happens, hypersonic freezes.

**Closed** 2024-02-14 08:22 UTC
Labels: bug, extension, extension: hypersonic
