### ISSUE TITLE
[iMessage 2FA] Any way to delete the 2FA message automatically as soon as it's been used?

### ISSUE THREAD

**Issue by xhi-nico** [raycast/extensions#10741] opened 2024-02-13 16:21 UTC
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

It would be ideal if the extension could also delete the 2FA message from Messages as soon as it's used. Not sure if this is even possible.

### Who will benefit from this feature?

Everyone that uses this extension

**Comment by alwinsamson** [comment] 2024-02-15 20:08
I'm not sure if this works in macOS, but in iOS 17.3, Settings > Passwords > Password Options > Clean Up Automatically (VERIFICATION CODES). Automatically deletes 2FA codes.

**Comment by xhi-nico** [comment] 2024-02-16 16:12
> I'm not sure if this works in macOS, but in iOS 17.3, Settings > Passwords > Password Options > Clean Up Automatically (VERIFICATION CODES). Automatically deletes 2FA codes.

this works when using Safari and the built-in feature, not when using this extension through RayCast.

**Comment by navtoj** [comment] 2024-02-18 09:10
Duplicate of #9838

**Comment by navtoj** [comment] 2024-02-18 09:10
@raycastbot close this issue

**Closed** 2024-02-18 09:10 UTC
Labels: feature request, extension, extension: imessage-2fa
