### ISSUE TITLE
[Coffee] decaf does not cancel three pots menu bar being caffeinated

### ISSUE THREAD

**Issue by bigplayer-ai** [raycast/extensions#14098] opened 2024-08-20 06:54 UTC
### Extension

https://www.raycast.com/mooxl/coffee

### Raycast Version

1.81.2

### macOS Version

17.6.1

### Description

![image](https://github.com/user-attachments/assets/a0aaefbb-07f1-4789-9d6d-957c5fd19b08)

### Steps To Reproduce

1) caffeinate
2) decaf while locked (or idk what is the trigger)
3) a lot of caffeination sessions...
4) decaf does not cancel all caffeination session, and the menu does not reflect that

**Comment by bigplayer-ai** [comment] 2024-08-20 13:29
I believe the problem is that menubar is not being updated correctly, how can I check if my MacBook is caffeinated using a more reliable way other than gum? maybe using terminal?
<img width="509" alt="image" src="https://github.com/user-attachments/assets/7a905889-d03b-4c95-a4a1-22ce29a183bd">
![Screenshot 2024-08-20 at 16 27 36](https://github.com/user-attachments/assets/3208547f-0c19-4f54-92d8-7d14a277d3ad)

**Comment by bnew10** [comment] 2024-08-23 00:05
I've also been experiencing the multiple filled coffee pots in the menu bar issue. 

When I have "Hide the icon" checked, it always happens following a "Caffeinate" then a "Decaffeinate" (which doesn't remove the filled coffee pot), and then with one more subsequent "Caffeinate" it will then add an additional filled coffee pot to the menu bar. When I don't have "Hide the icon" checked, the menu bar coffee pot behaves as expected: filled after a "Caffeinate", and then changes to an empty coffee pot after a "Decaffeinate".

@bigplayer-ai You can check whether your mac is caffeinated by running `pgrep caffeinate` from the command line. If it returns with a number (its PID) then caffeinate is running. However, from what I've been able to dig into it doesn't seem like it's failing at stopping the builtin macos caffeinate command that gets run, it's just an issue with how the macos menu bar extras section is getting updated.

**Comment by baruchiro** [comment] 2024-08-25 05:15
With GitHub plugin I'm facing the same problem:

![image](https://github.com/user-attachments/assets/7e2cdf56-cf0b-48f2-b4a9-d484c2b99dab)

<details>
  <summary>Details from Slack</summary>
  
It suddenly happened, I re-login to Github, restart but nothing changed.
I'm starting with one logo for my unread notifications.
Usually, after I read all the notifications from the Github interface, and open it later on, it disappears immediately after closing it. Because there are not unread notifications anymore. This is the expected behavior.
Now, as you can see, sometime during the day I had 4 unread notifications. I read them, from the extension or from Github, and the extension keeps appearing.
The next time it re-fetched, and found there were 3 unread notifications, so it recreated itself instead of updating the existing.
Note that the numbers are different, but the menu bar of each of the logos shows exactly the same content (the content is the content from the last update, for now, it contains one specific unread notification (although I already read it).
</details>

**Comment by pernielsentikaer** [comment] 2024-08-29 07:35
Could you check if this happen with the latest version of Raycast

**Comment by bigplayer-ai** [comment] 2024-08-29 17:37
> Could you check if this happen with the latest version of Raycast 

It is still the same problem only when hide menu bar icon is enabled as mentioned by others...

![Screenshot 2024-08-29 at 20 37 10](https://github.com/user-attachments/assets/96a42f5f-eab0-4033-8929-fdf42c15f263)

<img width="59" alt="image" src="https://github.com/user-attachments/assets/844ccd04-5c6c-46c5-b89e-341f65341d77">

**Comment by pernielsentikaer** [comment] 2024-09-05 22:38
This should be fixed with today's release. Can you check again?

**Comment by bnew10** [comment] 2024-09-05 22:57
Looks fixed on my end :)

**Comment by baruchiro** [comment] 2024-09-06 14:47
> With GitHub plugin I'm facing the same problem:
> 
> ![image](https://github.com/user-attachments/assets/7e2cdf56-cf0b-48f2-b4a9-d484c2b99dab)
> 
> <details>
>   <summary>Details from Slack</summary>
>   
> It suddenly happened, I re-login to Github, restart but nothing changed.
> I'm starting with one logo for my unread notifications.
> Usually, after I read all the notifications from the Github interface, and open it later on, it disappears immediately after closing it. Because there are not unread notifications anymore. This is the expected behavior.
> Now, as you can see, sometime during the day I had 4 unread notifications. I read them, from the extension or from Github, and the extension keeps appearing.
> The next time it re-fetched, and found there were 3 unread notifications, so it recreated itself instead of updating the existing.
> Note that the numbers are different, but the menu bar of each of the logos shows exactly the same content (the content is the content from the last update, for now, it contains one specific unread notification (although I already read it).
> </details>


Fixed for me too

**Closed** 2024-11-05 15:39 UTC
Labels: bug, extension, status: stalled, extension: coffee
