### ISSUE TITLE
[1Password] Exclude Vaults

### ISSUE THREAD

**Issue by dagfinnhagen** [raycast/extensions#11515] opened 2024-03-27 09:16 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Hi, would it be possible to include/exclude the vaults that should show up in the search? Now it searches all my 6 vaults, and they are both private and work vaults so it would be super to be able to choose which vaults it should search.

### Who will benefit from this feature?

All using multiple vaults.

### Anything else?

Adding snapshots from how the Alfred workflow solves this

![1](https://github.com/raycast/extensions/assets/165145901/d3a01642-140e-4aac-b229-b7574fe87ca9)
![2](https://github.com/raycast/extensions/assets/165145901/c2ccd859-9d82-4892-b788-32ef547ab861)

**Comment by Luk4h** [comment] 2024-04-09 12:33
duplicate of #4744 
@raycastbot close this issue

**Closed** 2024-04-09 12:33 UTC
Labels: feature request, extension, extension: 1password
