### ISSUE TITLE
[Spotify Beta]...

### ISSUE THREAD

**Issue by MatteoRicchiuto** [raycast/extensions#6048] opened 2023-04-19 21:08 UTC
### Extension

https://raycast.com/mattisssa/spotify-beta

#### Error:
```
Error: Server error.
    at Uo (/Users/matteo/.config/raycast/extensions/56a2815e-83a0-44c6-8f3c-04ef778f3298/yourLibrary.js:47:19760)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
```

**Comment by andreaselia** [comment] 2023-04-19 21:41
@MatteoRicchiuto any chance you could provide more details as to what the issue is here? How it occurred, how it can be reproduced, etc.

**Comment by peduarte** [comment] 2023-04-21 09:51
Closing due to lack of detail, but feel free to re-open with more info. Thanks

**Closed by peduarte** 2023-04-21 09:51 UTC
Labels: bug, extension, extension: spotify-beta
