### ISSUE TITLE
[GitHub] Cannot read properties of null (reading 'name') while searching for issues

### ISSUE THREAD

**Issue by scolestock** [raycast/extensions#6232] opened 2023-04-28 22:54 UTC
### Extension

https://www.raycast.com/raycast/github

#### Error:
```
TypeError: Cannot read properties of null (reading 'name')

uy:IssueActions.tsx:31:39
    at ray-list-item
Nn:index.js:23:20621
RA:search-issues.js:1284:5569
```

### Steps To Reproduce

When I initiate a search for github issues, I immediately get the "something went wrong" prompt.
Other functions, like "open issues", are retrieving data just fine - so it isn't a problem with permissions.

### Current Behaviour

When I initiate a search for github issues, I immediately get the "something went wrong" prompt.

### Expected Behaviour

Should allow me to specify a search string and return results.

**Comment by thomaslombart** [comment] 2023-06-27 09:47
It appears that this is a duplicate of issue #4831, so I'll mark it as such.

**Closed by thomaslombart** 2023-06-27 09:47 UTC
Labels: bug, extension, status: stalled, extension: github
