### ISSUE TITLE
Support <details> and <summary> HTML tags in markdown

### ISSUE THREAD

**Issue by EvanZhouDev** [raycast/extensions#7153] opened 2023-06-17 09:53 UTC
### Description

Using the Markdown syntax for a dropdown does not turn it into a dropdown.

### Steps To Reproduce

1. Create any form of an element in a Raycast extension that supports entering Markdown.
2. Put markdown={`<details>\n<summary>How do I dropdown?</summary>\n<br>\nThis is how you dropdown.\n</details>`} in that element.
3. The HTML will not turn into a dropdown.

### Current Behaviour

The HTML does not turn into a dropdown.

### Expected Behaviour

The HTML should turn into a dropdown, like it does in GitHub, or any other Markdown renderer.

**Comment by mathieudutour** [comment] 2023-06-19 16:10
I'll consider it a feature request as HTML is expected not to render in Raycast

**Comment by thomaslombart** [comment] 2023-09-06 14:59
It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/107, so I'll mark it as such.

**Closed by thomaslombart** 2023-09-06 14:59 UTC
Labels: api, feature request
