### ISSUE TITLE
[Jira] Find tickets without using ticket number prefixes

### ISSUE THREAD

**Issue by Mauricevb** [raycast/extensions#8572] opened 2023-09-26 08:32 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

Right now it's not possible to find Jira tickets by searching for the number. You need to type the full ticket number (with the project prefix) in order to find a story.

So `PROJ-12345` works, but `12345` doesn't. 

It would be nice if the prefix can be omitted.

### Who will benefit from this feature?

All Jira users that share ticket numbers without the prefix.

**Comment by thomaslombart** [comment] 2023-09-29 11:57
Thanks for the feature request. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by thomaslombart** [comment] 2023-10-06 08:44
Actually, it appears that this is a duplicate of issue #7951, so I'll mark it as such.

**Closed by thomaslombart** 2023-10-06 08:44 UTC
Labels: feature request, extension, extension: jira
