### ISSUE TITLE
[Spotify Player] ... fails to stay logged in. Must re-authorize multiple times a day

### ISSUE THREAD

**Issue by alivault** [raycast/extensions#11327] opened 2024-03-17 00:06 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ke (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6250)\n    at pt (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6375)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6140)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-03-17T00:01:18.558Z","data":{"function":"getApplications"}}]}: 


```

### Steps To Reproduce

1. login to spotify
2. wait
3. spotify logs out at least once per day
4. must re-authorize in order to use the extension

### Current Behaviour

logs out multiple times per day

### Expected Behaviour

should stay logged in indefinitely until I un-authorize the extension

**Comment by cupcakearmy** [comment] 2024-03-18 13:26
For me it's every 1-2 days. quite annoying, however i don't know if this is a spotify thing

**Comment by thomaslombart** [comment] 2024-03-19 13:47
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-19 13:47 UTC
Labels: bug, extension, extension: spotify-player
