### ISSUE TITLE
[Browser Bookmarks] Excludelist certain bookmark folders

### ISSUE THREAD

**Issue by ajsinger1** [raycast/extensions#13024] opened 2024-06-18 18:13 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Currently, all browser bookmarks are within the search space of this extension. It would be useful to have the ability to customize this search space and exclude certain bookmark folders.

### Who will benefit from this feature?

At least myself

**Comment by thomaslombart** [comment] 2024-06-19 07:51
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/11799, so I'll mark it as such.

**Closed by thomaslombart** 2024-06-19 07:51 UTC
Labels: feature request, extension, extension: browser-bookmarks
