### ISSUE TITLE
[Todoist] Error: Worker terminated due to reaching memory limit: JS heap out of memory

### ISSUE THREAD

**Issue by Vractos** [raycast/extensions#13491] opened 2024-07-15 15:09 UTC
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.78.1

### macOS Version

15.0

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. With Todoist extension and API keys set up
2. Enable menu bar tasks
3. Get the error 

### Current Behaviour

The tasks are not appearing.
![image](https://github.com/user-attachments/assets/92b640bd-b723-4f2b-9cc5-a54e7bcf01ae)

### Expected Behaviour

The tasks must show up.
![image](https://github.com/user-attachments/assets/03bddd31-90b3-4742-88f8-4576c0962bfb)

**Comment by jfkisafk** [comment] 2024-07-15 18:37
Similar to this https://github.com/raycast/extensions/issues/10127 and might have been happening due to large number of tasks getting loaded.

**Comment by thomaslombart** [comment] 2024-07-16 07:03
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10127, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-16 07:03 UTC
Labels: bug, extension, extension: todoist
