### ISSUE TITLE
[Spotify Player] Menu player shows an error icon

### ISSUE THREAD

**Issue by jhon-andrew** [raycast/extensions#7620] opened 2023-07-24 02:23 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Run Error: Command terminated, code: 2 (Unhandled Extension Rejection)


```

### Steps To Reproduce

1. Re-installed Spotify Player.
2. Enabled menu bar.
3. Signed in.
4. It shows an "error icon" and asks to login when clicked.
5. After logging in, the same icon appears.

**Comment by iurigustavo** [comment] 2023-08-18 19:02
Same here

**Comment by erics118** [comment] 2023-10-15 21:12
Duplicate of #7511

**Comment by thomaslombart** [comment] 2023-11-03 13:19
Closing it in favor of https://github.com/raycast/extensions/issues/7511.

**Closed by thomaslombart** 2023-11-03 13:19 UTC
Labels: bug, extension, extension: spotify-player
