### ISSUE TITLE
[Shortcuts Search] Does not work at all

### ISSUE THREAD

**Issue by nukesean** [raycast/extensions#9558] opened 2023-12-06 00:42 UTC
### Extension

https://www.raycast.com/solomkinmv/shortcuts-search

### Description

Every time I try to use either "List All Shortcuts" or "List Current Shortcuts," I get the following error:

![shortcuts-search 2023-12-05 at 19 38 35](https://github.com/raycast/extensions/assets/69487134/7a72bb1d-a97a-41f3-ae2f-2e9b155f60a1)

### Steps To Reproduce

1. Use either the "List All Shortcuts" or "List Current Shortcuts" command
2. See error

**Comment by solomkinmv** [comment] 2023-12-06 00:52
I can confirm this. Looks like I didn't notice it because my local version diverged from public one. Will prepare fix for this shortly.

**Comment by solomkinmv** [comment] 2023-12-06 01:00
Removed shortcut that's not supported by this version of the extension. Now it should be fine. I'll prepare next revision to address the issue.

**Comment by pernielsentikaer** [comment] 2023-12-06 06:32
This is now merged, please use `Check For Extension Updates` and verify

**Closed** 2024-02-04 06:44 UTC
Labels: bug, extension, status: stalled, extension: shortcuts-search
