### ISSUE TITLE
[Jira] I am unable to create a JIRA issue

### ISSUE THREAD

**Issue by jenningsb2** [raycast/extensions#9199] opened 2023-11-10 18:40 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:405:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```

### Steps To Reproduce

I am using the standard `Create Issue` command. The issue creation form loads, then crashes after a few seconds. 

### Current Behaviour

https://github.com/raycast/extensions/assets/29644050/74581fa1-5c47-471b-b840-8687e3dff283

**Comment by thomaslombart** [comment] 2023-11-13 02:16
Thanks for flagging this issue. Would you like to work on it? I can provide some guidance on how to contribute to this extension so that you can open a pull request. You can contact me here or in the [Slack community](http://raycastcommunity.slack.com/) if you need further help.

Note that opening up a PR and having it merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by literallyjustroy** [comment] 2023-11-18 23:36
Same thing here. I opened [an issue](https://github.com/raycast/extensions/issues/8620#issuecomment-1765884916), but then later I was unable to reproduce it. It is now back.

**Comment by literallyjustroy** [comment] 2023-11-19 23:10
Looks like the problem for me is that my organizations issue metadata is absolutely MASSIVE (242,531 lines of formatted JSON).

**Comment by literallyjustroy** [comment] 2023-11-20 02:10
@jenningsb2 Can you update your Jira extension and see if this issue is resolved?

**Comment by jenningsb2** [comment] 2023-11-20 16:49
It works as expected now! Thanks for fixing this @literallyjustroy !!

**Closed** 2023-11-20 21:13 UTC
Labels: bug, extension, extension: jira
