### ISSUE TITLE
[Authy] "Something Went Wrong" Error 

### ISSUE THREAD

**Issue by slappula** [raycast/extensions#5880] opened 2023-04-11 15:08 UTC
### Extension

https://www.raycast.com/guga4ka/authy

### Description

Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Or:index.js:5:5486
    at ray-list

### Steps To Reproduce

1. Reinstalled the extension, since it was having the 'backup password wrong' error.
2. Re-entered credentials to set it up.
3. Try searching
4. Error

**Comment by guga4ka** [comment] 2023-04-11 16:02
A small improvement for this issue already has been merged, now u could use extension, but one or more OTPs will not be available. Could you pls share the name of service, that will be marked as `corrupted` i will try to setup it and debugging

**Comment by slappula** [comment] 2023-04-11 17:05
Thanks Guga! I wasn't even searching for a particular service. The error occurs when I run the extension. Small video demonstrating the issue:

https://www.screencast.com/t/CEPcZYVl2I

**Comment by guga4ka** [comment] 2023-04-12 07:18
Hm, could you pls run `Check For Extensions Updates` command to be sure u are using the latest version of extension. And check again

**Comment by PMiraLopes** [comment] 2023-04-12 11:23
Hi [guga4ka](https://github.com/guga4ka) I continue to have the same issue, I already checked for updates and the bug continues to happen

**Comment by ahoereth** [comment] 2023-04-12 16:55
Same problem. Getting the "something went wrong" right away when opening the "search token" screen as well. After re-login I get a list of tokens initially, but they all show corrupted.

**Comment by guga4ka** [comment] 2023-04-13 12:18
@ahoereth could you say a few services that marked as corrupted. will try to register and check. I think Authy changed something in their api

**Comment by ahoereth** [comment] 2023-04-13 12:25
As said, all of them, I am now also stuck in the "something went wrong" screen without ever getting a list of services.

Some I use include GitHub, microsoft, dropbox, google, aws, slack..

**Comment by ray-su** [comment] 2023-04-16 04:46
> ervices that marked as corrupted. will try to register and check. I think Authy changed something in their api

Having the same issue

**Comment by guga4ka** [comment] 2023-05-01 18:13
sorry guys, i couldn't reproduce this bug, will try more. In case some 1 can create a dummy account with this issue and share it to me, it will speed up a fix

**Comment by ray-su** [comment] 2023-05-04 03:09
I previously uninstalled this extension, and just reinstalled it again today, and....
It's working perfectly.   Not sure what was wrong before...

**Comment by ahoereth** [comment] 2023-05-04 07:35
Sadly this is not the case for me. Just tried uninstalling and installing the extension again. Not sure if there is some cache I have to clear or something similar 🤷🏻

**Comment by ray-su** [comment] 2023-05-04 15:04
> 
I had also changed my Authy password, not sure if that changed anything

**Comment by freshfey** [comment] 2023-05-10 13:18
@ahoereth do you have special characters in your backup password? That was the cause of the error for me. Changed backup password, removed extension, re-installed - works now. //cc @guga4ka

**Comment by JensVanhooydonck** [comment] 2023-05-10 13:37
> @ahoereth do you have special characters in your backup password? That was the cause of the error for me. Changed backup password, removed extension, re-installed - works now. //cc @guga4ka

That doesn't seem possible
![image](https://github.com/raycast/extensions/assets/5812950/521d5b37-e766-45d9-9053-9e9f74a39d7f)

**Comment by freshfey** [comment] 2023-05-10 14:20
> > @ahoereth do you have special characters in your backup password? That was the cause of the error for me. Changed backup password, removed extension, re-installed - works now. //cc @guga4ka
> 
> That doesn't seem possible ![image](https://user-images.githubusercontent.com/5812950/237407950-521d5b37-e766-45d9-9053-9e9f74a39d7f.png)

Weird, just did it on Mac, and didn't get this view or the request to add a special character 🤷‍♂️

**Comment by AboodeDaBOSS** [comment] 2023-06-09 11:52
i just got the smae problem couple of hours ago I don't know what to do

**Comment by guga4ka** [comment] 2023-06-09 12:02
@AboodeDaBOSS could you pls try to
1.  change authy id in extension setting to any random number
<img width="1112" alt="image" src="https://github.com/raycast/extensions/assets/13866979/a858f0c6-c697-4345-89a5-4060e7736b66">

2. run a search otp command (it will force a cache to be cleared)
3. return to settings and revert authy id to your real id 
4. run search otp command again (it should start onboarding process from the screech)

**Comment by slappula** [comment] 2023-06-09 13:49
I just tried this and now it shows a different error ("services not found"):

![image](https://github.com/raycast/extensions/assets/409165/9daf59e0-b73c-4259-bc11-bc42d7157894)

**Comment by AboodeDaBOSS** [comment] 2023-06-09 20:53
I tried it it didnt work for me too also no I haven't changed anything from my side

**Comment by AboodeDaBOSS** [comment] 2023-06-22 11:24
so guys any update? can anyone please help 
Error: Invalid base32 characters

uu:OtpListItem.tsx:72:38
fu:search-otp.js:42:4668
Ir:index.js:6:5510
    at ray-list
    
    
<img width="748" alt="image" src="https://github.com/raycast/extensions/assets/68856095/2fd090e8-3514-46ac-89d0-d0206c5f140c">

**Comment by guga4ka** [comment] 2023-06-22 16:05
finally, folks could you try to clear local store and cache in this window 

<img width="862" alt="image" src="https://github.com/raycast/extensions/assets/13866979/f6f96507-b2ed-4f34-a294-2990f67793e2">

in case error still present i would say, something wrong with backup password

**Comment by guga4ka** [comment] 2023-06-22 16:08
to be clear it's not a solution and i should better handle errors, but at the moment i have no time to manage it

**Comment by devCharles** [comment] 2023-06-22 18:00
changing my password and reinstalling worked for me this time 👍🏼

**Comment by AboodeDaBOSS** [comment] 2023-06-22 23:33
Okay sure no problem take your time

Thanks


Abdulrahman Mashnouq
Student | CUD | FEAST-Cybersecurity
M:
+971585668262<tel:+971585668262>
P:
+966530016464<tel:+966530016464>
S:
***@***.******@***.***?chat>
E:
***@***.******@***.***>
A:
UAE-Dubai
linktr.ee/b00d<https://mysig.io/eOrMVrro>

On 22 Jun 2023, at 7:08 PM, guga4ka ***@***.***> wrote:

﻿

to be clear it's not a solution and i should better handle errors, but at the moment i have no time to manage it

**Comment by sandrofsousa** [comment] 2023-07-07 09:07
I can confirm that changing the password to numbers and letters only fixed the problem on my side.

**Closed** 2023-09-05 10:03 UTC
Labels: bug, extension, status: stalled, extension: authy
