### ISSUE TITLE
[YouTube Downloader] ...

### ISSUE THREAD

**Issue by patricktrack** [raycast/extensions#11923] opened 2024-04-21 17:52 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

keep getting encoding errors

### Steps To Reproduce

1. paste video link
2. command + enter to download
3. video downloads
4. hit encoding error
![Screenshot 2024-04-21 at 1 51 50 PM](https://github.com/raycast/extensions/assets/5630628/a4a82e21-55d6-414d-ac76-07e36937657d)

**Comment by vimtor** [comment] 2024-04-28 09:59
Hi @patricktrack, could you please follow the instructions here https://github.com/raycast/extensions/issues/11822#issuecomment-2064183311?

The issue is related to the new version of ﻿ffmpeg. Until this is resolved, you should install version 6 as outlined in the [extension instructions](https://www.raycast.com/vimtor/youtube-downloader#readme).

**Comment by vimtor** [comment] 2024-06-21 17:52
@raycastbot close this issue

**Closed** 2024-06-21 17:52 UTC
Labels: bug, extension, status: stalled, extension: youtube-downloader
