### ISSUE TITLE
[Extension Bug] Safari Show Tabs - Something Went Wrong

### ISSUE THREAD

**Issue by kraiovsky** [raycast/extensions#520] opened 2021-12-12 14:23 UTC
# Extension – [Safari](https://github.com/raycast/extensions/tree/main/extensions/safari)
Author: @loris 

## Description
I have installed extension and granted full access as needed. When prompting Show Tabs (either through hotkey or picking from the list), it errors. I have several tabs open in Safari. On contrary, Show Reading list works well.

See error below:

```
TypeError: Invalid URL

eh:cloud-tabs.js:71:613

---
68:       const safari = Application("Safari");
69:       safari.searchTheWeb({ for: "${i}" });
70:       safari.activate();
71:   `),q1=i=>$i.default.truncate(i,{length:75}),M1=i=>{let{tab:c}=i;return c.is_local?_jsx(yn.ActionPanel.Item,{title:"Open in Browser",icon:yn.Icon.Globe,onAction:async()=>{await P1(c),await(0,yn.closeMainWindow)({clearRootSearch:!0})}}):_jsx(yn.OpenInBrowserAction,{url:c.url})},D1=i=>_jsx(yn.CopyToClipboardAction,{content:i.tab.url,title:"Copy URL"}),F1=i=>{let{tab:c,refreshTabs:d}=i;return c.is_local?_jsx(yn.ActionPanel.Item,{title:"Close Tab",icon:yn.Icon.XmarkCircle,shortcut:{modifiers:["ctrl"],key:"x"},onAction:async()=>{await C1(c),d()}}):_jsx(nt.Fragment,null)};function eh(){let[i,c]=(0,nt.useState)(!1),[d,_]=(0,nt.useState)(),[x,f]=(0,nt.useState)(""),P=(0,nt.useCallback)(async()=>{try{let[q,K]=await Promise.all([R1(),L1()]),B={uuid:"local",name:`${nh} \u2605`,tabs:q},un=$i.default.transform($i.default.groupBy(K,"device_uuid"),(on,$,xn)=>{on.push({uuid:xn,name:$[0].device_name,tabs:$})},[]);_([B,...un])}catch(q){if(q instanceof Error&&q.message.includes("operation not permitted"))return c(!0);throw q}},[]);return(0,nt.useEffect)(()=>{P()},[P]),i?_jsx(yn.Detail,{markdown:Xc}):_jsx(yn.List,{isLoading:!d,onSearchTextChange:f},$i.default.map(d,q=>{let K=Kc(q.tabs,["title","url"],x);return _jsx(yn.List.Section,{key:q.uuid,title:q.name,subtitle:Hc(K.length,"tab")},K.map(B=>{let un=kc(B.url),on=Gc(un);return _jsx(yn.List.Item,{key:B.uuid,title:q1(B.title),accessoryTitle:on,icon:$c(on),actions:_jsx(yn.ActionPanel,null,_jsx(M1,{tab:B}),_jsx(D1,{tab:B}),_jsx(F1,{tab:B,refreshTabs:P}))})}),x!==""&&q.uuid==="local"&&_jsx(yn.List.Item,{key:"fallback-search",title:`Search for "${x}"`,icon:yn.Icon.MagnifyingGlass,actions:_jsx(yn.ActionPanel,null,_jsx(yn.ActionPanel.Item,{title:"Search in Browser",icon:yn.Icon.Globe,onAction:async()=>{await O1(x),await(0,yn.closeMainWindow)({clearRootSearch:!0})}}))}))}))}0&&(module.exports={});
72: /**
73:  * @license
74:  * Lodash <https://lodash.com/>
---

    at ray-navigation-stack
nm:index.js:24:10558
al:index.js:24:10663
Is:index.js:24:9779
QO:index.js:24:8740
    at ray-root
Ef:index.js:24:10083
```

### Raycast version
Version: 1.26.2

**Comment by loris** [comment] 2021-12-12 16:20
Hi @kraiovsky thanks for the report, this is a duplicate of https://github.com/raycast/extensions/issues/505 and it is already fixed, PR is waiting to be reviewed/deployed: https://github.com/raycast/extensions/pull/514

**Comment by kraiovsky** [comment] 2021-12-12 16:23
@loris FWIW, #505 mentions issue with empty tabs, I experience it with several open tabs.

**Comment by loris** [comment] 2021-12-12 16:42
Yes, but according to the error you get (Invalid URL), one of your tabs must have an invalid URL, like local files or empty URL.
The PR fix will catch the error gracefully

**Comment by loris** [comment] 2021-12-12 17:08
@kraiovsky by the way, would be awesome if you could checkout the PR and verify on your setup that it fixes the issue you have

**Closed** 2021-12-13 09:34 UTC
Labels: bug, extension, status: Issue's PR is on the review

**Comment by kraiovsky** [comment] 2021-12-16 09:29
sorry I was late to test the PR but I see you merged it now and I can confirm it works for me, thanks!
