### ISSUE TITLE
[Obsidian] Typing fast will cause certain character removed

### ISSUE THREAD

**Issue by jzhang-brex** [raycast/extensions#3622] opened 2022-11-22 20:44 UTC
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/9e427b6da0e2afbc24ec520d9c31c9bdb4da3e8e/extensions/obsidian/)
Author: @marcjulianschwarz

## Description

See https://share.cleanshot.com/ZiZPuD. In this screencast, I tried to type "personal" twice. I typed it very slow the first time and it worked. However, if I typed it in normal speed, certain characters are swallowed. 

## Steps To Reproduce

1. Enter Obsidian's search note
2. Type anything fast

### Raycast version
Version: 1.43.2

**Comment by marcjulianschwarz** [comment] 2022-11-22 21:23
Hi @jzhang-brex,

thanks for reporting. This issue seems to be on Raycasts side. Their API team is currently working on a fix.

**Comment by jzhang-brex** [comment] 2022-11-23 06:37
Ty!

**Comment by pernielsentikaer** [comment] 2022-11-23 18:23
Could you give it a spin with 1.44.o that we just released @jzhang-brex - it might be fixed 😊

**Comment by marcjulianschwarz** [comment] 2022-11-23 21:55
Tried 1.44.0 locally and the issue is still there for me. 

Also made some changes as the dropdown menu prevented the search from functioning correctly with the new version. Will open a PR soon.

**Comment by pernielsentikaer** [comment] 2022-11-29 21:56
@marcjulianschwarz do you need to have a lot of entries in order to reproduce this? Maybe I'm doing something wrong, can you share a "repro steps for dummies" for me 😊

**Comment by marcjulianschwarz** [comment] 2022-11-30 08:56
@pernielsentikaer I was able reproduce it with only one entry.
But while playing around with the issue I noticed something strange.
- Type some text really fast (for example writing the word "Test" 10 times) 
- then delete the written text with cmd+a and backspace
- then write slowly (tested with about 40 word per minute)
- See how characters are being overridden and removed

Here I followed the steps from above:
https://user-images.githubusercontent.com/67844154/204751427-b9698631-6499-4028-b6a5-194bd7be48b6.mov

**Comment by pernielsentikaer** [comment] 2022-11-30 09:14
Not sure why I can't reproduce this, but I just checked, the "fix" is first released with the next release 1.45.0, can we await for that to confirm?

**Comment by marcjulianschwarz** [comment] 2022-11-30 09:16
Sure. As the main functionality of the extension is still working I think it is not a problem to wait for the release.

**Comment by jzhang-brex** [comment] 2022-12-03 15:10
I confirmed the issue still existed for 1.44. I can test again in 1.45.0. When will it release?

**Comment by pernielsentikaer** [comment] 2022-12-06 08:58
I can't give you a date as it is right now - but it's released this year 😊

**Comment by mathieudutour** [comment] 2022-12-15 15:03
Should be fixed in 1.45!

**Closed by mathieudutour** 2022-12-15 15:03 UTC
Labels: bug, extension, status: fixed in next release, status: blocked by API
