### ISSUE TITLE
[Bitwarden Vault] Extension fails to load vault items

### ISSUE THREAD

**Issue by rpoenaru** [raycast/extensions#10977] opened 2024-02-27 07:37 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Using version `1.68.1` for Raycast together with the Bitwarden extension fails to provide the vault items. As such, copying the passwords to clipboard is unavailable.

#### Error:
```
Error: Command failed with Unknown system error -86: /Users/basavyr/Library/Application Support/com.raycast.macos/extensions/5fdb86d3-dfcc-45a7-8969-8113b51434ab/bw-2023.10.0 lock
spawn Unknown system error -86

ChildProcess.spawn:child_process:421:11
Object.spawn:node:child_process:761:9
e0:search.js:48:4352
```

### Steps To Reproduce

1. Open _Raycast_
2. Open _Search Vault_ (Bitwarden extension)

### Current Behaviour

Getting this error message:

_Something went wrong
You can try reloading, or report the error to the extension developer, by
copying the log from the Action Panel_

### Expected Behaviour

Get the list of vault items and be able to select any password into clipboard.

**Comment by Geezus42** [comment] 2024-02-27 14:07
Ditto, it's like it's failing to connect to the CLI. For instance, even telling it to logout of the vault fails. The problem only started this morning. I have not recently updated the CLI, and the plugin appears to install it's own version anyway.

**Comment by Geezus42** [comment] 2024-02-27 14:16
related: https://github.com/raycast/extensions/issues/10975

**Comment by Geezus42** [comment] 2024-02-27 14:21
Nevermind, I just tried pointing it to `/opt/homebrew/bin/bw` anyway, and it's working even better than before.

**Comment by jomifepe** [comment] 2024-02-27 15:34
Hey, sorry for the inconvenience, we've been transitioning to downloading the CLI, and it's difficult to predict to test it in different environments.

I'm currently trying to fix it 🙂

**Comment by cupcakearmy** [comment] 2024-03-04 11:01
Seems like it works for me now, was broken before. Thanks!

**Comment by Geezus42** [comment] 2024-03-04 14:30
Confirmed, it's working without pointing to the local binary now.

**Comment by jomifepe** [comment] 2024-03-13 17:04
@raycastbot close this issue

**Closed** 2024-03-13 17:04 UTC
Labels: bug, extension, extension: bitwarden
