### ISSUE TITLE
[App Bug] There is a shortcut to line breaks in the list search box

### ISSUE THREAD

**Issue by kkange** [raycast/extensions#414] opened 2021-11-23 15:48 UTC
Raycast version: 1.25.6

## Description

There is a shortcut to line breaks in the list search box

## Steps To Reproduce

1.  ctrl + opt + shift + enter

## The current behavior
https://user-images.githubusercontent.com/14085373/143060945-ed043e4c-ec8f-4024-94f4-7ad47bf05dcc.mov

https://user-images.githubusercontent.com/14085373/143062328-eb96e445-b910-4678-87b5-1f30999f337d.mov

## The expected behavior

Nothing at all.

**Comment by mattisssa** [comment] 2021-11-23 19:08
Wow, thank you for the report! Actually, it'd not related to the API since the bug can be reproduced in the root search as well.
We will take a look at that 👍

**Comment by fe9lix** [comment] 2021-11-30 06:04
Closing this issue since it's not an API-specific bug. @kkange Could you report this through the in-app feedback feature? (You can refer to this issue...)

**Closed by fe9lix** 2021-11-30 06:04 UTC
Labels: bug, app

**Comment by kkange** [comment] 2021-11-30 08:06
> Closing this issue since it's not an API-specific bug. @kkange Could you report this through the in-app feedback feature? (You can refer to this issue...)

Yes, the app sent me feedback.
