### ISSUE TITLE
[Spotify Player] Spotify displayed error 

### ISSUE THREAD

**Issue by kennygokh** [raycast/extensions#10052] opened 2024-01-09 01:32 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)\n    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-01-09T01:27:02.505Z","data":{"function":"getApplications"}}]}: 


```
Spotify extension error keep showing despite granted access at Spotify to Raycast

### Steps To Reproduce

1. Once Raycast launched
2. Error display
3. Access granted at Spotify
4. Error continue to display

### Current Behaviour

Spotify player extension giving error despite access has been granted

### Expected Behaviour

No error should display once access is granted

**Comment by peduarte** [comment] 2024-01-30 14:51
Hey there, can you still reproduce this? We pushed some fixes in the latest release.

**Comment by thomaslombart** [comment] 2024-03-19 13:46
It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-19 13:46 UTC
Labels: bug, extension, extension: spotify-player
