### ISSUE TITLE
[Jira] Can't open issues in browser (Mac -50 error; "Cannot open application")

### ISSUE THREAD

**Issue by rkrueger11** [raycast/extensions#12212] opened 2024-05-06 18:39 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

When finding an issue using the JIRA extension, if I try to open it in the browser, I get a MacOS error that "Cannot open application". 

### Steps To Reproduce

1. Type Jira search
2. Search for any issue
3. Command Enter to open in browser

### Current Behaviour

MacOS Error: "Cannot open application"

![Screenshot 2024-05-06T11 39 32@2x](https://github.com/raycast/extensions/assets/8338328/698e610d-089b-4a14-93a6-6bf00ecaedf2)

### Expected Behaviour

Browser to open to issue

**Comment by thomaslombart** [comment] 2024-05-14 10:19
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/12119#issuecomment-2088622400, so I'll mark it as such.

**Closed by thomaslombart** 2024-05-14 10:19 UTC
Labels: bug, extension, extension: jira
