### ISSUE TITLE
[Spotify Player] ... Access token returning

### ISSUE THREAD

**Issue by einargudnig** [raycast/extensions#15174] opened 2024-10-31 09:26 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.84.8

### macOS Version

15.0.1

### Description

I get the expired access token every other day.
This was not the case, now it is in this 'broken' state for some time an than I can get a new access token by authenticating and allowing raycast access to Spotify, which should create the access token.
It's annoying, but it could be survived if I could just "refresh" the access token.

Error from raycast
```
Error: The access token expired

U0:getPlaybackState.ts:15:10

---
12:   } catch (err) {
13:     const error = getErrorMessage(err);
14:     console.log("getPlaybackState.ts Error:", error);
15:     throw new Error(error);
16:   }
17: }
18: 
---

async K0:togglePlayPause.js:60:144
```

I'll take a look at it later, see if there is something that I can do to help

### Steps To Reproduce

Open the extensions in Raycast and select any command, all of them return this error since the access token is expired

**Comment by thomaslombart** [comment] 2024-10-31 09:32
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-10-31 09:32 UTC
Labels: bug, extension, extension: spotify-player
