### ISSUE TITLE
[Browser Bookmarks] Crashes when searching using Arc

### ISSUE THREAD

**Issue by kvenn** [raycast/extensions#13843] opened 2024-08-02 18:03 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.80.0

### macOS Version

14.5

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Have Arc set as default browser
2. Have a ton of bookmarks?
3. Search browser bookmarks (with no text entered)

### Current Behaviour

The bookmarks show for less than a second and then it goes to the "something went wrong" page

### Expected Behaviour

The bookmarks show and are then searchable

**Comment by thomaslombart** [comment] 2024-08-05 08:49
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-08-05 08:49 UTC
Labels: bug, extension, extension: browser-bookmarks
