### ISSUE TITLE
[Spotify Player] ... Can we get "scrolling" option in menubar? 

### ISSUE THREAD

**Issue by bcometa** [raycast/extensions#13050] opened 2024-06-19 21:37 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The Spotify Menu Bar Player is awesome. I just wish it would scroll to show entire song title/artist if the length exceeds max text length. 

### Who will benefit from this feature?

Everyone!

**Comment by erics118** [comment] 2024-06-19 21:59
See https://github.com/raycast/extensions/issues/7450

**Comment by bcometa** [comment] 2024-06-19 22:00
Didn't see that -- thanks Erics118!

**Comment by thomaslombart** [comment] 2024-06-20 07:41
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/11292, so I'll mark it as such.

**Closed by thomaslombart** 2024-06-20 07:41 UTC
Labels: feature request, extension, extension: spotify-player
