### ISSUE TITLE
[Jira] Save selected project in subsequent queries

### ISSUE THREAD

**Issue by nurgasemetey** [raycast/extensions#5988] opened 2023-04-17 09:04 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

Hello team

I remember that previous version was using previously selected project. In new version I constantly select project to search my teams' issues.

![image](https://user-images.githubusercontent.com/4669437/232436990-d78b470c-0487-4257-bc47-ee71eeb2df90.png)

### Who will benefit from this feature?

Users whose organizations are big so they have different projects. I am only using one project so I don't want to select project each time.

**Comment by thomaslombart** [comment] 2023-04-18 06:59
I've shipped a fix that may close the issue @nurgasemetey. Could you try it again and let me know if it works for you?

**Comment by nurgasemetey** [comment] 2023-04-19 06:43
Hello

Thanks for your fix but I am maybe confused with how "Active Sprints" is working. 

So I selected my project
![image](https://user-images.githubusercontent.com/4669437/232988154-f072a5d3-0a06-4c50-9d6e-64897be6d9da.png)

Then I closed extension is closed(not quit) and executed "Active Sprints" again.

![image](https://user-images.githubusercontent.com/4669437/232988457-51dd3e8f-a8f6-47b0-a6c2-01a56e953e85.png)

It again shows first element from project list.

Maybe it is like how it works and I was confused that selected project will be persisted once it selected.

**Comment by thomaslombart** [comment] 2023-04-19 06:52
Are you searching for the project in the dropdown or is it already there when opening the dropdown?

**Comment by zach-cao** [comment] 2023-04-26 01:53
@thomaslombart I'm having the same issues.

> Are you searching for the project in the dropdown or is it already there when opening the dropdown?

I have a long list of projects, and I have to search it in the dropdown. Maybe the root cause is the same with this issue: #5768

**Comment by thomaslombart** [comment] 2023-04-26 07:22
Indeed, it's exactly the same root cause.

**Comment by Justverbickas** [comment] 2023-05-11 07:38
Hey, my organization also has many projects, but I only work on three, I would love to see the most used ones on top or to have favorites. Because right the workflow looks like  "active sprint" > command+p > type a project name > enter. 

I was thinking maybe somehow I could build deep links to my favorite projects' active sprints, but I couldn't figure it out how to do it.

**Comment by IzakMaraisTAL** [comment] 2023-07-04 06:03
Can others confirm that this is fixed for them too? 

It had not been working for months.  But when I tested it now (after getting this `stalled` notification) it looks like it is fixed.

**Comment by thomaslombart** [comment] 2023-07-04 06:39
A fix has been shipped yesterday thanks to @jesperorb (https://github.com/raycast/extensions/pull/7307).

**Closed by thomaslombart** 2023-07-04 06:39 UTC
Labels: feature request, extension, extension: jira

**Comment by IzakMaraisTAL** [comment] 2023-07-04 06:42
Thank you very much! Thanks @jesperorb !

**Comment by Justverbickas** [comment] 2023-07-04 08:47
Works for me as well, lovely ❤️ thank you (;
