### ISSUE TITLE
[TidyRead - Streamline Your Daily Reading] Digest generation stopped to work completely

### ISSUE THREAD

**Issue by alexandertsukanov** [raycast/extensions#10335] opened 2024-01-25 11:08 UTC
### Extension

https://www.raycast.com/jaredliu233/tidyread---streamline-your-daily-reading

### Description

After https://github.com/raycast/extensions/issues/10331 was merged TinyRead stuck on Digest Generation.

### Steps To Reproduce

1. Go to "Daily Read" command
2. Click "Daily Digest Generation"
3. See infinity fetching.

<img width="738" alt="CleanShot 2024-01-25 at 13 07 43@2x" src="https://github.com/raycast/extensions/assets/17796771/58c29ab2-18e5-47cf-affd-f83a44d8fc49">

### Current Behaviour

Daily Digest fetched forever.

### Expected Behaviour

Daily Digest generated.

**Comment by DophinL** [comment] 2024-01-25 11:29
> ### Extension
> https://www.raycast.com/jaredliu233/tidyread---streamline-your-daily-reading
> 
> ### Description
> After #10331 was merged TinyRead stuck on Digest Generation.
> 
> ### Steps To Reproduce
> 1. Go to "Daily Read" command
> 2. Click "Daily Digest Generation"
> 3. See infinity fetching.
> 
> <img alt="CleanShot 2024-01-25 at 13 07 43@2x" width="738" src="https://private-user-images.githubusercontent.com/17796771/299636867-58c29ab2-18e5-47cf-affd-f83a44d8fc49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODIzMzYsIm5iZiI6MTcwNjE4MjAzNiwicGF0aCI6Ii8xNzc5Njc3MS8yOTk2MzY4NjctNThjMjlhYjItMThlNS00N2NmLWFmZmQtZjgzYTQ0ZDhmYzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDExMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5Mzk2OGM2ZGVkZWM5NWNmMTA0NWNjNTM4NzBkMDBlMWU3YjI3YWEyY2M5YjNjMDUzNGUzNGQ5YzJjYjA3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghXjb23uTTXsD-0ElkFs9j5LbPmHpdB8dbXuD4ZK64g">
> ### Current Behaviour
> Daily Digest fetched forever.
> 
> ### Expected Behaviour
> Daily Digest generated.

Hi Alex @alexandertsukanov ,  Can you share your sources to me? refer this [doc](https://www.tidyread.info/docs/share-or-export-your-sources)

**Comment by DophinL** [comment] 2024-01-25 11:42
@alexandertsukanov 
I didn't run into a problem when I tried it. What AI Provider are you using and what model? I'm guessing it's because the default settings for the retry count and retry delay are a bit too large, to ensure that the briefs are generated correctly. You can try to reduce the value a little bit. Actually you try to keep waiting and it should eventually generate the digest.

And it's recommended to auto generate dailly digest, refer [this doc](https://www.tidyread.info/docs/automate-daily-digest), then you won't be bothered anymore.

**Comment by alexandertsukanov** [comment] 2024-01-25 12:06
here we go
```json
[
    {
        "schedule": "everyday",
        "tags": [],
        "rssLink": "https://in.relation.to/blog.atom",
        "timeSpan": "7",
        "url": "https://in.relation.to/",
        "title": "The Hibernate team blog on everything data - In Relation To",
        "favicon": "https://static.jboss.org/hibernate/images/favicon.ico"
    },
    {
        "url": "https://feeds.feedblitz.com/baeldung",
        "title": "Baeldung Blog",
        "rssLink": "https://feeds.feedblitz.com/baeldung&x=1",
        "tags": [],
        "timeSpan": "1",
        "schedule": "everyday",
        "favicon": ""
    }
]
```
here is my settings

<img width="343" alt="CleanShot 2024-01-25 at 14 05 19@2x" src="https://github.com/raycast/extensions/assets/17796771/ebfe0efb-2cec-45ae-bef1-ae3b1e48b333">
<img width="299" alt="CleanShot 2024-01-25 at 14 05 28@2x" src="https://github.com/raycast/extensions/assets/17796771/18f261bc-2f2e-4462-af00-748bd5b864c5">
<img width="313" alt="CleanShot 2024-01-25 at 14 05 41@2x" src="https://github.com/raycast/extensions/assets/17796771/8565a47b-0ed6-4db5-8c0c-c2b6d63e4a4c">

**Comment by alexandertsukanov** [comment] 2024-01-25 12:15
So finally I have it, it takes around 10 min. But still have failed items:
<img width="740" alt="CleanShot 2024-01-25 at 14 15 05@2x" src="https://github.com/raycast/extensions/assets/17796771/a3c27f06-28e1-479e-b073-8a79c9f37caa">

**Comment by DophinL** [comment] 2024-01-25 12:54
> So finally I have it, it takes around 10 min. But still have failed items: <img alt="CleanShot 2024-01-25 at 14 15 05@2x" width="740" src="https://private-user-images.githubusercontent.com/17796771/299656762-a3c27f06-28e1-479e-b073-8a79c9f37caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODYxOTMsIm5iZiI6MTcwNjE4NTg5MywicGF0aCI6Ii8xNzc5Njc3MS8yOTk2NTY3NjItYTNjMjdmMDYtMjhlMS00NzllLWIwNzMtOGE3OWM5ZjM3Y2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjhlNTU2MTM1ZGNhZjkxMmUwZmIyNWEzNGUwMTg1NDhhODQ2ZDMxY2E4NGQwZDk3MjBkMWNhMDM4YzU3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9Y4evJtU7lxQuyWwAQM93ArrqwxDfl4DfCfy_HT0OQ">

Sorry Alex @alexandertsukanov , I didn't have a feel for what's actually going on since I've changed the default configuration locally and am using Raycast AI.

Suggest you start by tweaking these parameters to the values on the image:
![CleanShot 2024-01-25 at 20 52 11@2x](https://github.com/raycast/extensions/assets/8707316/0cc2abc6-42c1-4ead-9ea1-c588bc7712ec)

I'm digging deeper now to see what the problem is, theoretically open free tier 1 supports 500 requests per minute, but in practice there are quite a few requests that keep failing

**Comment by DophinL** [comment] 2024-01-25 12:54
> So finally I have it, it takes around 10 min. But still have failed items: <img alt="CleanShot 2024-01-25 at 14 15 05@2x" width="740" src="https://private-user-images.githubusercontent.com/17796771/299656762-a3c27f06-28e1-479e-b073-8a79c9f37caa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODYxOTMsIm5iZiI6MTcwNjE4NTg5MywicGF0aCI6Ii8xNzc5Njc3MS8yOTk2NTY3NjItYTNjMjdmMDYtMjhlMS00NzllLWIwNzMtOGE3OWM5ZjM3Y2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMjhlNTU2MTM1ZGNhZjkxMmUwZmIyNWEzNGUwMTg1NDhhODQ2ZDMxY2E4NGQwZDk3MjBkMWNhMDM4YzU3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9Y4evJtU7lxQuyWwAQM93ArrqwxDfl4DfCfy_HT0OQ">

Sorry Alex @alexandertsukanov , I didn't have a feel for what's actually going on since I've changed the default configuration locally and am using Raycast AI.

Suggest you start by tweaking these parameters to the values on the image:
![CleanShot 2024-01-25 at 20 52 11@2x](https://github.com/raycast/extensions/assets/8707316/0cc2abc6-42c1-4ead-9ea1-c588bc7712ec)

I'm digging deeper now to see what the problem is, theoretically open free tier 1 supports 500 requests per minute, but in practice there are quite a few requests that keep failing

**Comment by alexandertsukanov** [comment] 2024-01-25 14:13
@DophinL so looks like I see next error on items are failed to load:
<img width="711" alt="CleanShot 2024-01-25 at 16 12 49@2x" src="https://github.com/raycast/extensions/assets/17796771/f7b3a810-fc6a-4f5b-b401-e97e026ca252">

**Comment by DophinL** [comment] 2024-01-26 07:22
> @DophinL so looks like I see next error on items are failed to load: <img alt="CleanShot 2024-01-25 at 16 12 49@2x" width="711" src="https://private-user-images.githubusercontent.com/17796771/299693906-f7b3a810-fc6a-4f5b-b401-e97e026ca252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzMzMjUsIm5iZiI6MTcwNjIzMzAyNSwicGF0aCI6Ii8xNzc5Njc3MS8yOTk2OTM5MDYtZjdiM2E4MTAtZmM2YS00ZjViLWI0MDEtZTk3ZTAyNmNhMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAxMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTViN2QyNGQ1NjAzNWE3MWNkMTgyOTgzOTgxODFiZTJkMjEwM2IxMTliYTM2ZmM0YTI5NjVmYWEzYzkwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.95HfZ85EDaBiW8zUyrJ5oyzFnMPTB4XGJzvqJVUm6f0">

oops, I've checked and there is no answer, and due to the way the plugin is currently implemented and the stability of the openai interface, some errors in the process may be unavoidable. I can't follow up on this `openai The data couldn't be read because it isn't in the correct format` issue for now!

May I ask what api model you are using and if you have set the preferred language?

**Comment by DophinL** [comment] 2024-01-26 07:25
And I changed api call from stream to normal, it seems more stable now when multi requests are concurrent

**Comment by alexandertsukanov** [comment] 2024-01-26 08:45
Well, I use next settings:

<img width="296" alt="CleanShot 2024-01-26 at 10 45 13@2x" src="https://github.com/raycast/extensions/assets/17796771/92d9a104-c083-4d51-983b-bed88f5bc89a">

**Comment by DophinL** [comment] 2024-01-26 08:50
> Well, I use next settings:
> 
> <img alt="CleanShot 2024-01-26 at 10 45 13@2x" width="296" src="https://private-user-images.githubusercontent.com/17796771/299925641-92d9a104-c083-4d51-983b-bed88f5bc89a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTkxNjgsIm5iZiI6MTcwNjI1ODg2OCwicGF0aCI6Ii8xNzc5Njc3MS8yOTk5MjU2NDEtOTJkOWExMDQtYzA4My00ZDUxLTk4M2ItYmVkODhmNWJjODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MzBiMzYxNjI0Y2FiOGRlYmRmYTdmNzYwMzA2OTI3ZDI5ZGVhYTUyN2FhZTlkOTFlZTg3MzJlNzg4Y2RjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c4pT6HcE5XUfb8kul0C0abwmSLg1z6XCvJJ2esRXNc0">
> And provider is Raycast AI.

@alexandertsukanov If you are using Raycast AI, you can try the following parameters and the model can be adjusted to raycast instruct:
```
{
    maxApiConcurrency: 5,
    retryCount: 4,
    retryDelay: 20,
  }
```

**Comment by alexandertsukanov** [comment] 2024-01-26 09:02
@DolphinL, very nice work! It works like a charm! So basically, you need to set the model according to the AI provider. Wouldn't it be the easiest way to fetch the list of models based on the provider?

**Comment by DophinL** [comment] 2024-01-26 13:39
> @dolphinl, very nice work! It works like a charm! So basically, you need to set the model according to the AI provider. Wouldn't it be the easiest way to fetch the list of models based on the provider?

Haha, thank you for the suggestion. I indeed have implemented the feature to configure based on the provider. However, this time I've hardcoded it and did not use a dynamic request approach.

**Comment by DophinL** [comment] 2024-01-27 15:04
@alexandertsukanov 

Hi Alex, the issue has been fixed and released, thanks again for your feedback. If you have any questions, please feel free to raise them!

Next, these three configuration items can be removed, as default configurations for different providers have already been provided.

**Comment by DophinL** [comment] 2024-01-27 15:05
@raycastbot close this issue

**Closed** 2024-01-27 15:05 UTC
Labels: bug, extension, extension: tidyread---streamline-your-daily-readi…
