### ISSUE TITLE
[Ollama AI] × Preferred model is not configured on LocalStorage.

### ISSUE THREAD

**Issue by jahan-paisley** [raycast/extensions#10660] opened 2024-02-09 00:22 UTC
### Extension

https://www.raycast.com/massimiliano_pasquini/raycast-ollama

### Description

While the app is open and working raycast extension shows this error and fails to accept any input

### Steps To Reproduce

Open ollama app so that http://127.0.0.1:11434/api/chat would be accessible
Open extension to start a chat.
<img width="776" alt="Screenshot 2024-02-09 at 3 50 53 AM" src="https://github.com/raycast/extensions/assets/503810/a743e9c6-2ec7-43f5-bea8-5449a6b1cdd1">

### Current Behaviour

Not accepting any input

### Expected Behaviour

Accept input and respond with the answer from ollama

**Comment by MassimilianoPasquini97** [comment] 2024-02-09 05:55
Hi @jahan-paisley, as shown by error message, an installed model need to be chose. Normally if it isn't set it would show up the form for chose the LLM Model, this abnormal behaviour could be caused by a bug introduced in a recent versions an I will further investigate for resolve it.

In the meantime you can set the model from "Actions" menu or with "CMD+M" shortcuts.

**Comment by jahan-paisley** [comment] 2024-02-11 09:03
Hi @MassimilianoPasquini97 and thanks for prompt reply, I chose the model but it kept showing me the error, I'm sure it's a minor issue, I don't know how but the error is gone after a dozen of time trying different scenarios.

**Comment by mwmcode** [comment] 2024-02-16 03:08
For me, it went away after I set `Embedding` option (set to the same `Model` option). 

![ol](https://github.com/raycast/extensions/assets/13101565/0e9a3f58-70fa-4c68-985a-08fdc5b75ede)

**Comment by BSoDium** [comment] 2024-02-27 16:49
@mwmcode I agree, the bug only occurs when the "use different Model for Embedding" option is not selected

**Comment by MassimilianoPasquini97** [comment] 2024-04-01 06:15
@raycastbot close this issue

**Closed** 2024-04-01 06:15 UTC
Labels: bug, extension, extension: raycast-ollama
