### ISSUE TITLE
[Menubar Weather] ...

### ISSUE THREAD

**Issue by peterreibel** [raycast/extensions#8656] opened 2023-10-03 13:21 UTC
### Extension

https://www.raycast.com/koinzhang/menubar-weather

### Description

On a multiple display setup, macOS dims or fades the menu bar and it's content on the display that is currently not in active use. The temperature does not fade on the inactive display where the icon of it does. I am using macOS Sonoma 14.0 in dark mode.

![CleanShot 2023-10-03 at 15 14 19](https://github.com/raycast/extensions/assets/42697505/4b18b377-611a-4789-8653-b64ee87e1767)

### Steps To Reproduce

1. Use a multi display setup.
2. Make sure both desktops show the menu bar.
3. Observe the other screen's menu bar you are _not_ currently working on.

### Current Behaviour

The temperature value is not fading like the rest of the the menu bar on the inactive display/screen/space.

### Expected Behaviour

Faded temperature value on the in active display/screen/space.

**Comment by fuksman** [comment] 2023-10-03 14:35
Duplicate of #7481

**Comment by sxn** [comment] 2023-10-23 10:47
I'll close this issue in favour of #7481

**Closed by sxn** 2023-10-23 10:47 UTC
Labels: bug, extension, extension: menubar-weather
