### ISSUE TITLE
[Obsidian] Can't locate vault if username contains "." character

### ISSUE THREAD

**Issue by lancosch** [raycast/extensions#3292] opened 2022-10-21 17:10 UTC
# Extension – [Obsidian](https://github.com/raycast/extensions/tree/main/extensions/obsidian)

Author: @marcjulian

## Description
The plugin can't locate the obsidian vault if the username contains "." character. By specifying it explicitly and not relying on "~/Library/Application Support/obsidian/obsidian.json" doesn't help.

## Steps To Reproduce

1. Create a user with "." like john.doe
2. Create obisidan vault in home directory
3. Try using the plugin

## The current behavior
"The path set in preferences doesn't exist" Error message

## The expected behavior
Normal operation

### Raycast version

Version: 1.41.1

**Comment by marcjulianschwarz** [comment] 2022-10-28 09:29
Hi @lancosch,

thank you. I will have a look at it. Added this issue to the [backlog](https://github.com/users/marcjulianschwarz/projects/1/).

**Comment by marcjulianschwarz** [comment] 2022-11-21 19:30
Commenting to prevent automatic closing.

Still trying to reproduce this issue. Does this only happen when creating the vault in the home directory or everywhere?

**Comment by lancosch** [comment] 2022-11-22 19:18
Only in my home directory. If I place the vault onto for example an external drive and the path is /Volumes/something/vault things are working. If I try to reference the vault inside my home /Users/user.name/vault it tells me invalid path when for example I try to use search.

**Comment by marcjulianschwarz** [comment] 2022-12-03 22:07
I can't reproduce this issue on my side.

I created a user called "user.name" and added a folder called "Vault". All commands worked as expected.

One more thing you could try is to see whether you allowed Raycast "Full Disk Access" in macOS settings. This is necessary to access your markdown files.

**Closed** 2022-12-25 10:02 UTC
Labels: bug, extension, status: stalled
