### ISSUE TITLE
[Bitwarden Vault] ...

### ISSUE THREAD

**Issue by Tigeredgar** [raycast/extensions#6302] opened 2023-05-03 17:42 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Keeps logging me out right after logging in.

### Steps To Reproduce

Login with master password. 
Wait 2 seconds
Logs me out and prompts for master password again

**Comment by jomifepe** [comment] 2023-05-03 23:26
Hello, thanks for reporting, I'm taking a look into the issue. In the meantime, please try to reinstall the extension.

**Comment by trm217** [comment] 2023-05-04 07:08
Experiencing the same issue currently.

**Comment by jomifepe** [comment] 2023-05-04 15:38
Can you confirm that the issue still persists are the last update?

**Comment by GumbyXGames** [comment] 2023-05-06 22:54
Upgraded to Raycast v1.50.4 and issue persits.

**Comment by trm217** [comment] 2023-05-07 22:31
Can confirm, issue persists.

**Comment by jomifepe** [comment] 2023-05-08 10:10
Please verify if the issue still persists with the latest update

**Comment by trm217** [comment] 2023-05-08 15:42
@jomifepe It's working for me now. Thank you for your effort 🙌🏻

**Comment by jomifepe** [comment] 2023-05-08 21:24
@Tigeredgar can you confirm that it's working correctly?

**Comment by GumbyXGames** [comment] 2023-05-08 22:44
Bitwarden extension seems to be working fine after installing the update. Thanks for the quick fix!

**Comment by jomifepe** [comment] 2023-05-22 13:42
I will assume that this issue is resolved, given that two people already confirmed that it's working. 

If not, be sure to comment, thanks 🙂

@raycastbot close this issue

**Closed** 2023-05-22 13:42 UTC
Labels: bug, extension, extension: bitwarden
