### ISSUE TITLE
[Browser Bookmarks]... maxObjectCount exceeded when adding Safari

### ISSUE THREAD

**Issue by makaidos42** [raycast/extensions#8651] opened 2023-10-02 22:51 UTC
### Extension

https://raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: maxObjectCount exceeded
    at Re.parseBuffer (/Users/kane.vandenbiggelaar/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:35:60380)
    at S8 (/Users/kane.vandenbiggelaar/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:40:24495)
    at /Users/kane.vandenbiggelaar/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:40:25037
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Steps To Reproduce

1. Open Browser Bookmarks extention
2. ⌘-K to Select Browsers
3. Add Safari
4. Receive the error

### Current Behaviour

When I try and select Safari as a browser to add, I get the "maxObjectCount exceeded" error.

### Expected Behaviour

I expect that Safari bookmarks can be added. This worked perfectly well in the old extension before it was deprecated. I easily have a few thousand bookmarks.

**Comment by thomaslombart** [comment] 2023-10-03 06:12
Thanks for bringing this up. It appears that this is a duplicate of issue #8640, so I'll mark it as such.

**Closed by thomaslombart** 2023-10-03 06:12 UTC
Labels: bug, extension, extension: browser-bookmarks
