### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by wilsonsemilio** [raycast/extensions#13229] opened 2024-06-29 09:03 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.77.3

### macOS Version

14.5 (23F79)

### Description

Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant","error_description":"Refresh token revoked"}

r1.refreshTokens:OAuthService.js:134:18

---
131:         if (!response.ok) {
132:             const responseText = await response.text();
133:             console.error("refresh tokens error:", responseText);
134:             throw new Error(`Error while refreshing tokens: ${response.status} (${response.statusText})\n${responseText}`);
135:         }
136:         const tokenResponse = this.tokenRefreshResponseParser(await response.json());
137:         tokenResponse.refresh_token = tokenResponse.refresh_token ?? token;
---

async r1.authorize:togglePlayPause.js:30:14121

### Steps To Reproduce

Make custom shortcuts.
Use them.

### Current Behaviour

My custom made shortcuts to control Spotify do not work all of a sudden.

**Comment by thomaslombart** [comment] 2024-07-03 08:45
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/13167, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-03 08:45 UTC
Labels: bug, extension, extension: spotify-player
