### ISSUE TITLE
[Todoist] menu bar command not working

### ISSUE THREAD

**Issue by erauner12** [raycast/extensions#6685] opened 2023-05-19 22:13 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

Cannot use menu bar tasks.

error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

Try to open Menu Bar Command

### Current Behaviour

Command Terminated

### Expected Behaviour

For it to put something on menu bar

**Comment by Ek2100** [comment] 2023-05-20 00:50
It seems like your laptop ran out of memory(ram)

**Comment by thomaslombart** [comment] 2023-05-23 07:36
Thanks for bringing this up. It appears that this is a duplicate of issue #6562, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-23 07:36 UTC
Labels: bug, extension, extension: todoist
