### ISSUE TITLE
[Slack] ...

### ISSUE THREAD

**Issue by sanatcodes** [raycast/extensions#13923] opened 2024-08-08 12:10 UTC
### Extension

https://www.raycast.com/mommertf/slack

### Raycast Version

1.80.00

### macOS Version

14.5 (23F79)

#### Error:
```
Error: Command failed with exit code 1: osascript
644:690: execution error: Not authorised to send Apple events to System Events. (-1743)

e6:run-applescript.js:38:21

---
35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     })

### Steps To Reproduce

1. Search for unread messages command on raycast
2. Click on it
3. The app crashes 
![Screenshot 2024-08-08 at 1 09 15 p m](https://github.com/user-attachments/assets/92145a01-574e-4bc0-a5e6-6fc9e0d790fe)


### Current Behaviour

Open unread messages command is not working 

### Expected Behaviour

Raycast just errors out

**Comment by Elliot67** [comment] 2024-08-08 12:20
Hi @sanatcodes ,

Looks like the same issue as #10297. Could you try the solution provided in [this comment](https://github.com/raycast/extensions/issues/10297#issuecomment-2002497007) ?

**Comment by sanatcodes** [comment] 2024-08-08 12:40
Thanks for the quick reply @Elliot67. I already had accessibility permissions on. Tried toggling them off and on again. Also restarted Raycast. Doesn't seem to resolve the issue.

**Comment by Elliot67** [comment] 2024-08-23 22:15
@sanatcodes Could you try allowing `System Events` for raycast at `System Preferences  -> Privacy  & Security -> Automation`.

Couldn't reproduce the issue on my end, I currently got the following apps allowed in there :
- `Terminal`
- `System Events`
- `System Preferences`

Restarting the computer might or might not be needed.

**Comment by thomaslombart** [comment] 2024-10-14 09:10
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.

**Closed by thomaslombart** 2024-10-14 09:10 UTC
Labels: bug, extension, status: stalled, extension: slack
