### ISSUE TITLE
[Jira] "My Filters" Selection Not Persisting

### ISSUE THREAD

**Issue by macjabeth** [raycast/extensions#8677] opened 2023-10-04 18:10 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

Hello,

I just finished transitioning from the deprecated Jira extension to the supported version, and I've noticed a small issue with the "My Filters" command.

Whenever I access it, the active filter resets, even if I had previously selected the desired filter.

It would be great if the previous functionality of retaining the filter selection could be restored. This way, users wouldn't have to search for the filter every time they want to use it.

### Steps To Reproduce

1. Select the "My Filters" command.
2. Update the filter to desired filter.
3. Exit out of Jira filter and use some other Raycast functionality (like the built-in calculator.. because math..)
4. Go back into "My Filters" command.
5. See active filter has been reset and no longer uses the desired filter you had selected previously.

### Current Behaviour

Active filter is reset on each use.

### Expected Behaviour

Active filter should persist between uses.

**Comment by thomaslombart** [comment] 2023-10-05 07:59
Thanks for bringing this up. It appears that this is a duplicate of issue #5768, so I'll mark it as such.

**Closed by thomaslombart** 2023-10-05 07:59 UTC
Labels: bug, extension, extension: jira
