### ISSUE TITLE
[Jira] Network Fails under New Authentication

### ISSUE THREAD

**Issue by macjabeth** [raycast/extensions#7335] opened 2023-06-30 15:21 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

The existing Jira extension functions correctly for me. However, after attempting the new extension and completing the authentication process, it fails to communicate through the API calls.

I am connected to a work VPN. As the Jira extension is primarily used for work, there is no need to switch to a new, incompatible version when the original one is functioning properly.

Please deprecate the new Jira extension and continue development on the old one, or somehow integrate the previous authentication method from the old Jira extension into this one. Thank you!

### Steps To Reproduce

1. Install new Jira extension.
2. Authenticate in Jira.
3. Try running any Jira command.
4. See API communication failures.

### Current Behaviour

API communication is blocked.

### Expected Behaviour

API communication would work fine.

**Comment by thomaslombart** [comment] 2023-07-03 13:03
Do you get any specific errors? I'm wondering if this issue is a duplicate of #7104 or #7085.

**Comment by macjabeth** [comment] 2023-07-05 16:47
@thomaslombart Hey Thomas, this is the flow of what happens after authenticating. Hopefully this helps:

![2023-07-05 at 11 45 35@2x](https://github.com/raycast/extensions/assets/8473052/6e8c9d73-d726-454c-a84a-04cabb5dea86)
![2023-07-05 at 11 46 02@2x](https://github.com/raycast/extensions/assets/8473052/f653d426-fcb6-4363-8762-8780ced211b1)

**Comment by macjabeth** [comment] 2023-07-05 16:49
And yes actually this seems like a duplicated issue from #7104 - I must've forgotten I created that one. Apologies for the duplicate.

**Comment by thomaslombart** [comment] 2023-07-06 08:31
Thanks for the additional details.

**Comment by neilcode** [comment] 2023-07-25 16:49
I am also using this at work with a VPN. The old version of the extension was working great. After upgrading, auth fails with this message:
![image](https://github.com/raycast/extensions/assets/7885337/47cfd783-5594-4b0c-808d-a7c1b271fe15)

Hoping this can be resolved, the JIRA extension is one of my favorite things about Raycast!

**Comment by acovaci** [comment] 2023-09-14 13:56
I am also facing the same issue under ZScaler

**Comment by mathieudutour** [comment] 2023-09-18 10:14
Could you try playing with those settings in the "Advanced" tab of the Raycast's preferences?

<img width="530" alt="image" src="https://github.com/raycast/extensions/assets/3254314/6b539639-460c-4e26-8824-8cedddb007fa">

**Comment by macjabeth** [comment] 2023-09-22 14:53
Tried using both the keychain, and a custom `.pem` cert provided by my company... Not only is it still failing, but now Raycast team has removed the original (better) extension that was working. Is the Raycast team _trying_ to lose customers?

![2023-09-22 at 09 37 44@2x](https://github.com/raycast/extensions/assets/8473052/08f92304-400b-41c7-b538-0d24d26d0b04)

**Comment by macjabeth** [comment] 2023-10-04 17:44
**Update:** After getting updated `.pem` files from the powers that be and using those in the Advanced Configuration (custom) setting, the extension is loading things once more! Hopefully this helps. Thank you.

**Comment by mathieudutour** [comment] 2023-10-05 06:43
Awesome! Hopefully we can drive this extension forward in the open now!

**Closed by mathieudutour** 2023-10-05 06:43 UTC
Labels: bug, extension, extension: jira
