### ISSUE TITLE
[Quit Applications] ...

### ISSUE THREAD

**Issue by LeTriponaute** [raycast/extensions#6362] opened 2023-05-06 11:12 UTC
### Extension

https://www.raycast.com/mackopes/quit-applications

#### Error:
Error: Command failed with exit code 1: osascript -e 
    set appPaths to {}
    tell application "System Events"
      repeat with aProcess in (get file of every process whose background only is false)
        set processPath to POSIX path of aProcess
        set end of appPaths to processPath
      end repeat
    end tell

    return appPaths
  
177:187: execution error: Can’t get POSIX path of missing value. (-1728)

    set appPaths to {}
    tell application "System Events"
      repeat with aProcess in (get file of every process whose background only is false)
        set processPath to POSIX path of aProcess

```

```

### Steps To Reproduce

open raycast
put input

**Comment by mackopes** [comment] 2023-06-25 13:54
Hi @LeTriponaute,

Apologies for the delayed response. I missed this issue until the raycastbot pinged me again.

Unfortunately I cannot reproduce this bug. Could you please try again with as many applications closed as possible? This is most probably caused by a specific application. If we could pinpoint which app it is, I could debug this further. If you could help that'd be perfect!

**Closed** 2023-08-24 15:03 UTC
Labels: bug, extension, status: stalled, extension: quit-applications
