### ISSUE TITLE
[YouTube Downloader] Error: "Output format X is not available" regardless of format 

### ISSUE THREAD

**Issue by kaouzz** [raycast/extensions#12319] opened 2024-05-13 12:45 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

When trying to download a video the download runs and right after downloading 100% of the video, the download crashes and error message "Output format X is not available." 

Changing format and size makes no difference, the same error occurs irrespective of format. 

![Screenshot](https://github.com/raycast/extensions/assets/80008872/d8c431e3-b18b-424a-b062-cf03d637a3b4)

### Steps To Reproduce

1. Copy URL of chosen YouTube video
2. Open Raycast and select the extension "YouTube Downloader"
3. Select format
4. Run extension [command + enter] to start download
5. Wait for the download to complete
6. Error occurs here, right after download completes 

### Current Behaviour

No file is downloaded. File does not appear in selected download path. 

### Expected Behaviour

Downloaded file appears in selected download path after download has completed.

**Comment by vimtor** [comment] 2024-05-13 13:36
Hi @kaouzz!

Sadly, this is a known issue. The problem is related to the new `ffmpeg` version and the library we are using to process the videos.

Check out the temporary solution here: https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625

**Comment by vimtor** [comment] 2024-07-04 07:52
This was fixed by https://github.com/raycast/extensions/pull/12583

@raycastbot close this issue

**Closed** 2024-07-04 07:53 UTC
Labels: bug, extension, status: stalled, extension: youtube-downloader
