### ISSUE TITLE
[Library Genesis] TypeError: p.replace is not a function

### ISSUE THREAD

**Issue by timebooksio** [raycast/extensions#8778] opened 2023-10-12 09:42 UTC
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

![CleanShot 2023-10-12 at 16 41 03@2x](https://github.com/raycast/extensions/assets/66457203/dc8ba571-111a-43f5-a110-83bb7947e57c)

### Steps To Reproduce

Searching any books name

**Comment by jphastings** [comment] 2023-11-10 09:36
This is a duplicate of #8355, there's a [quick-fix](https://github.com/raycast/extensions/issues/8355#issuecomment-1720927792) and an explanation in the (short!) thread.

**Comment by j3lte** [comment] 2023-12-11 18:33
Fixed in #9549, issue can be closed

**Comment by j3lte** [comment] 2023-12-13 00:45
@raycastbot close this issue

**Closed** 2023-12-13 00:45 UTC
Labels: bug, extension, extension: library-genesis
