### ISSUE TITLE
[Jira] The new Jira extension always gives me a "Something Went Wrong" error

### ISSUE THREAD

**Issue by dgobera-humane** [raycast/extensions#6567] opened 2023-05-15 23:27 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"

```

### Steps To Reproduce

1. Enable the new Jira extension, log in
2. Invoke the "Open Issues" action

### Current Behaviour

Error saying "Something went wrong"

<img width="862" alt="Screenshot 2023-05-15 at 4 22 19 PM" src="https://github.com/raycast/extensions/assets/87452201/320b6fcb-3e1d-451f-90bf-ed0baf33266d">

### Expected Behaviour

In the old deprecated Jira extension, it always showed me my correct list of open issues.

**Comment by thomaslombart** [comment] 2023-05-16 08:23
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-16 08:23 UTC
Labels: bug, extension, extension: jira
