### ISSUE TITLE
Buggy jumps when scrolling on the docs

### ISSUE THREAD

**Issue by dgrcode** [raycast/extensions#2542] opened 2022-08-12 11:52 UTC
It's only happening when scrolling slowly.

At least happening in https://developers.raycast.com/api-reference/user-interface/list

gif of the bug:
![Screen Recording 2022-08-12 at 13 46 16](https://user-images.githubusercontent.com/17493200/184348257-da35c520-a0a6-4c89-bb2f-0ccf2a1403a4.gif)

**Comment by thomaslombart** [comment] 2023-09-06 14:09
Closing as not planned since I couldn't reproduce it plus it's something that we don't have control over since GitBook is used for the developer docs.

**Closed by thomaslombart** 2023-09-06 14:09 UTC
Labels: documentation
