### ISSUE TITLE
[QR Code Scanner] Not response when raycast mainwindow closed

### ISSUE THREAD

**Issue by like-aiquan** [raycast/extensions#11210] opened 2024-03-11 13:36 UTC
### Extension

https://www.raycast.com/StevenRCE0/qr-code-scanner

### Description

After closing the Raycast main window, the function does not toggle.

### Steps To Reproduce

In the index.tsx file line 47.
When closeMainWindow(); is called, there will be no response when scanning the QR code. 
But when we block closeMainWindow(); and comment it out, the program can run normally, but there will be an empty raycast window blocking the screen.
I don’t know how this happens, please help me.

Uploading a.mp4…

**Comment by StevenRCE0** [comment] 2024-03-12 05:05
Thanks for your feedback. Please check if you're on the latest branch, the issue should be solved by 4607fbd29b7955b9d4b3653ea2934f93595ba350

**Comment by like-aiquan** [comment] 2024-03-12 06:34
> Thanks for your feedback. Please check if you're on the latest branch, the issue should be solved by [4607fbd](https://github.com/raycast/extensions/commit/4607fbd29b7955b9d4b3653ea2934f93595ba350)

Hello, thank you for helping me look at this problem. I can now confirm that my branch has the code of your [https://github.com/raycast/extensions/commit/4607fbd29b7955b9d4b3653ea2934f93595ba350](4607fbd) commit this time. I checked it. In your submission record, you should have changed the main function to a synchronous method, and then added a new change log.
![a](https://github.com/raycast/extensions/assets/65346310/2493e1a9-7eaa-4d14-ae2f-606305381029)

**Comment by StevenRCE0** [comment] 2024-03-12 09:02
Sorry I didn't quite get it, is the problem still persist on the latest version? If it does, please provide more details (log, error screen, etc.) Since I weren't able to reproduce it. 

---

不好意思，我不太明白你的意思；是在最新的代码上这个问题仍然存在吗？这个问题在我这里无法复现，如果依然存在麻烦提供日志截图这样的相关信息。

**Comment by like-aiquan** [comment] 2024-03-12 10:57
> Sorry I didn't quite get it, is the problem still persist on the latest version? If it does, please provide more details (log, error screen, etc.) since I wasn't able to reproduce it.
> 
> 不好意思，我不太明白你的意思；是在最新的代码上这个问题仍然存在吗？这个问题在我这里无法复现，如果依然存在麻烦提供日志截图这样的相关信息。

哈哈, 我这边是直接从raycast的仓库fork的代码,应该是您fix之后的分支,而且我看fork下来的有您提交的代码,我有一份录屏文件您可以帮我看看. 最诡异的就是我并没有看到任何错误...

Haha, I forked the code directly from the raycast extension repository. It should be the branch after your fix. And I see that the forked code contains the code you submitted. I have a screen recording file that you can help me take a look at. The weirdest thing The thing is I don't see any errors...


https://github.com/raycast/extensions/assets/65346310/4d51d9b4-4805-4800-b91c-040991816c94

**Comment by StevenRCE0** [comment] 2024-03-19 11:32
I see, the cause is likely to be what #11358 pointed out. When it gets popped in the background, the lifecycle is terminated. A patch is going to be merged. You may also try cloning my fork to see if it's fixed.

**Comment by StevenRCE0** [comment] 2024-03-20 07:17
The problem *should* be solved by now...Otherwise feel free to reopen.

@raycastbot close this issue

**Closed** 2024-03-20 07:18 UTC
Labels: bug, extension, extension: qr-code-scanner

**Comment by like-aiquan** [comment] 2024-03-21 06:01
Yes, you fixed, thank you!
