### ISSUE TITLE
[Browser Bookmarks] It often crashes when I search for a bookmark.

### ISSUE THREAD

**Issue by binbjz** [raycast/extensions#11623] opened 2024-04-04 03:29 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

It often crashes when I search for a bookmark.

### Current Behaviour

Something went wrong.
<img width="761" alt="Screenshot 2024-04-04 at 11 28 06" src="https://github.com/raycast/extensions/assets/8213913/c8016b17-2a3b-4cc1-b831-2e82e5f8806a">

### Expected Behaviour

It should search for bookmarks normally every time and be able to open bookmarks by hitting enter in the default browser.

**Comment by thomaslombart** [comment] 2024-04-04 08:25
Thanks for bringing this up. It appears that this is a duplicate of issue #6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-04-04 08:25 UTC
Labels: bug, extension, extension: browser-bookmarks
