### ISSUE TITLE
Sip Commands open Zoom, not Sip

### ISSUE THREAD

**Issue by jmabeebiz** [raycast/extensions#7947] opened 2023-08-15 12:45 UTC
### Extension

https://www.raycast.com/jameslyons/sip

### Description

I just downloaded Sip today and I'm still on my free trial, but I installed the Raycast extension and when I try to use Sip with Raycast, every command opens Zoom.us app. 

### Steps To Reproduce

Try and run a command with Sip using Raycast. Not sure if this is just me though...

### Current Behaviour

Opens Zoom instead of Sip

### Expected Behaviour

Opens Sip

**Comment by megaroeny** [comment] 2023-08-16 18:50
In my case, it opens Teams. Odds are its because they just released a major redesign for v3.0. The extension probably needs some updates/fixes as a result.

**Comment by jamesjlyons** [comment] 2023-08-16 20:51
Thanks for reporting this! I'll take a look at the update as well, but there was an issue with Webex in the current version. 

Unfortunately, it looks like other apps also use the 'sip://' URL scheme (mostly video call apps, most likely to handle SIP calls). Not sure if there's anything I can do on the extension side to make sure the correct app is receiving the URL scheme but I'll look into it. Otherwise I might have to reach out the the Sip team.

**Comment by megaroeny** [comment] 2023-08-16 21:01
@jamesjlyons cool no worries! Thanks

**Comment by jamesjlyons** [comment] 2023-08-17 01:36
Can confirm it's now opening Teams after upgrading to v3, and it worked just before updating Sip. There's no updates in the docs I can see, reached out to the team to see if they have an idea of what's going on.

**Comment by jamesjlyons** [comment] 2023-08-23 18:43
> I just tried it again today, and it seems to be working now. Did you push a fix?

Nope, no updates on my end! Haven't heard back from the Sip team yet, maybe they pushed an update though?

**Comment by megaroeny** [comment] 2023-08-23 18:46
> > I just tried it again today, and it seems to be working now. Did you push a fix?
> 
> Nope, no updates on my end! Haven't heard back from the Sip team yet, maybe they pushed an update though?

Try it out and see what happens on your end. Maybe they fixed something with their API then 🤷🏼‍♂️

**Comment by jamesjlyons** [comment] 2023-08-24 02:14
> > Nope, no updates on my end! Haven't heard back from the Sip team yet, maybe they pushed an update though?
> 
> Try it out and see what happens on your end. Maybe they fixed something with their API then 🤷🏼‍♂️

Ah yeah, they shipped an update today and it's working on my end now. @jmabeebiz can you confirm if it works for you on the latest Sip version (3.03)? If so we can close out this issue.

**Comment by jmabeebiz** [comment] 2023-08-24 02:21
Can confirm, issue is resolved!

Thanks,
// Justin Mabee
*Freelance Squarespace Web Design*
justinmabee.com ( http://justinmabee.com )
(267) 632-4103

Sent via Superhuman ( ***@***.*** )

**Comment by jamesjlyons** [comment] 2023-08-24 18:26
@raycastbot close issue

**Comment by jamesjlyons** [comment] 2023-08-24 18:41
@raycastbot close this issue

**Closed** 2023-08-24 18:41 UTC
Labels: bug, extension, extension: sip

**Comment by megaroeny** [comment] 2023-11-07 15:13
This is happening again now with WebEx, unfortunately. Can anyone else confirm? @jamesjlyons

**Comment by jamesjlyons** [comment] 2023-11-08 02:06
I'm away for a while, but when I'm back to my computer next week I'll download webex and see if I can confirm. Bummer that this keeps popping up.

**Comment by jamesjlyons** [comment] 2023-12-04 00:47
@megaroeny any chance the Sip 3.3.1 update fixed this?
