### ISSUE TITLE
Notion: LKe} has an invalid date. If time zone is explicitly provided, start and end must contain date and time 

### ISSUE THREAD

**Issue by marcoale94** [raycast/extensions#10687] opened 2024-02-10 14:17 UTC
### Extension

https://www.raycast.com/notion/notion

### Description

Hi,
by trying to create an event in my notion calendar I get this error when i specify the time.
<img width="686" alt="image" src="https://github.com/raycast/extensions/assets/17622932/d3d127d5-c3ab-4dc8-b9c0-89675a1794ed">
If I just put the day without time it works.

I'm attaching the log file I generated with this command while trying to reproduce the error, hopefully it will be usefull.
[ray.20240210_144952.log](https://github.com/raycast/extensions/files/14229519/ray.20240210_144952.log)

thank you in advance.

### Steps To Reproduce

Macbook M1 pro
MacOS Sonoma 14.1.1
cmd + space -> create database page -> select my own calendar -> typing "in five minutes" in the date textbox -> selecting the suggestion -> fill in other fields -> cmd + enter

**Comment by erics118** [comment] 2024-02-10 14:19
Looks like a regression due to something I did a while ago. I'll see if I can fix this sometime today.

**Comment by erics118** [comment] 2024-02-10 15:49
Fixed in #10689

**Closed** 2024-02-19 10:42 UTC
Labels: bug, extension, extension: notion
