### ISSUE TITLE
[Apple Reminders] ... Text {selection} to create a reminder

### ISSUE THREAD

**Issue by connorwforsyth** [raycast/extensions#14206] opened 2024-08-27 03:27 UTC
### Extension

https://www.raycast.com/raycast/apple-reminders

### Description

Can the reminders extension integrate perhaps with Raycast Pros AI features, to enable a user to create a reminder based on the text {selection}?

I.e. 
![CF - Messaging - 2024 08 27](https://github.com/user-attachments/assets/12113949-64df-475b-84e5-223553b50950)

### Who will benefit from this feature?

Raycast pro users, and those needing to quickly create reminders for themselves with extra speed and reduced context switching.

**Comment by thomaslombart** [comment] 2024-08-27 13:40
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/13853, so I'll mark it as such.

**Closed by thomaslombart** 2024-08-27 13:40 UTC
Labels: feature request, extension, extension: apple-reminders
