### ISSUE TITLE
[Apple Reminders] Cannot list reminders (did **not** forget to give permissions)

### ISSUE THREAD

**Issue by ddotlic** [raycast/extensions#10518] opened 2024-02-02 07:42 UTC
### Extension

https://raycast.com/raycast/apple-reminders

#### Error:
```
SwiftError: Could not get any data
    at ChildProcess.<anonymous> (/Users/draza/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/my-reminders.js:51:40213)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at Pipe.<anonymous> (node:net:337:12)
```

### Steps To Reproduce

Just trying to open "My Reminders" fails immediately. Trying again, takes a really long time with no result.

### Current Behaviour

It's important to note that - of course - the app was given access to the Reminders (`Privacy and Security -> Reminders`). In fact, I used to use the legacy reminders on two machines and _everything worked fine_. 

As soon as I removed the legacy and installed the new "Apple Reminders", listing reminders does not work. Tried deactivating permission for Reminders, removing the permission (using `tccutil`) then re-adding, does not help. Reproduced on two different machines, both running AS (M2 and M2 Pro, Air and mini), macOS 14.3.

**Creating** a reminder works, though. Really weird.

### Expected Behaviour

Listing reminders should not fail.

**Comment by ddotlic** [comment] 2024-02-02 07:46
Note: _almost_ a duplicate of #10509 and I also confirm that while creating a reminder the extension cannot **fetch** the names of lists, but for me, it does eventually create the reminder. Listing never works.

**Comment by thomaslombart** [comment] 2024-02-02 10:49
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9172, so I'll mark it as such.

**Closed by thomaslombart** 2024-02-02 10:49 UTC
Labels: bug, extension, extension: apple-reminders
