### ISSUE TITLE
[Jira] active sprint command returs all the possible projects in a company

### ISSUE THREAD

**Issue by Justverbickas** [raycast/extensions#6753] opened 2023-05-24 12:41 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

I really enjoy Raycast's Active Sprint feature and I've created a shortcut to access it quickly. The only downside is that I work in a large company, so every time I open Active Sprint, I have to use ⌘+P to search for my project. It would be great if it could show my favorite projects or my most recently used ones by default. 

Thanks!

### Who will benefit from this feature?

I see everyone who works in bigger companies and has access to multiple projects, but only wants to focus on projects which matter to their work.

**Comment by thomaslombart** [comment] 2023-05-25 08:23
Thanks for bringing this up. It appears that this is a duplicate of issue #5988, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-25 08:23 UTC
Labels: feature request, extension, extension: jira
