### ISSUE TITLE
[Nextcloud] ...

### ISSUE THREAD

**Issue by caloracloud** [raycast/extensions#5040] opened 2023-02-28 13:25 UTC
### Extension

https://www.raycast.com/uetchy/nextcloud

### Description

Hello all !
When I try to find a file on my nextcloud instance the extension returns the following message:

API request failed TypeError: Cannot read properties of undefined (reading 'd:prop')

<img width="606" alt="Screenshot 2023-02-28 at 10 21 54" src="https://user-images.githubusercontent.com/111899507/221867231-eff3c18d-9034-4ac8-8c1d-bb86e68c05e0.png">

**Comment by foss-** [comment] 2023-03-15 13:10
This is not limited to file search, but also affects Show Deck.

Show Activity, Show Notes. List Favorites works without error.

**Comment by BotMister** [comment] 2023-03-24 14:06
I guess the issue I opened a while back is relevant here: #4726

**Comment by foss-** [comment] 2023-05-15 11:11
I don't understand the benefit of a bot randomly closing valid issues. This issue is real, reproducible and unresolved.

**Comment by jacobkossman** [comment] 2023-06-26 19:54
also confirming the issue is still occurring.

**Comment by foss-** [comment] 2023-08-15 23:10
I don't understand the benefit of a bot randomly closing valid issues. This issue is real, reproducible and unresolved.

**Closed** 2023-10-15 00:56 UTC
Labels: bug, extension, status: stalled, extension: nextcloud

**Comment by BugsWorld** [comment] 2023-10-15 18:31
Nextcloud Extension is still not working. I've been waiting for a fix since forever. Proper Nextcloud integration would really make my raycast experience so much better. Is there a way to keep this issue open? Keeps getting closed.
