### ISSUE TITLE
[Bitwarden Vault] Biometric

### ISSUE THREAD

**Issue by marcomiche00** [raycast/extensions#9214] opened 2023-11-12 09:24 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

Is it possible to add biometric login?

### Who will benefit from this feature?

Everyone

**Comment by jomifepe** [comment] 2023-11-15 23:30
Hello, thanks for the suggestion. Multiple people have asked for this, and here's why it's not implemented yet: https://github.com/raycast/extensions/issues/8075#issuecomment-1694508921

**Comment by jomifepe** [comment] 2023-12-29 16:16
Duplicate of #8075

**Comment by jomifepe** [comment] 2023-12-29 16:17
@raycastbot close this issue

**Closed** 2023-12-29 16:17 UTC
Labels: feature request, extension, extension: bitwarden
