### ISSUE TITLE
[Linear] ...Workspace switcher

### ISSUE THREAD

**Issue by robbyrob42** [raycast/extensions#14941] opened 2024-10-16 06:05 UTC
### Extension

https://www.raycast.com/linear/linear

### Description

It would be wonderful to be able to switch the logged-in workspace from the command context modal (or worst case even just the ability to logout from that context menu in the meantime) Love ya!

### Who will benefit from this feature?

anyone using multiple workspaces of Linear. Consultants, agencies, even internal teams not on a single workspace.

**Comment by thomaslombart** [comment] 2024-10-16 12:38
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/4299, so I'll mark it as such.

**Closed by thomaslombart** 2024-10-16 12:38 UTC
Labels: feature request, extension, extension: linear

**Comment by robbyrob42** [comment] 2024-10-17 01:50
My apologies for the dupe! Appreciate you have it in the backlog already. I'm a huge fan of the plugin!

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=cm9iQHJvb3RzeXN0ZW0uY29t>
