### ISSUE TITLE
[Bitwarden Vault] ... - Keep getting "Failed to get password" error.

### ISSUE THREAD

**Issue by YufusKhan** [raycast/extensions#8788] opened 2023-10-12 22:16 UTC
### Extension

https://www.raycast.com/jomifepe/bitwarden

### Description

I just always get it on all of the passwords

### Steps To Reproduce

Go to "Search vault"
Select any one
Click enter

**Comment by utkarshk384** [comment] 2023-10-16 01:28
Hello there,
I'm also facing the same issue. I am unable to logout, sync vault, get the password. Also as soon as I try to search for an item it throws an error message "Failed to load items".

**Comment by jomifepe** [comment] 2023-10-23 22:24
Hello, thanks for reporting, and I'm sorry this is happening. Reinstalling the extension might solve it for now. In the meantime, I'm trying to debug these issues and solve them, it's not easy as there's not a lot of information, and there's always the possibility of some of these being caused by different CLI versions.

**Comment by YufusKhan** [comment] 2023-10-23 22:42
Thanks for your response. I will try reinstalling it.

--
Yusuf

**Comment by kernelguardian** [comment] 2023-11-29 12:50
I am also seeing this issue, The error is `Username or password is incorrect. Try again.` 
A search suggests this https://community.bitwarden.com/t/web-and-desktop-client-username-or-password-is-incorrect/57038/3

**Comment by kernelguardian** [comment] 2023-11-30 06:57
Updating the bitwarden-cli through brew fixed the issue for me. 
`brew upgrade bitwarden-cli`

**Comment by jomifepe** [comment] 2023-12-29 16:20
@YufusKhan did you manage to get it working by reinstalling or installing a different version of the CLI?

I plan on removing the requirement of the CLI and having it download and manage its own version.

**Comment by YufusKhan** [comment] 2023-12-30 03:32
I fixed it by reinstalling the extension.

**Comment by jomifepe** [comment] 2023-12-30 15:43
Great, thanks for reporting.

@raycastbot close this issue

**Closed** 2023-12-30 15:43 UTC
Labels: bug, extension, extension: bitwarden
