### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by 483dca0024cdefe0e8293c39b1e24544** [raycast/extensions#8673] opened 2023-10-04 11:41 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
Error: Player command failed: Premium required

pi:play.ts:68:10

---
65:     }
66: 
67:     console.log("play.ts Error: ", error)

### Steps To Reproduce

when i try to click on any command it's stuck and the whole raycast ai stopped working. yes, i successfully logged in.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by erics118** [comment] 2023-10-15 06:06
the extension uses the API, which requires premium.

**Comment by erics118** [comment] 2023-10-15 21:12
Duplicate of #7730

**Comment by thomaslombart** [comment] 2023-11-03 13:38
Closing it in favor of #7730.

**Closed by thomaslombart** 2023-11-03 13:38 UTC
Labels: bug, extension, extension: spotify-player
