### ISSUE TITLE
[Dev Tools Bug] Dev build failed with file: reference in package.json

### ISSUE THREAD

**Issue by BoruiGu** [raycast/extensions#458] opened 2021-12-02 01:26 UTC
Raycast version: 1.26.1

## Description

dev build fails when package.json contains dependencies with file: reference

## Steps To Reproduce

Rep 1:

1. Create Extension
2. run `npm install <package> <path>` to install dependency `"<package>": "file:..."`
3. run `npm run dev`

Rep 2:

1. Create Extension
2. run `npm link <path>`
3. run `npm run dev`

## The current behavior

💥 Error: build failed: Could not resolve ""

## The expected behavior

dev build should be successful

**Comment by fe9lix** [comment] 2021-12-07 16:44
I'm closing this issue since I'm unable to reproduce it and local file references seem to work. Example: 
Adding a customized version of the npm `open` package to the root source folder of the extension and then referencing the extension as local dependency: 
`"open": "file:./open"`

**Closed by fe9lix** 2021-12-07 16:44 UTC
Labels: bug, dev tools

**Comment by BoruiGu** [comment] 2021-12-07 21:42
thanks @fe9lix, i spent more time to investigate the issue and it turned out to be a different cause, created https://github.com/raycast/extensions/issues/495
