### ISSUE TITLE
[Browser Bookmarks] ...

### ISSUE THREAD

**Issue by Yejinius** [raycast/extensions#10371] opened 2024-01-26 16:26 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. run raycast
2. typing bm (command) and enter to search menu

### Current Behaviour

then it works a bit 2 seconds around. and print error like screenshot.
<img width="767" alt="Screenshot 2024-01-27 at 1 25 05 AM" src="https://github.com/raycast/extensions/assets/11899758/7274aefd-ef85-4d02-937d-3b9f9f0c6058">

### Expected Behaviour

When the list of bookmark is too big, it makes an error I guess. Please take a look about this issue.

**Comment by thomaslombart** [comment] 2024-01-29 07:58
Thanks for bringing this up. It appears that this is a duplicate of issue #6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-01-29 07:58 UTC
Labels: bug, extension, extension: browser-bookmarks
