### ISSUE TITLE
[Spotify Player] Menu Bar Player Disappears forever when idling

### ISSUE THREAD

**Issue by rakanalb** [raycast/extensions#10645] opened 2024-02-08 08:22 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

The menu bar player worked at first then after idling and sleeping the machine it wouldn't show up the next day. I tried all possible configurations except uninstalling the extension (changing the Maximum text length, deactivating and reactivating the service, enabling and disabling, changing the icon type, etc.).

The final solution was disabling and reenabling "Hide icon while idling".
I assume the issue is the icon gets hidden while idle and then can't get unhidden, so I disabled the option.
<img width="305" alt="image" src="https://github.com/raycast/extensions/assets/29729356/255cf2a7-cc02-4751-845e-31c874692862">

### Steps To Reproduce

1. Enable Menu bar player
2. Enable "Hide icon while idling" setting
3. Let machine idle/sleep whilst Spotify on the machine is not playing
4. Come back after idling/sleeping to find the Spotify menu bar player disappeared

### Current Behaviour

Menu bar player disappears whilst idle and never reappears when coming out of idling

### Expected Behaviour

The menu bar player should disappear whilst idling but it should also reappear when coming out of idling.

**Comment by thomaslombart** [comment] 2024-03-19 13:50
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10477, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-19 13:50 UTC
Labels: bug, extension, extension: spotify-player
