### ISSUE TITLE
[Transmit] ... the extension does not load the server list

### ISSUE THREAD

**Issue by gpessia** [raycast/extensions#15584] opened 2024-11-28 13:08 UTC
### Extension

https://www.raycast.com/kennonb/transmit

### Raycast Version

1.86.1

### macOS Version

15.1.1

### Description

Error: Missing required property "title" for List.Item

### Steps To Reproduce

![CleanShot 2024-11-28 at 14 08 26@2x](https://github.com/user-attachments/assets/ad95db74-2d4e-41e4-9b35-f4a38efb59ff)

**Comment by xmok** [comment] 2024-11-30 17:12
Hi @gpessia.

I just gave the extension a whirl and it's working for me. From the `Error` it seems like your *Server* has an empty "name". Transmit isn't letting me save w/o a name so I can't reproduce but can you try adding a "name" and does that make the error go away? If so, I can push a fix ASAP.
Thanks.

**Comment by gpessia** [comment] 2024-11-30 19:15
Yep! You're right. I have about 50 servers and only one was unnamed. I added the name and now it works perfectly. Thanks.

**Comment by xmok** [comment] 2024-11-30 20:28
Glad to hear it 😄.
I've made a PR with a fix so others don't run into the issue. Once the PR is merged the bot will close the Issue automatically. Thanks for your help in troubleshooting.

**Closed** 2024-12-03 11:46 UTC
Labels: bug, extension, extension: transmit

**Comment by matthewpinto** [comment] 2024-12-03 20:15
Hey everyone. I installed this extension yesterday and it worked beautifully; today I am getting no servers found, and a prompt to download Transmit (which I most certainly have installed). Not a dev so unsure how to get an error log here. Attached is a screenshot. Thanks!

<img width="762" alt="Screenshot 2024-12-03 at 3 13 38 PM" src="https://github.com/user-attachments/assets/32d23189-b57a-4a50-a2af-2c7622fef3eb">
