### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by gatszegi** [raycast/extensions#14706] opened 2024-09-28 17:56 UTC
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.83.1

### macOS Version

15.0

#### Error:
```
Error: Item not found

fo:api.ts:82:12

---
79:     const uuid = Object.keys(data.sync_status)[0]
------
----

Second error:
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20



### Steps To Reproduce

1. Enable ManuBar item
2. Do anything (complete, change date, focus)
3.  Crash

I logged out and in again and I did not add my Todoist Token nor the Focus Label and it's working
Adding any of Token or Label case crash

Error: Item not found

fo:api.ts:82:12

---
79:     const uuid = Object.keys(data.sync_status)[0];
80:     if (data.sync_status[uuid] !== "ok") {
81:       const error = data.sync_status[uuid] as { error: string };
82:       throw new Error(error.error);
83:     }
84:   }
85: 
---

async gi:menu-bar.js:63:6278
async c:menu-bar.js:63:11718

### Current Behaviour

Crash

### Expected Behaviour

No crash

**Comment by thomaslombart** [comment] 2024-09-30 06:46
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/14659, so I'll mark it as such.

**Closed by thomaslombart** 2024-09-30 06:46 UTC
Labels: bug, extension, extension: todoist
