### ISSUE TITLE
[Jira] The selected filter is not saved when using "My Filters" command

### ISSUE THREAD

**Issue by antoinerey** [raycast/extensions#6293] opened 2023-05-03 12:12 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

I've recently switched from the legacy Jira extension to the new one, and noticed an unexpected behaviour: when executing the "My Filters" command, the selected filter (top right) always goes back to the very first one in the list. With the legacy extension, after picking one filter, it was kept on subsequent execution, which I feel like is the way it should work.

![CleanShot 2023-05-03 at 14 07 31@2x](https://user-images.githubusercontent.com/3336873/235911466-aa83d065-a363-426e-80a7-7c871c550d03.png)

Is there anything I could configure on my side, or is something not working as expected?

### Steps To Reproduce

1. Install the official Jira extension.
2. Execute the "My Filters" command.
3. Pick another filter on the top right.
4. Hide the Raycast window.
5. Execute the "My Filters" command again.
6. Notice that the previously selected filter is not the one currently selected.

### Expected Behaviour

I feel like the filter selected the last time you executed the "My Filters" command should be saved somehow, and used on subsequent executions.

**Comment by thomaslombart** [comment] 2023-05-03 14:05
Thanks for bringing this up. There's an issue when using typeahead search in the filters selection field. It's actually a duplicate of issue #5735, so I'll mark it as such 😊

**Closed by thomaslombart** 2023-05-03 14:05 UTC
Labels: bug, extension, extension: jira

**Comment by antoinerey** [comment] 2023-05-04 09:22
Woops. I did not find this issue when browsing the list. 🙇
