### ISSUE TITLE
Crashing when trying to "Open Issues"

### ISSUE THREAD

**Issue by tobbbe** [raycast/extensions#7796] opened 2023-08-04 11:07 UTC
### Extension

https://www.raycast.com/raycast/github

#### Error:
```
TypeError: Cannot read properties of null (reading 'name')

py:IssueActions.tsx:31:39

---
28:   children?: React.ReactNode;
29: };
30: 
31: export default function IssueActions({ issue, mutateList, mutateDetail, children }: IssueActionsProps) {
32:   const { github } = getGitHubClient();
33: 
34:   const viewer = useViewer();
---

    at ray-list-item
Rn:index.js:23:21950
NA:open-issues.js:1284:5567

### Steps To Reproduce

Work earlier so I might have an Github Issue that causing problems?

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

**Comment by thomaslombart** [comment] 2023-08-04 13:37
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/4831, so I'll mark it as such.

**Closed by thomaslombart** 2023-08-04 13:37 UTC
Labels: bug, extension, extension: github
