### ISSUE TITLE
[API Feature Request] QuickLook

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#393] opened 2021-11-19 20:27 UTC
add a function to show the QuickLook preview of a file/folder

**Describe the feature and the current behavior/state.**

Currently, we can use `qlmanage` to show a different quicklook window, but it is very different from the one that Finder shows. Adding this function allows us to use the Finder QuickLook instead.

**Will this change the current api? How?**

adds a `showQuickLook(file: string)` function

**Who will benefit with this feature?**

developers and users

**Any Other info.**

**Comment by thomaspaulmann** [comment] 2021-11-21 17:24
Seems like this is a duplicate of #367. Gonna close that one to keep the discussion in one place. Thanks for propsing an API 👏

**Closed by thomaspaulmann** 2021-11-21 17:24 UTC
Labels: api, feature request

**Comment by mathieudutour** [comment] 2022-02-04 10:17
Duplicate of #367
