### ISSUE TITLE
[Todoist] Add Natural Language Processing for Task Creation

### ISSUE THREAD

**Issue by adityaastro** [raycast/extensions#13280] opened 2024-07-01 21:45 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

Add natural language processing (NLP) capabilities to the Todoist extension for Raycast. This feature would allow users to create tasks using everyday language, automatically interpreting dates, priorities, and project assignments.

### Who will benefit from this feature?

Todoist users who prefer a more intuitive and conversational way of creating tasks. It would streamline the task creation process, making it faster and more user-friendly. 

### Anything else?

This feature could leverage Todoist's existing NLP capabilities, similar to how it works in the main Todoist app. It would enhance the extension's functionality, making it more aligned with Todoist's core features.

**Comment by jfkisafk** [comment] 2024-07-01 22:11
This is similar to https://github.com/raycast/extensions/issues/12769 and I will start the implementation in July.

**Comment by thomaslombart** [comment] 2024-07-03 08:39
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/12769, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-03 08:39 UTC
Labels: feature request, extension, extension: todoist
