### ISSUE TITLE
[Swift Package Index] ...

### ISSUE THREAD

**Issue by atacan** [raycast/extensions#11399] opened 2024-03-20 08:03 UTC
### Extension

https://www.raycast.com/maximkrouk/swift-package-index

### Description

```console
Could not perform search SyntaxError: Unexpected token '<, "‹!DOCTYPE " ... is not valid JSON
```

### Steps To Reproduce

- Type a search term.
- Get an error.

### Current Behaviour

Error

![ScrShot 2024-03-20 at 09 01 47@2x](https://github.com/raycast/extensions/assets/765873/56d1e0e8-3d0c-41c2-9973-9d926756b1c0)

### Expected Behaviour

Fetch and show search results

**Comment by japanese-goblinn** [comment] 2024-03-22 14:39
Hey @atacan. It's a duplicate of https://github.com/raycast/extensions/issues/11132. The fix is in progress and will be done hopefully next week.

**Comment by maximkrouk** [comment] 2024-05-05 17:32
Fixed in https://github.com/raycast/extensions/pull/11539 ✅

**Closed** 2024-07-04 18:04 UTC
Labels: bug, extension, status: stalled, extension: swift-package-index
