### ISSUE TITLE
[Browser Bookmarks] Search terms are not accurately matching against bookmarks

### ISSUE THREAD

**Issue by rkoval** [raycast/extensions#8541] opened 2023-09-23 20:58 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Search terms are not accurately matching against bookmarks

### Steps To Reproduce

1. Add a search term that filters bookmarks down to a list. For example:

  ![CleanShot 2023-09-23 at 15 51 33@2x](https://github.com/raycast/extensions/assets/1282943/8f3defe8-5ee2-4f8b-8546-da865b64719e)

2. I am ultimately trying to filter down to the bookmark with "sync" in it (see above screenshot with red arrow), so add another term to attempt to filter the bookmarks down further. For example:
  <img width="862" alt="CleanShot 2023-09-23 at 15 51 42@2x" src="https://github.com/raycast/extensions/assets/1282943/b20946e8-e687-4a62-907e-33efc3c974b9">

3. Observe that all bookmarks are filtered out despite providing terms that are relevant

### Current Behaviour

Search terms ignore terms in a bookmark's name. I do not have this issue in Alfred with their default bookmark search:

First query (notice how results are basically the same as Raycast's at this point):
![CleanShot 2023-09-23 at 15 55 53@2x](https://github.com/raycast/extensions/assets/1282943/35170978-989c-4008-8745-2f00f4e73154)

Second query:
<img width="764" alt="CleanShot 2023-09-23 at 15 56 42@2x" src="https://github.com/raycast/extensions/assets/1282943/15538b08-0cc5-465b-b73a-0bc48f9a7834">

### Expected Behaviour

Search terms should match terms in a bookmark's name

**Comment by thomaslombart** [comment] 2023-09-25 11:59
Thanks for bringing this up. It appears that this is a duplicate of issue #8514, so I'll mark it as such.

**Closed by thomaslombart** 2023-09-25 11:59 UTC
Labels: bug, extension, extension: browser-bookmarks
