### ISSUE TITLE
Raycast Bitwarden extension not loading bug

### ISSUE THREAD

**Issue by SARRAF-5757** [raycast/extensions#867] opened 2022-02-11 03:18 UTC
# Extension – [Bitwarden Vault](https://github.com/raycast/extensions/tree/71dc0903b48af29aa0595ad456899ba7679312e0/extensions/bitwarden/)
Author: @pomdtr

## Error:
```

```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.28.0

**Comment by pomdtr** [comment] 2022-03-24 09:54
@mattisssa can we close this ? The issue is not useful without details

**Closed** 2022-03-24 15:02 UTC
Labels: bug, extension
