### ISSUE TITLE
[Brew] search page not opening

### ISSUE THREAD

**Issue by iamaamir** [raycast/extensions#3482] opened 2022-11-11 10:43 UTC
# Extension – [Brew](https://github.com/raycast/extensions/tree/dd6d1181a4d488063098d5561759026bafd36f6d/extensions/brew/)
Author: @nhojb

## Description
going to search page showing the below page
<img width="862" alt="image" src="https://user-images.githubusercontent.com/8420386/201323959-3c54ada4-ac53-4e11-9945-32c838c4ed88.png">

## Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

## Steps To Reproduce

1.
2.

### Raycast version
Version: 1.43.1

**Comment by TonyVlcek** [comment] 2022-11-11 13:46
This seems to be a duplicate of #3142

**Comment by nhojb** [comment] 2022-11-11 15:38
@iamaamir this should be fixed now once your local extension updates.

**Closed** 2022-11-11 15:38 UTC
Labels: bug, extension

**Comment by iamaamir** [comment] 2022-11-22 06:16
yes, seems to working now , thanks
