### ISSUE TITLE
[Browser Bookmarks] ...Extension crashes when accessing my Arc Bookmarks

### ISSUE THREAD

**Issue by seishonagon** [raycast/extensions#15342] opened 2024-11-13 05:53 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.85.2

### macOS Version

15.1

### Description

The extensions properly accesses the Google Chrome bookmarks, but if I select the Arc browser, it crashes on start.  
Here's the log:
Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

### Steps To Reproduce

Not sure how to describe. I start the extension and it crashes. When I reinstall and select only Chrome it works perfectlyl

**Comment by thomaslombart** [comment] 2024-11-13 08:50
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-11-13 08:50 UTC
Labels: bug, extension, extension: browser-bookmarks
