### ISSUE TITLE
[Installed Extensions] ...

### ISSUE THREAD

**Issue by angelineflorajohn** [raycast/extensions#10866] opened 2024-02-21 15:46 UTC
### Extension

https://www.raycast.com/pernielsentikaer/installed-extensions

### Description

Adding the option to uninstall an extension through the list of all extensions instead of having to go to the extensions window every time will be really helpful and save time for some of the pro users.

![image](https://github.com/raycast/extensions/assets/25217498/13c05b89-1388-471e-a80d-f18d81c96820)

### Who will benefit from this feature?

Everyone

**Comment by erics118** [comment] 2024-02-22 04:25
Duplicate of https://github.com/raycast/extensions/issues/9161

**Comment by pernielsentikaer** [comment] 2024-02-22 09:27
Yeah, extensions doesn't have access to such action so it's not possible 🫠

**Closed by pernielsentikaer** 2024-02-22 09:27 UTC
Labels: feature request, extension, extension: installed-extensions

**Comment by angelineflorajohn** [comment] 2024-02-22 14:46
@pernielsentikaer is there any chance (or plan) of making this extension into Raycast native command to add this functionality?

**Comment by pernielsentikaer** [comment] 2024-02-22 15:00
There will be a revamp of the preference window in the future, but it's not planned yet 🙂

**Comment by angelineflorajohn** [comment] 2024-02-22 15:27
Looking forward to that! Thank you @pernielsentikaer
