### ISSUE TITLE
[Apple Notes] Stopped working search notes and shows error

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#11285] opened 2024-03-14 10:49 UTC
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Stopped working after recent Raycast update and shows error: "Cannot search notes database disk image is malformed"

### Steps To Reproduce

Open Raycast, write "Search notes" hit enter and see error.

**Comment by ChaithzKRU** [comment] 2024-03-22 08:54
Same is happening to me

**Comment by thomaslombart** [comment] 2024-03-22 11:17
It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6916, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-22 11:17 UTC
Labels: bug, extension, extension: apple-notes
