### ISSUE TITLE
[Spotify Player] Extension is completely unresponsive

### ISSUE THREAD

**Issue by leo-leesco** [raycast/extensions#13311] opened 2024-07-03 17:53 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.78.0

#### Error:
```
Error: Error while refreshing tokens: 400 (Bad Request)
{"error":"invalid_grant","error_description":"Refresh token revoked"}

r1.refreshTokens:OAuthService.js:134:18

---
131:         if (!response.ok) {
132:             const responseText = await response.text()

### Steps To Reproduce

Nothing much, I didn't change anything but the shortcuts stopped working and same for the commands

### Current Behaviour

No command works anymore

### Expected Behaviour

_No response_

**Comment by thomaslombart** [comment] 2024-07-04 07:43
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/13167, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-04 07:43 UTC
Labels: bug, extension, extension: spotify-player
