### ISSUE TITLE
[Library Genesis] p.replace is not a function

### ISSUE THREAD

**Issue by filipruisl** [raycast/extensions#8333] opened 2023-09-11 13:46 UTC
### Extension

https://www.raycast.com/yz3440/library-genesis

### Description

After submitting a query I'm getting an error "p.replace is not a function" and the search yields 0 results

### Steps To Reproduce

Search for anything using the extension and wait for the result.

**Comment by jphastings** [comment] 2023-11-10 09:36
This is a duplicate of #8355, there's a [quick-fix](https://github.com/raycast/extensions/issues/8355#issuecomment-1720927792) and an explanation in the (short!) thread.

**Comment by j3lte** [comment] 2023-12-11 18:34
Fixed in #9549, issue can be closed

**Comment by j3lte** [comment] 2023-12-13 00:45
@raycastbot close this issue

**Closed** 2023-12-13 00:45 UTC
Labels: bug, extension, extension: library-genesis
