### ISSUE TITLE
Bug with menu bar icon[Pomodoro] ...

### ISSUE THREAD

**Issue by SeaSphynx** [raycast/extensions#5106] opened 2023-03-02 20:30 UTC
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

Once I set up a session, i.e. 25 minute focus session with 5 minute short breaks and 20 minute long breaks), the menu icon appears but will only activate the counting down seconds when I click on it.

Specs:
13-inch, 2020, Two Thunderbolt 3 ports
1.4 GHz Quad-Core Intel Core i5
Intel Iris Plus Graphics 645 1536 MB
8 GB 2133 MHz LPDDR3
Macintosh HD
13.0 (22A380)

### Current Behaviour

Once the timer starts, it will show 24:59 and will be stuck on that number. It only changes to the most recent update once I click on the menu icon, it won't update every second on its own. For example, the timer will start and will be stuck at 24:59 and if I click on the menu icon 10 seconds later, the menu icon will switch from showing 24:59 immediately to 24:49. But then the menu icon will be stuck on that new number until I click on the menu bar icon again.

### Expected Behaviour

It should simply update every second and be accurate to the real time as it counts down instead of being stuck on a number from the most recent time I clicked on the menu bar icon.

**Comment by thekorn** [comment] 2023-03-12 17:31
thats a duplicate of https://github.com/raycast/extensions/issues/4524 (which also includes a reason for this behaviour)

**Comment by pernielsentikaer** [comment] 2023-05-12 07:02
That's correct, for now, it's only possible to update the menubar every 10. second

**Closed by pernielsentikaer** 2023-05-12 07:02 UTC
Labels: bug, extension, status: stalled, extension: pomodoro
