### ISSUE TITLE
[ChatGPT] "Ask Question" Command not work!

### ISSUE THREAD

**Issue by lonly197** [raycast/extensions#5837] opened 2023-04-09 10:02 UTC
### Extension

https://www.raycast.com/abielzulio/chatgpt

### Description

"Ask Question" Command not work!

#### Error:
```
Something went wrong!
```

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7350356/230766608-f60dc31e-1ef2-4884-b8c1-ff185893916d.png">

### Current Behaviour

<img width="750" alt="image" src="https://user-images.githubusercontent.com/7350356/230766636-f63f9dfa-42e0-47fb-a7db-54275c5b73c3.png">

**Comment by abielzulio** [comment] 2023-04-09 14:37
Could you give me your error logs? Couldn't reproduce it on my end.

https://user-images.githubusercontent.com/7030944/230779072-ff773433-0a3f-4a69-b322-e51205daef69.mp4

**Comment by abielzulio** [comment] 2023-05-13 16:40
Closing due to inability to reproduce the same error given

**Comment by abielzulio** [comment] 2023-05-13 16:40
@raycastbot close this issue

**Closed** 2023-05-13 16:40 UTC
Labels: bug, extension, extension: chatgpt
