### ISSUE TITLE
[Toothpick] ...

### ISSUE THREAD

**Issue by romaness** [raycast/extensions#4289] opened 2023-01-17 10:12 UTC
### Extension

https://raycast.com/briankosw/toothpick

### Description

Hello,
I am trying to use the Toothpick extension. However, I somehow cannot see the steps I need to do with the settings to make it working. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/37443611/212870566-f3caf771-b79e-4192-a613-d0378cb35d37.png">

### Steps To Reproduce

1. Install Toothpick
2. Open a toothpick command

### Current Behaviour

Cannot see the things I need to add to the settings

### Expected Behaviour

Should see the things I need to add to the settings

**Comment by VladCuciureanu** [comment] 2023-01-18 10:31
You just need to press 'Continue' in the bottom-right side of the window (or press Command+Enter)
<img width="752" alt="Screenshot 2023-01-18 at 12 30 50" src="https://user-images.githubusercontent.com/71708164/213148621-ac8776d1-6f3e-4645-a360-85e4c9ca01af.png">

**Comment by romaness** [comment] 2023-01-18 15:58
> You just need to press 'Continue' in the bottom-right side of the window (or press Command+Enter)
> <img alt="Screenshot 2023-01-18 at 12 30 50" width="752" src="https://user-images.githubusercontent.com/71708164/213148621-ac8776d1-6f3e-4645-a360-85e4c9ca01af.png">

Thank you for your reply. When I just press continue I can't disconnect any devices somehow from the device list. So I thought I might have skipped these mentioned "preferences steps".

**Comment by VladCuciureanu** [comment] 2023-01-18 18:53
It's definitely not the preferences. I'm going to need more info. Do your devices appear in the device list?
When you try to connect to them, what happens?

**Comment by VladCuciureanu** [comment] 2023-01-25 09:08
@raycastbot close this issue

**Closed** 2023-01-25 12:58 UTC
Labels: bug, extension

**Comment by romaness** [comment] 2023-01-26 17:25
> It's definitely not the preferences. I'm going to need more info. Do your devices appear in the device list?
> When you try to connect to them, what happens?

Sorry for my late reply.
Yes, all my devices appear in the device list.
When I try to disconnect the device it stays connected. 
Here is how it looks like: https://www.loom.com/share/aaa105e96385439698b1a00f1ab0ba04

**Comment by VladCuciureanu** [comment] 2023-01-26 17:39
> > It's definitely not the preferences. I'm going to need more info. Do your devices appear in the device list?
> 
> > When you try to connect to them, what happens?
> 
> 
> 
> Sorry for my late reply.
> 
> Yes, all my devices appear in the device list.
> 
> When I try to disconnect the device it stays connected. 
> 
> Here is how it looks like: https://www.loom.com/share/aaa105e96385439698b1a00f1ab0ba04
> 
> 

Ah yes. That's a known issue caused by a MacOS bug that can only be patched from Raycast Team's side (already talked to them & waiting for their response)

**Comment by romaness** [comment] 2023-01-26 17:46
> > > It's definitely not the preferences. I'm going to need more info. Do your devices appear in the device list?
> > 
> > 
> > > When you try to connect to them, what happens?
> > 
> > 
> > Sorry for my late reply.
> > Yes, all my devices appear in the device list.
> > When I try to disconnect the device it stays connected.
> > Here is how it looks like: https://www.loom.com/share/aaa105e96385439698b1a00f1ab0ba04
> 
> Ah yes. That's a known issue caused by a MacOS bug that can only be patched from Raycast Team's side (already talked to them & waiting for their response)

Alright got it. Thank you! 
Then let's hope that gets fixed soon.

**Comment by VladCuciureanu** [comment] 2023-01-26 18:36
> > > > It's definitely not the preferences. I'm going to need more info. Do your devices appear in the device list?
> 
> > > 
> 
> > > 
> 
> > > > When you try to connect to them, what happens?
> 
> > > 
> 
> > > 
> 
> > > Sorry for my late reply.
> 
> > > Yes, all my devices appear in the device list.
> 
> > > When I try to disconnect the device it stays connected.
> 
> > > Here is how it looks like: https://www.loom.com/share/aaa105e96385439698b1a00f1ab0ba04
> 
> > 
> 
> > Ah yes. That's a known issue caused by a MacOS bug that can only be patched from Raycast Team's side (already talked to them & waiting for their response)
> 
> 
> 
> Alright got it. Thank you! 
> 
> Then let's hope that gets fixed soon.

Fingers crossed 🤞🏻

**Comment by VladCuciureanu** [comment] 2023-02-04 17:10
@romaness See #3636 for a temporary solution

**Comment by romaness** [comment] 2023-02-04 17:19
> @romaness See #3636 for a temporary solution

Perfect got it working now! Thank you very much.

**Comment by VladCuciureanu** [comment] 2023-09-04 09:44
So, good news (kinda).
#8193
I implemented a compat-layer for 'blueutil' which improves this situation.

1. Install 'blueutil' via brew
2. Update Raycast
3. Update Toothpick
4. Open Toothpick preferences
5. Switch Bluetooth Backend to 'blueutil'

Connecting/disconnecting should be faster and less flaky. Testing was limited so I can't guarantee that it's perfect but, to me, it looks like an improvement :>
