### ISSUE TITLE
[Browser Bookmarks] ...

### ISSUE THREAD

**Issue by paulminors** [raycast/extensions#12524] opened 2024-05-23 09:23 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

Latest

### macOS Version

Latest

### Description

When viewing bookmarks in Raycast, it's showing the wrong favicon:

![CleanShot 2024-05-23 at 21 22 22@2x](https://github.com/raycast/extensions/assets/16178904/88e30221-08d2-4f15-872d-c10abc33bf7d)

### Steps To Reproduce

You can test this with your own bookmarks I guess.

**Comment by thomaslombart** [comment] 2024-05-23 14:44
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6590, so I'll mark it as such.

**Closed by thomaslombart** 2024-05-23 14:44 UTC
Labels: bug, extension, extension: browser-bookmarks
