### ISSUE TITLE
[Arc]...some mistake with "search tab" command.

### ISSUE THREAD

**Issue by Arsik0803** [raycast/extensions#10101] opened 2024-01-11 11:30 UTC
### Extension

https://raycast.com/the-browser-company/arc

#### Error:
```
SyntaxError: Unexpected token '’', ..."ни здоров\’я є найкр"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.T5 [as current] (/Users/arsenpetrosov/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:89:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

I've only selected option "Search Tabs" and've got the mistake.

**Comment by radualexe32** [comment] 2024-01-12 04:02
+1

**Comment by megaroeny** [comment] 2024-01-25 17:02
There's still ongoing issues with any commands related to Tabs. Tried again today to go to a tab via the command, and it'll just open a tab with a blank screen. Very odd.

**Comment by thomaslombart** [comment] 2024-01-30 10:58
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9758, so I'll mark it as such.

**Closed by thomaslombart** 2024-01-30 10:58 UTC
Labels: bug, extension, extension: arc
