### ISSUE TITLE
[1Password] Ability to to pull from multiple accounts when logged into both via CLI

### ISSUE THREAD

**Issue by Levi-Lido** [raycast/extensions#5332] opened 2023-03-13 16:56 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Right now, I have both work and personal 1password accounts signed in on my machine, but in raycast, I can only be signed into one at a time. I would like to be able to access both whenever.

**Comment by khasbilegt** [comment] 2023-03-13 21:36
Duplicate of #4744

**Closed** 2023-03-14 09:15 UTC
Labels: feature request, extension, extension: 1password
