### ISSUE TITLE
[Jira] "Open Issues" fails

### ISSUE THREAD

**Issue by chrismetcalf** [raycast/extensions#6171] opened 2023-04-25 21:58 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

1. Launch the JIRA "Open Issues" command
2. Command fails

**Comment by thomaslombart** [comment] 2023-04-26 07:21
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.

**Closed by thomaslombart** 2023-04-26 07:21 UTC
Labels: bug, extension, extension: jira
