### ISSUE TITLE
[Jira] Delay until one can start typing

### ISSUE THREAD

**Issue by ahoereth** [raycast/extensions#7238] opened 2023-06-22 17:40 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

When entering basically any command in the jira extension, there is an initial loading period before one can start typing. This makes using the extension less smooth. 

To be clear: I understand that a lot of information used by the extension is only available after some network requests, my remark here is solely about me expecting the input interface being available earlier, so one can start typing queries earlier, which are okay to only be executed once everything else loaded up.

See the videos and the loading bars below. I also understand this is more of a nit and not really to be considered a bug.

### Steps To Reproduce

1. Install and setup jira extension.
2. Execute extension's "search issues" or any other command.
3. Observe load bar before the main text field becomes available.

### Current Behaviour

https://github.com/raycast/extensions/assets/3015996/44ff2e86-4eae-4df3-8f1f-b8efcbd6d547

https://github.com/raycast/extensions/assets/3015996/af65f665-b63e-4c4e-9702-853d02a488ae

### Expected Behaviour

1. Select command
2. Be able to type immediately

As a good example, compare with this screen recording of the confluence extension:

https://github.com/raycast/extensions/assets/3015996/7ae472a3-51d2-43d3-91d9-3fba8aba9b38

**Comment by thomaslombart** [comment] 2023-06-23 07:38
Thanks for bringing this up. It appears that this is a duplicate of issue #6960, so I'll mark it as such.

**Closed by thomaslombart** 2023-06-23 07:38 UTC
Labels: bug, extension, extension: jira
