### ISSUE TITLE
[Pomodoro] Menu item not updating (second counter)

### ISSUE THREAD

**Issue by chandlerroth** [raycast/extensions#4077] opened 2022-12-27 17:33 UTC
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

When a pomodoro timer is running, the timer is not progressing (unless I click on the menu item). In contrast, you can see the Clock app timer is running ok (see attached video). 

Pomodoro extension menu item is to the right, and the macOS Clock app timer is on the left:

https://user-images.githubusercontent.com/894178/209701394-c4f5f280-68e4-43d0-a256-cbfe2302e5a6.mov

**Comment by KELiON** [comment] 2023-01-09 04:29
As @pernielsentikaer mentioned, it is expected behaviour, timer updated every 10 seconds, not every second

**Comment by pernielsentikaer** [comment] 2023-01-18 11:53
Closing since it's not possible, we might consider lowering this in the future

**Closed by pernielsentikaer** 2023-01-18 11:53 UTC
Labels: bug, extension, extension: pomodoro
