### ISSUE TITLE
[Elgato Key Light] ...

### ISSUE THREAD

**Issue by kimpa888** [raycast/extensions#3331] opened 2022-10-27 08:57 UTC
# Extension – [Elgato Key Light](https://github.com/raycast/extensions/tree/4479d612107d01bc93466c2ce7049e8b6fa79bfe/extensions/elgato-key-light/)
Author:

## Description

I use the extension to turn on and off my elgato key light. It has used well, but now it just tells me "Cannot discover any key lights in network". 

I can still manage the light using the elgato control center to manage the light, so it is not like I'm not connected to it. 

## Steps To Reproduce

1. Run the extension in raycast
2. Get error message

## The current behavior
- Doesn't turn on/off light

## The expected behavior

Turns on/off light

### Raycast version

Raycast v1.42.1

**Comment by qor72** [comment] 2022-11-02 18:54
Duplicate of https://github.com/raycast/extensions/issues/3326

**Closed** 2022-11-25 00:14 UTC
Labels: bug, extension, status: stalled
