### ISSUE TITLE
[Jira Search] Search Boards -> TypeError: cannot read properties of undefined (reading 'displayName')

### ISSUE THREAD

**Issue by scottmmjackson** [raycast/extensions#6561] opened 2023-05-15 15:09 UTC
### Extension

https://www.raycast.com/sven/jira-search

### Description

In a properly configured Jira Search plugin accessing a Jira Cloud instance, I get a `TypeError` searching boards.

### Steps To Reproduce

1. Get the Jira Search plugin
2. Configure for Jira cloud
3. Attempt to search for boards

### Current Behaviour

TypeError

### Expected Behaviour

Search for boards

**Comment by svenwiegand** [comment] 2023-05-15 15:27
@scottmmjackson Can you please post a screenshot or copy and paste the full error message? Do other commands of the extension work (e.g. search for issues)?

**Comment by scottmmjackson** [comment] 2023-05-15 15:29
Other commands work. The full error message is in the issue title. Unfortunately the error only appears in a toast at the bottom of the raycast command palette- I can't find it dumped to the logs or anything.

If you still want a screenshot I'm happy to offer one but I don't know how much it'll help.

**Comment by svenwiegand** [comment] 2023-05-15 16:12
Thank you – no screenshot needed. It‘s a pain, that raycast doesn‘t provide logging on the user side … I don’t understand in which case this error could appear. Will try to make the code more tolerant. May take a while, because I‘m busy at the moment.

**Comment by scottmmjackson** [comment] 2023-05-15 16:31
Actually, I just curl'd the endpoint and the shape looks different.

I'm getting:

```
{
...,
"values": [
   {
     "id": 20,
     "self": <uri>,
     "name": "Development",
     "type": "scrum"
   }
}
```

So it's entirely missing the `location` object. It looks like the API docs show that as well:

https://developer.atlassian.com/cloud/jira/software/rest/api-group-other-operations/#api-rest-agile-1-0-board-get

**Comment by scottmmjackson** [comment] 2023-05-15 18:49
I'm curious if this works for you or if it's only my instance that responds in this way? The shape looks like the response one gets from `GET /rest/agile/1.0/board/{boardId}`, which I think implies that we'd be trying to essentially do a (pseudocode):

```
const boards = (await getBoards()).map(board => await getBoardById(board.id));
```

**Comment by scottmmjackson** [comment] 2023-05-16 00:05
I have done a little more poking, and I think this is only true in the case where there's no project for the board. Needless to say, it's possible.

@svenwiegand are you welcoming PRs for this?

**Comment by svenwiegand** [comment] 2023-05-16 06:37
Thanks for your analysis @scottmmjackson, this made fixing the issue a breeze. #6571 should fix the issue.

Unfortunately I was not able to reproduce this issue. All the boards in my Jira instance do have a location. Can you give a hint, how to create one without a location.

**Comment by svenwiegand** [comment] 2023-05-16 06:38
@raycastbot close this issue

**Closed** 2023-05-16 06:38 UTC
Labels: bug, extension, extension: jira-search

**Comment by svenwiegand** [comment] 2023-05-16 16:30
No problem. Have you been able to verify the fix?

**Comment by scottmmjackson** [comment] 2023-05-19 18:07
Yes! Fix verified!!
