### ISSUE TITLE
[1Password] "Allow Raycast to get CLI Access" prompts constantly

### ISSUE THREAD

**Issue by scottschechner** [raycast/extensions#12095] opened 2024-04-30 12:25 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

Raycast is asking for CLI access 10+ times per day for the 1Password extension. I don’t believe I’ve changed any extension settings.

### Steps To Reproduce

1. Install 1Password extension for Raycast
2. Wait until the CLI prompt appears
3. Give 1Password access
4. Watch the prompt reappear throughout the day

**Comment by Luk4h** [comment] 2024-05-02 11:46
Hello Scott, how are you? 1Password has a 10 minute cooldown for each unlock. There is a command that is disabled by default that extends this cooldown up to 12 hours. But you may get prompts from nowhere after waking the device on. You may disable the command to auto renew if you prefer to only use the prompts when trying to access a password. Right now it is working as intended, but I will include an improvement to its functionality to avoid these random prompts.

**Comment by j-peeters** [comment] 2024-05-03 07:50
> You may disable the command to auto renew if you prefer to only use the prompts when trying to access a password.
That would be a great addition for me.

**Comment by romanr** [comment] 2024-05-03 11:43
Happens about once every hour for me, while I never use this extension, or when I didn't use Raycast in hours.. 

I am not sure what is usefulness of extension over 1P built-in functionality, you can enable [1P "Quick access" ](https://support.1password.com/quick-access/) global shortcut `⇧`+`⌘`+`Space`, which pops its own up Raycast-like interface to copy your credentials.

**Comment by Luk4h** [comment] 2024-05-03 12:06
On the settings page, on 1Password commands, the auto renew command has the background refresh enabled? By default it should be disabled.

**Comment by j-peeters** [comment] 2024-05-03 12:20
It was 'on' for me, thanks for this, I deactivated it. I didn't change this manually so maybe this is set by the extension to 'on' by default. Might be an idea to set it to 'off'?

**Comment by scottschechner** [comment] 2024-05-03 12:22
It was on by default for me as well.

Would there be a way to prompt [1P "Quick access" ](https://support.1password.com/quick-access/)global shortcut ⇧+⌘+Space within Raycast itself using an alias?

**Comment by Luk4h** [comment] 2024-05-03 14:37
It should be off by default, I will add a fix for it on the next update. Sorry about it guys.

**Comment by j-peeters** [comment] 2024-05-03 14:38
No problem @Luk4h Thanks for clarifying and fixing!

**Comment by Luk4h** [comment] 2024-05-03 14:40
> Would there be a way to prompt [1P "Quick access" ](https://support.1password.com/quick-access/)global shortcut ⇧+⌘+Space within Raycast itself using an alias?

I am not sure about it, I dont think so since its directly to an app not browser or cli...

**Comment by romanr** [comment] 2024-05-03 17:55
> It was on by default for me as well.
> 
> Would there be a way to prompt [1P "Quick access" ](https://support.1password.com/quick-access/)global shortcut ⇧+⌘+Space within Raycast itself using an alias?

You can set it to any shortcut in 1P. I have Raycast set to ⌘+Space.

**Comment by Luk4h** [comment] 2024-05-21 13:10
With the latest update, there is now a better authorization system that will always require only 1 prompt. If the auto-renew feature is enabled, it will only start renewing after the first manual sign-in, solving the issue of the random prompts. Also, it is ensured that the auto-renew feature is now disabled by default, ensuring that users are in control of their authorization process.

@raycastbot close this issue

**Closed** 2024-05-21 13:10 UTC
Labels: bug, extension, extension: 1password
