### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by lukaspiwowar** [raycast/extensions#13516] opened 2024-07-17 13:06 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.78.1

### macOS Version

14.4.1

### Description

I have to reauthorize Spotify several times a day for the extension to work.

### Steps To Reproduce

It just stops working and requires reauthorization.

**Comment by lukaspiwowar** [comment] 2024-07-17 13:07
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"\n    at mn (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6354)\n    at D0\n    at Fr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2490)\n    at ray-navigation-stack\n    at No (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:2088)\n    at Suspense\n    at Nr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:7:2335)\n    at ray-root\n    at Ii (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:8:3000)","breadcrumbs":[]}: OAuth request creation is not available when command is launched in background

**Comment by thomaslombart** [comment] 2024-07-18 09:30
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-18 09:30 UTC
Labels: bug, extension, extension: spotify-player
