### ISSUE TITLE
[CleanShot X] ...

### ISSUE THREAD

**Issue by linpan** [raycast/extensions#9383] opened 2023-11-23 10:25 UTC
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

CleanShot_X_4.6.1 not work

### Steps To Reproduce

CleanShot_X_4.6.1 not work

### Current Behaviour

CleanShot_X_4.6.1 not work

### Expected Behaviour

CleanShot_X_4.6.1  cursor not change, not work. 4.6.0 is okay

**Comment by Aayush9029** [comment] 2023-11-23 13:20
@linpan 

Please Check README.md

**Comment by Aayush9029** [comment] 2023-11-29 16:31
![](https://github.com/raycast/extensions/raw/e24c69324167a7e932c63c20ffaca3e8ea33bddf/extensions/cleanshotx//media/EnableAPI.png)

If you've followed these steps. Please verify if 

typing `cleanshot://capture-area` in Safari URL bar yields.

![CleanShot 11-29 at 11 31 25](https://github.com/raycast/extensions/assets/43297314/5f09825a-5840-466e-96f7-1584cb825a6f)

**Comment by liunice** [comment] 2023-11-30 01:50
> ![](https://github.com/raycast/extensions/raw/e24c69324167a7e932c63c20ffaca3e8ea33bddf/extensions/cleanshotx//media/EnableAPI.png)
> 
> If you've followed these steps. Please verify by typing `cleanshot://capture-area` in Safari URL bar, which should show an alert like this
> 
> ![CleanShot 11-29 at 11 31 25](https://private-user-images.githubusercontent.com/43297314/286673913-5f09825a-5840-466e-96f7-1584cb825a6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDkxNjUsIm5iZiI6MTcwMTMwODg2NSwicGF0aCI6Ii80MzI5NzMxNC8yODY2NzM5MTMtNWYwOTgyNWEtNTg0MC00NjZlLTk2ZjctMTU4NGNiODI1YTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAxNDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MDI4YmEyNDE4NmJiNWRjMjZlNTkyNTNhYWI1OGJjMzk4ZTc3YjA2ZDcwY2ExY2Q3MzhmYmQzMWFlM2YwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJyd2HEXlAnMZErUfbfC_m614fOStqyhZ6C3OUH-2Rc)
> 
> Let me know what you see. Thank you!

I tested again, this time I found something weired. If cleanshot app is not open, requesting cleanshot://capture-area from browser can launch cleanshot app and activate area capturing function successfullly. But if cleanshot app has already been opened, requesting cleanshot://capture-area does nothing.

**Comment by Aayush9029** [comment] 2023-11-30 07:41
It sounds to me like the issue is with the app itself, rather than the extension.

Feel free to email their support team and see if they can help you with this issue :) 

You may link this discussion to provide more context.

**Comment by Aayush9029** [comment] 2023-11-30 07:41
@raycastbot close this issue

**Closed** 2023-11-30 07:41 UTC
Labels: bug, extension, extension: cleanshotx
