### ISSUE TITLE
[Apple Reminders] Brand new installation of Raycast Remindres

### ISSUE THREAD

**Issue by rochakagrawal** [raycast/extensions#10257] opened 2024-01-21 03:57 UTC
### Extension

https://raycast.com/raycast/apple-reminders

#### Error:
```
SwiftError: Could not get any data
    at ChildProcess.<anonymous> (/Users/rochakandshagun/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/my-reminders.js:50:13567)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

### Steps To Reproduce

1. uninstalled raycast and reinstalled a clean copy
2. installed apple reminders 
3. immediately getting  above error when opening "my reminders" first time

**Comment by thomaslombart** [comment] 2024-01-22 08:37
Thanks for bringing this up. It appears that this is a duplicate of issue #9172, so I'll mark it as such.

**Closed by thomaslombart** 2024-01-22 08:37 UTC
Labels: bug, extension, extension: apple-reminders
