### ISSUE TITLE
[Todoist] Cannot perform search, extension crashes

### ISSUE THREAD

**Issue by airandopal** [raycast/extensions#10436] opened 2024-01-29 22:59 UTC
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Alt + Spacebar to open Raycast
2. Type search, press enter to choose "Search" for Todoist
3. Type search term (it would sometimes start to show results here, or I would press enter)
4. Get extension crashed error screen 

### Current Behaviour

It's not letting me search, it just crashes when I try to see the results. 

I was going to take a screenshot, but I tried clearing the cache when pressing cmd+k , and now it's not even going to the error screen, but looping and saying no results. The extension is definitely still logged in because I was able to create a new task.

### Expected Behaviour

To see the results of the search

**Comment by thomaslombart** [comment] 2024-02-01 08:33
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10127, so I'll mark it as such.

**Closed by thomaslombart** 2024-02-01 08:33 UTC
Labels: bug, extension, extension: todoist
