### ISSUE TITLE
[1Password] Ability to sync multiple 1Password accounts in a single instance of Raycast

### ISSUE THREAD

**Issue by joshuaw-finedesign** [raycast/extensions#5133] opened 2023-03-04 02:26 UTC
### Extension

https://www.raycast.com/khasbilegt/1password

### Description

I have two 1Password accounts on my device: one for work, and the other for personal. It would be great to have the "My Passwords" Command populate with both lists, similar to how the 1Password native app allows for an "All Items" view that's searchable across accounts.

### Who will benefit from this feature?

Anyone with multiple 1Password accounts.

**Comment by thomaspaulmann** [comment] 2023-03-06 08:53
Seems like a duplicate of #4744

**Closed by thomaspaulmann** 2023-03-06 08:53 UTC
Labels: feature request, extension, extension: 1password
