### ISSUE TITLE
[Claude] ...This is not working 

### ISSUE THREAD

**Issue by fwends** [raycast/extensions#14103] opened 2024-08-20 10:42 UTC
### Extension

https://www.raycast.com/florisdobber/claude

### Raycast Version

don't know

### macOS Version

14.5 (23F79)

### Description

On the raycast window after putting in my api and trying to send any text it just says selected text could not load, my API key is up to date, it is sometimes working but most of the time not 

### Steps To Reproduce

Ask a question it gives a big red error at the bottom

### Current Behaviour

not working

### Expected Behaviour

to work

**Comment by florisdobber** [comment] 2024-09-12 08:22
Hi @fwends, I cannot reproduce this issue from a clean install. Can you give me any more information on the error you encountered? Perhaps it was an outage at Anthropic?

@raycastbot assign me

**Comment by florisdobber** [comment] 2024-10-14 17:23
@raycastbot close this issue

**Closed** 2024-10-14 17:23 UTC
Labels: bug, extension, extension: claude
