### ISSUE TITLE
[Jira] extension fails loading open issues

### ISSUE THREAD

**Issue by yehudaNahon** [raycast/extensions#5918] opened 2023-04-13 08:14 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"
```

### Steps To Reproduce

1. open raycast
2. search for open issues 
3. tap on the command

### Current Behaviour

failes to load

### Expected Behaviour

loads the issues

**Comment by thomaslombart** [comment] 2023-04-13 08:40
Thanks for bringing this up. It appears that this is a duplicate of issue #5907, so I'll mark it as such.

**Closed by thomaslombart** 2023-04-13 08:40 UTC
Labels: bug, extension, extension: jira
