### ISSUE TITLE
[GitHub] Can't create an issue on github.

### ISSUE THREAD

**Issue by gideonite** [raycast/extensions#7969] opened 2023-08-16 17:35 UTC
### Extension

https://raycast.com/raycast/github

#### Error:
```
Error: You do not have permission to view repository collaborators.: {"response":{"data":{"repository":{"defaultBranchRef":{"id":"MDM6UmVmOTM3NDE1NDQ6cmVmcy9oZWFkcy9tYXN0ZXI=","name":"master","target":{"authoredDate":"2018-02-09T18:09:22Z","oid":"f41731b965348259dcd94b0dcb1374d3e1c4ca7d","message":"added RVAE experiments"}},"refs":{"totalCount":1,"nodes":[{"id":"MDM6UmVmOTM3NDE1NDQ6cmVmcy9oZWFkcy9tYXN0ZXI=","name":"master","target":{"authoredDate":"2018-02-09T18:09:22Z","oid":"f41731b965348259dcd94b0dcb1374d3e1c4ca7d","message":"added RVAE experiments"}}]},"collaborators":null,"labels":{"totalCount":7,"nodes":[{"id":"MDU6TGFiZWw2MjI0MDc3OTg=","name":"bug","color":"ee0701","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc3OTk=","name":"duplicate","color":"cccccc","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc4MDA=","name":"enhancement","color":"84b6eb","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc4MDE=","name":"help wanted","color":"128A0C","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc4MDI=","name":"invalid","color":"e6e6e6","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc4MDM=","name":"question","color":"cc317c","isDefault":true},{"id":"MDU6TGFiZWw2MjI0MDc4MDQ=","name":"wontfix","color":"ffffff","isDefault":true}]},"projectsV2":{"totalCount":0,"nodes":[]},"milestones":{"totalCount":0,"nodes":[]},"pullRequestTemplates":[],"issueTemplates":[]}},"errors":[{"type":"FORBIDDEN","path":["repository","collaborators"],"locations":[{"line":20,"column":5}],"message":"You do not have permission to view repository collaborators."}],"status":200,"headers":{}},"request":{"query":"query dataForRepository($owner: String!, $name: String!) {\n  repository(owner: $owner, name: $name) {\n    defaultBranchRef {\n      id\n      name\n      target {\n        ...CommitFields\n      }\n    }\n    refs(refPrefix: \"refs/heads/\", direction: ASC, first: 50) {\n      totalCount\n      nodes {\n        id\n        name\n        target {\n          ...CommitFields\n        }\n      }\n    }\n    collaborators(first: 50) {\n      totalCount\n      nodes {\n        ...UserFields\n      }\n    }\n    labels(first: 50) {\n      totalCount\n      nodes {\n        id\n        name\n        color\n        isDefault\n      }\n    }\n    projectsV2(first: 50) {\n      totalCount\n      nodes {\n        id\n        title\n      }\n    }\n    milestones(first: 50, states: OPEN, orderBy: {field: DUE_DATE, direction: ASC}) {\n      totalCount\n      nodes {\n        id\n        title\n      }\n    }\n    pullRequestTemplates {\n      body\n    }\n    issueTemplates {\n      name\n      about\n      title\n      body\n    }\n  }\n}\n\nfragment CommitFields on Commit {\n  authoredDate\n  oid\n  message\n}\n\nfragment UserFields on User {\n  id\n  avatarUrl\n  name\n  login\n  isViewer\n}","variables":{"owner":"ratschlab","name":"RGAN"}}}
    at /Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:23442
    at p (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16848)
    at Object.next (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:16152)
    at u (/Users/gideond/.config/raycast/extensions/89648e03-cceb-4205-9f40-75fcb039a4c6/create-issue.js:220:15710)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

1. Run "Create Issue" from raycast
2. Observe the following behavior (see image below).
3. Cannot create issue on a particular repo (which happens to be private but I'm not sure if this is the main issue).
<img width="602" alt="image" src="https://github.com/raycast/extensions/assets/2163686/fd9ca5c7-def5-48d8-9f28-943eec69dbb5">

**Comment by thomaslombart** [comment] 2023-08-17 07:51
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/5209, so I'll mark it as such.

**Closed by thomaslombart** 2023-08-17 07:51 UTC
Labels: bug, extension, extension: github

**Comment by gideonite** [comment] 2023-08-24 15:29
Looks like #5209 was abandoned due to inactivity. Should I reopen that issue? @thomaslombart

**Comment by thomaslombart** [comment] 2023-09-04 14:13
Done!
