### ISSUE TITLE
[Linear] Setting of cycle does not work anymore

### ISSUE THREAD

**Issue by brunovollmer** [raycast/extensions#9017] opened 2023-10-29 18:03 UTC
### Extension

https://www.raycast.com/linear/linear

### Description

When creating an issue the cycle is not set correctly anymore.

### Steps To Reproduce

Create an issue from raycast with a cycle. Check in linear app (where the cycle is not set).

**Comment by thomaslombart** [comment] 2023-10-30 09:05
Could you send a recording to see what happens?

**Comment by brunovollmer** [comment] 2023-11-06 08:31
Hope it is clear like this:

Uploading Raycast Bug.mp4…

**Comment by brunovollmer** [comment] 2023-11-09 16:44
@thomaslombart any progress on this?

**Comment by thomaslombart** [comment] 2023-11-13 01:41
No progress on it yet. There is a growing list of extensions to maintain at Raycast, which implies that we cannot be at the top of everything. So, feel free to take a shot at it and open a PR. It will be greatly appreciated! 😊

Note that having a PR merged will earn you some credits as we want to reward contributions. You’ll then be able to exchange them in a swag store that we’ll launch soon!

**Comment by jfkisafk** [comment] 2024-06-23 14:39
@raycastbot assign me

**Comment by jfkisafk** [comment] 2024-06-23 15:51
Checked on my end and setting the cycles is working now. Maybe an issue with linear api itself, b/c I definitely noticed it not working in the timeframe @brunovollmer  created this issue.

Moreover, the way we've implemented the graphQL mutation should work as intended:

https://github.com/raycast/extensions/blob/5c077f5a72c66ae6caab0a5958f4d89fb30c86df/extensions/linear/src/api/createIssue.ts#L44-L46

Closing this issue. Please re-open if the latest version of the command/extension does not work for you @brunovollmer

**Comment by jfkisafk** [comment] 2024-06-23 15:51
@raycastbot close this issue

**Closed** 2024-06-23 15:51 UTC
Labels: bug, extension, extension: linear, Dont close

**Comment by brunovollmer** [comment] 2024-08-08 10:29
Works fine! Thanks for checking
