### ISSUE TITLE
[Spotify Player] Menu command no longer works

### ISSUE THREAD

**Issue by mikestopcontinues** [raycast/extensions#14373] opened 2024-09-07 17:12 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.82.0

### macOS Version

14.6.1

#### Error:
```
Error: The operation couldn’t be completed. (Foundation.JSONError error 0.)
```

### Steps To Reproduce

Error occurs even after logout/login.

**Comment by mattisssa** [comment] 2024-09-07 17:23
Hey, just found out the same behaviour on my machine, investigating what can it be. A tricky one since once I built it locally everything started to work normally...

**Comment by thomaslombart** [comment] 2024-09-30 06:37
It may have been caused by a regression in the API. Are you still experiencing the issue?

**Comment by mikestopcontinues** [comment] 2024-09-30 14:24
@thomaslombart Now it only shows the menu bar item when there's an error. It no longer shows what's playing. I've tried deactivating and reactivating it. Any ideas?

**Comment by thomaslombart** [comment] 2024-09-30 14:42
Could you share a recording? It'll make it easier to see what's happening.

**Comment by mikestopcontinues** [comment] 2024-09-30 22:46
This'll be pretty easy, as it just doesn't show anything. :) Thanks for looking into this.

https://github.com/user-attachments/assets/e71f9607-e28d-4202-9044-31e80d6aed54

**Comment by thomaslombart** [comment] 2024-10-01 07:46
The `Foundation.JSONError` has been fixed in 1.82.3, so I'd first check if you're up-to-date. I also know that the `Hide icon when idle` option, as shown below, has caused the menu bar player to be [a bit buggy](https://github.com/raycast/extensions/issues/7688). If it's enabled, I'd recommend disabling it. Otherwise, you can uninstall and then reinstall the extension.
 
![CleanShot 2024-10-01 at 09 45 11@2x](https://github.com/user-attachments/assets/5f80612f-4b80-457e-9f7f-14b49e649d1c)

**Comment by mikestopcontinues** [comment] 2024-10-01 14:17
@thomaslombart It was the "Hide icon" setting. I subscribed to the other issue. Thanks!

**Comment by thomaslombart** [comment] 2024-10-01 16:43
Thanks for letting me know! I'll close this one out then.

**Closed by thomaslombart** 2024-10-01 16:43 UTC
Labels: bug, extension, extension: spotify-player
