### ISSUE TITLE
[Jira] Cannot view Active Sprints

### ISSUE THREAD

**Issue by dkarter** [raycast/extensions#7103] opened 2023-06-14 16:25 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:

```
Error: Rendering failed:
Missing required property "title" for Unknown
```

### Steps To Reproduce

1. Install Jira extension
2. Login
3. View 'Active Sprints' in Raycast

### Current Behaviour

![Screenshot 2023-06-14 at 11 23 08](https://github.com/raycast/extensions/assets/551858/48c02066-f43f-44ed-be27-de367157022b)

### Expected Behaviour

The active sprint is shown. This used to work.

Also important to note and viewing 'Open Issues' does work for me.. so this is not a login problem. Likely it is expecting some data to be available on an object that doesn't have it `Missing required property "title" for Unknown`.

**Comment by dkarter** [comment] 2023-06-14 16:46
Update: I uninstalled the Jira extension and the issue was resolved. Might have been some bad cache? Feel free to close this issue if you don't think this is worth investigating at this time.

**Comment by thomaslombart** [comment] 2023-06-15 07:07
Thanks for bringing this up. It appears that this is a duplicate of issue #7091, so I'll mark it as such.

**Closed by thomaslombart** 2023-06-15 07:07 UTC
Labels: bug, extension, extension: jira
