### ISSUE TITLE
[API Feature Request] refreshTime

### ISSUE THREAD

**Issue by es183923** [raycast/extensions#92] opened 2021-10-18 01:38 UTC
**Describe the feature and the current behavior/state.**

Add `refreshTime` to extensions.
script-commands currently have the option to be `inline`, and use the `refreshTime` to update periodically.
This should be added to the API so that we can create complex inline commands.

**Will this change the current api? How?**
Yes. A new property will need to be created; I'm not sure how this should be implemented.

**Who will benefit with this feature?**

Extension developers and end users.

**Any Other info.**
No.

**Comment by es183923** [comment] 2021-10-18 10:57
Related to #41

**Comment by PitNikola** [comment] 2021-10-20 19:56
Duplicate of #41

**Closed by PitNikola** 2021-10-20 19:56 UTC
Labels: api, feature request
