### ISSUE TITLE
[YouTube Downloader] encoding failed

### ISSUE THREAD

**Issue by ShubhamPP04** [raycast/extensions#12210] opened 2024-05-06 15:37 UTC
### Extension

https://www.raycast.com/vimtor/youtube-downloader

### Description

Everytime I download any video it says encoding failed

### Steps To Reproduce

See error

**Comment by vimtor** [comment] 2024-05-11 13:28
Hi @ShubhamPP04!

Sadly, this is a known issue. The problem is related to the new `ffmpeg` version and the library we are using to process the videos.

Check out the temporary solution here: https://github.com/raycast/extensions/issues/12110#issuecomment-2089490625

**Comment by vimtor** [comment] 2024-07-04 07:54
This was fixed by https://github.com/raycast/extensions/pull/12583

@raycastbot close this issue

**Closed** 2024-07-04 07:55 UTC
Labels: bug, extension, status: stalled, extension: youtube-downloader
