### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by Bayar101** [raycast/extensions#14322] opened 2024-09-03 12:30 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.81.2

### macOS Version

14.6.1

### Description

My accound keeps getting logged out

### Steps To Reproduce

my connected spotify account keeps getting logged out daily, sometimes multiple times a day

**Comment by thomaslombart** [comment] 2024-09-04 07:51
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-09-04 07:51 UTC
Labels: bug, extension, extension: spotify-player
