### ISSUE TITLE
[Browser Bookmarks]... MaxObjectCount Exceeded on initial config

### ISSUE THREAD

**Issue by charmingnyc** [raycast/extensions#14905] opened 2024-10-13 15:33 UTC
### Extension

https://raycast.com/raycast/browser-bookmarks

### Raycast Version

1.84.2

### macOS Version

15.0.1

#### Error:
```
Error: maxObjectCount exceeded
    at je.parseBuffer (/Users/duanemorgan/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:33:60330)
    at u8 (/Users/duanemorgan/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:38:24511)
    at /Users/duanemorgan/.config/raycast/extensions/254a620a-7fba-450b-bc17-c2e1ce6809d8/index.js:38:25053
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
```
****

### Steps To Reproduce

Select Browser (with many, many) URL bookmarks

**Comment by thomaslombart** [comment] 2024-10-14 09:08
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/8640, so I'll mark it as such.

**Closed by thomaslombart** 2024-10-14 09:08 UTC
Labels: bug, extension, extension: browser-bookmarks
