### ISSUE TITLE
[Linear] Assignees missing from Linear issue creation

### ISSUE THREAD

**Issue by casey-chow** [raycast/extensions#8704] opened 2023-10-06 17:55 UTC
### Extension

https://www.raycast.com/linear/linear

### Description

When creating a Linear task, I'm missing a number of potential assignees I'd like to assign issues to, including myself.

### Steps To Reproduce

1. With Linear set up on my organization.
2. Try to create a Linear ticket and assign myself.

### Current Behaviour

Users not available.

### Expected Behaviour

The users should be available.

**Comment by thomaslombart** [comment] 2023-10-12 09:44
Thanks for reporting this. I will classify this as a feature request since the extension doesn't support typeahead search in dropdown.

**Comment by casey-chow** [comment] 2023-10-19 16:30
> Thanks for reporting this. I will classify this as a feature request since the extension doesn't support typeahead search in dropdown.

It's more than just typeahead search--I'm completely unable to assign myself to any issues on creation, even if I type in my full username or display name. If I do so, and change fields, the author field remains unassigned.

**Comment by jfkisafk** [comment] 2024-06-22 20:33
@raycastbot assign me

**Comment by jfkisafk** [comment] 2024-06-23 15:05
Checked on my end and setting the cycles is working now. Maybe an issue with linear api itself, b/c I definitely noticed it not working in the timeframe @casey-chow created this issue.

Moreover, the way we've implemented the graphQL mutation should work as intended:

https://github.com/raycast/extensions/blob/5c077f5a72c66ae6caab0a5958f4d89fb30c86df/extensions/linear/src/api/createIssue.ts#L44-L46

Closing this issue. Please re-open if the latest version of the command/extension does not work for you @casey-chow

**Comment by jfkisafk** [comment] 2024-06-23 15:06
@raycastbot close this issue

**Comment by jfkisafk** [comment] 2024-06-23 15:52
@raycastbot reopen this issue

**Closed** 2024-07-08 09:02 UTC
Labels: feature request, extension, extension: linear, Dont close
