### ISSUE TITLE
[Jira] ...

### ISSUE THREAD

**Issue by colinfitzp** [raycast/extensions#6448] opened 2023-05-10 09:20 UTC
### Extension

https://www.raycast.com/raycast/jira

#### Error:
```
Error: Rendering failed:
Missing required component property "title"

```

### Steps To Reproduce

1. Select "Open Issues"

The issue is temporarily resolved by logging out of Jira and Logging in again.

**Comment by colinfitzp** [comment] 2023-05-10 09:27
Yes, just now.  I'll double-check that my extensions are up to date.

**Comment by thomaslombart** [comment] 2023-05-12 12:40
I'll double-check that. Did the command failed immediately or did something happen in between?

**Comment by thomaslombart** [comment] 2023-05-17 12:32
Thanks for bringing this up. It appears that this is a duplicate of issue #6011, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-17 12:32 UTC
Labels: bug, extension, extension: jira
