### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by collinbell** [raycast/extensions#6864] opened 2023-05-30 21:37 UTC
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```

```

### Steps To Reproduce

"home" → something went wrong

### Current Behaviour

"something went wrong"

### Expected Behaviour

load extension

**Comment by thomaslombart** [comment] 2023-05-31 06:35
Thanks for bringing this up. It appears that this is a duplicate of issue #6562, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-31 06:35 UTC
Labels: bug, extension, extension: todoist
