### ISSUE TITLE
[Spotify Player] ...

### ISSUE THREAD

**Issue by Sabadzma** [raycast/extensions#11211] opened 2024-03-11 15:51 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

Can't connect spotify account
<img width="635" alt="Screenshot 2024-03-11 at 19 46 56" src="https://github.com/raycast/extensions/assets/68327968/538e81e0-c289-4e5e-a4d1-fabce3d6eaec">

### Steps To Reproduce

<img width="888" alt="1" src="https://github.com/raycast/extensions/assets/68327968/10a7caa1-2984-45b5-9ebb-29f664ef60c6">
<img width="429" alt="3" src="https://github.com/raycast/extensions/assets/68327968/10d60240-59c7-4b03-8169-cd79d4661ee8">
<img width="697" alt="2" src="https://github.com/raycast/extensions/assets/68327968/cc47cc15-0914-4689-bbca-4de65ed2dedc">
<img width="681" alt="4" src="https://github.com/raycast/extensions/assets/68327968/d2920a87-2ac8-4286-948a-ccceb2252d2d">

**Comment by thomaslombart** [comment] 2024-03-19 13:44
Thanks for reporting the issue. Could you send the error log?

**Comment by thomaslombart** [comment] 2024-03-19 13:51
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-19 13:51 UTC
Labels: bug, extension, extension: spotify-player
