### ISSUE TITLE
[Spotify Player] Toggling pause and play is not working

### ISSUE THREAD

**Issue by swapnil2911** [raycast/extensions#15143] opened 2024-10-29 05:33 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.84.3

### Description

Toggling pause and play is not working

### Steps To Reproduce

Just toggle with spotify extension on raycast

### Current Behaviour

When songs are paused, the play toggle works. 
But when the songs are playing, toggling it does not pause the music

### Expected Behaviour

It should toggle appropriately

**Comment by thomaslombart** [comment] 2024-10-31 09:34
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/14630, so I'll mark it as such.

**Closed by thomaslombart** 2024-10-31 09:34 UTC
Labels: bug, extension, extension: spotify-player
