### ISSUE TITLE
[GitHub] Repositories are not sorted based on starred state when searching repositories

### ISSUE THREAD

**Issue by gdebrauwer** [raycast/extensions#6449] opened 2023-05-10 10:56 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

In the previous GitHub extension, the repositories always placed your starred repositories at the top of the list (also when searching). This is currently not the case

### Steps To Reproduce

1. Search repositories
2. Check that your starred repositories are not the first repositories in the list

### Current Behaviour

Repositories are not sorted based on the starred state of authenticated GitHub user

### Expected Behaviour

Sort repositories based on the starred state of authenticated GitHub user

**Comment by thomaslombart** [comment] 2023-05-12 12:42
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/5813, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-12 12:42 UTC
Labels: bug, extension, extension: github
