### ISSUE TITLE
[GitHub] Occasional crashes when searching repositories

### ISSUE THREAD

**Issue by FelixLisczyk** [raycast/extensions#14344] opened 2024-09-05 11:13 UTC
### Extension

https://www.raycast.com/raycast/github

### Raycast Version

1.82.2

### macOS Version

15.1 Beta (24B5035e)

### Description

When I run the "Search Repositories" command, I occasionally get the following error:

```
Error: Could not store Cache data for key "history": Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

dW:search-repositories.tsx:19:47

---
16: 
17:   const preferences = getPreferenceValues<Preferences.SearchRepositories>();
18: 
19:   const [searchText, setSearchText] = useState("");
20:   const [searchFilter, setSearchFilter] = useState<string | null>(null);
21:   const [sortQuery, setSortQuery] = useCachedState<string>("sort-query", REPO_DEFAULT_SORT_QUERY, {
22:     cacheNamespace: "github-search-repo",
---

    at withAccessToken(dW)
_r:index.js:8:2593
    at ray-navigation-stack
```

### Steps To Reproduce

I don't have specific steps to reproduce the issue because the error occurs sporadically.

### Current Behaviour

The extension should not crash.

### Expected Behaviour

The extension crashes with the error mentioned above.

**Comment by jfkisafk** [comment] 2024-09-05 13:50
https://github.com/raycast/extensions/blob/c5726a63f0f95eb43ad162b724f62d1b43059483/extensions/github/src/helpers/repository.ts#L111-L112

**Comment by jfkisafk** [comment] 2024-09-05 13:51
Closing this as this is a duplicate of https://github.com/raycast/extensions/issues/14032

**Comment by jfkisafk** [comment] 2024-09-05 13:51
@raycastbot close this issue

**Closed** 2024-09-05 13:51 UTC
Labels: bug, extension, extension: github
