### ISSUE TITLE
[Apple Reminders] Getting SwiftError (Could not get any data) when opening My Reminders command

### ISSUE THREAD

**Issue by rolandleth** [raycast/extensions#9172] opened 2023-11-09 12:03 UTC
### Extension

https://raycast.com/raycast/apple-reminders

#### Error:
```
SwiftError
    at ChildProcess.<anonymous> (/Users/<user>/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/my-reminders.js:50:13280)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:350:12)
```

### Steps To Reproduce

Open `My Reminders` (privacy permissions granted).

### Current Behaviour

Nothing loads, error.

### Expected Behaviour

To load.

### Extra info
Creating reminders works (although lists do not load in that view).

**Comment by rolandleth** [comment] 2023-11-26 16:02
I have an extension published too, and I don't always reply in time, but the built-in (old) Reminders function worked and got deprecated in favour of this one and can not be installed anymore (or at least I can't find out how), a decent time to reply would be immensely appreciated, especially for an extension so core like this...

**Comment by thomaslombart** [comment] 2023-11-27 05:47
Hey @rolandleth, sorry for the late reply. We'll investigate this bug. Thanks for reporting the issue and for your patience! 😊

**Comment by rolandleth** [comment] 2023-12-06 09:09
Hello! Is there anything I could help with? I really miss this extension, I used to use it multiple times per day 🙁

**Comment by thomaslombart** [comment] 2023-12-21 09:33
Hey @rolandleth, we've added an update that should make the error more descriptive. Could you test it out again and let me know if you see more than `SwiftError`? If that's not the case, could you follow these instructions:
- In Raycast's root search, select a reminder command, open the action panel and then open `Show Build in Finder`
- Open `create-reminder.js` in a text editor and search for `Could not get any data`. If you can't find it, that means the extension probably hasn't been updated.

**Comment by rolandleth** [comment] 2024-01-17 09:16
Hey! Sorry for the late reply.

I just uninstalled and reinstalled it, to make sure it's the latest version, but the error is the same. I see no "Show Build in Finder" action command.

```
SwiftError: Could not get any data
    at ChildProcess.<anonymous> (/Users/roland/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/my-reminders.js:50:13560)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by ddotlic** [comment] 2024-02-02 11:09
@thomaslombart  Seeing how the "legacy" extension worked just fine and this issue isn't getting any love, would it at least be possible to get the legacy extension back?

**Comment by PSalant726** [comment] 2024-02-13 18:43
Agreed with @ddotlic. This extension is completely broken and there seems to be no timeline for a fix. Quickly adding reminders is one of my primary use cases for Raycast, so re-enabling the legacy extension should be done as a workaround until this extension can be given the attention needed to resolve this issue.

**Comment by mathieudutour** [comment] 2024-02-14 08:03
The extension isn't "completely broken" - it seems that, for a handful of users, the extension can't execute a binary to get the data from Apple's APIs. We haven't been able to reproduce nor find any pattern as to when and why it would fail.

Let's see if we can find some common points between the failing setups:
- What version of macOS are you on?
- Are you running any kind of software that would stop the execution of binaries?
- Could you try running `ls -la ~/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift` in a terminal and send the result?
- Could you try running `~/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift/AppleReminders` in a terminal and send the result?

**Comment by ddotlic** [comment] 2024-02-14 09:05
@mathieudutour I agree that framing "completely broken" is likely a personal feeling and not based in hard data (I did not make this statement BTW) but I also suspect that "handful of users" is similarly misguided - as a (professional, making a living of it) developer myself, I occasionally get user-supplied bug reports (large web site with lots of users) which when found turn out to be **years** old. Why didn't we get any other bug reports about it (again, lots of users, public site, financial industry, not something silly)? I assume because it doesn't hurt the users enough or they don't know how to file a bug report or are too busy or...

But this philosophical point aside, I am extremely happy that you've given us things to try. Here's my report:

1. I am running latest possible macOS, 14.3.1 on Apple M2 Pro (mac mini)
2. I am **not** running any kind of antivirus or such, but _this is an excellent point_, I've seen issues with overzelous antivirus many times in my career (and have just double checked that on my machine, Acronis Backup's unwanted `Protection` is completely disabled)
3. Running ls command produces `.rw-r--r--@ 904k draza 12 Feb 14:42  AppleReminders`
4. Cannot run the `AppleReminders` since it's obviously not an executable

Based on 3 and 4, I manually made the file executable running (while in the plugin folder) `chmod 755 AppleReminders` which did not help, followed by a more dangerous `chmod 777 AppleReminders` which _also_ did not help. In both cases, I did quit and reopen Raycast.

If there's anything else I could try, please LMK and I'll gladly do it. Thanks!

**Comment by ddotlic** [comment] 2024-02-14 09:13
Forgot to say: now that `AppleReminders` can be executed, when I do so I get back `Not enough Command-Line arguments`.

I tried figuring out the arguments from the `my-reminders.js` but as it's minified, it's very hard to do so.

**Comment by mathieudutour** [comment] 2024-02-14 09:15
> Running ls command produces .rw-r--r--@ 904k draza 12 Feb 14:42  AppleReminders
Cannot run the AppleReminders since it's obviously not an executable

That's interesting! Now that the file is executable, the extension still shows the same error?

The code we use to run the binary is fairly simple:
```ts
import { join } from "path";
import { chmod } from "fs/promises";
import { spawn } from "child_process";

async function runSwiftFunction(command, ...args) {
  // the path below is dynamically generated
  const swiftPath = join("~/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift/AppleReminders");
  await chmod(swiftPath, "755");

  return new Promise((resolve, reject) => {
    const commandArgs = [command];
    for (const arg of args) {
      try {
        commandArgs.push(JSON.stringify(arg, (k, v) => v === undefined ? null : v));
      } catch (err) {
        reject(new SwiftError("Failed to serialize input to JSON: " + err.message));
        return;
      }
    }
    const child = spawn(swiftPath, commandArgs);
    const stdout = [];
    const stderr = [];

    child.stdout?.on("data", (data) => {
      stdout.push(data.toString());
    });
    child.stderr?.on("data", (data) => {
      stderr.push(data.toString());
    });

    child.on("exit", (code) => {
      if (code === 0) {
        try {
          const result = stdout.join("").trim();
          if (result.length != 0) {
            resolve(JSON.parse(result));
          } else {
            resolve(null);
          }
        } catch (err) {
          const error = new SwiftError("Failed to deserialize result from JSON: " + err.message);
          error.stdout = stdout.join("").trim();
          error.stderr = stderr.join("").trim();
          reject(error);
        }
      } else {
        const error = new SwiftError(stderr.join("").trim() || stdout.join("").trim() || "Could not get any data");
        error.stdout = stdout.join("").trim();
        error.stderr = stderr.join("").trim();
        reject(error);
      }
    });

    child.on("error", (error) => {
      reject(error);
    });
  });
}

export class SwiftError extends Error {
  constructor(message) {
    super(message);
    this.name = "SwiftError";
  }
}
```

**Comment by ddotlic** [comment] 2024-02-14 09:20
> That's interesting! Now that the file is executable, the extension still shows the same error?

@mathieudutour Yes, still the same error. I noticed the `chmod` in the script, this obviously did nothing prior.

What are the arguments sent to this, when one wants to list reminders? I'd like to try executing this manually.

**Comment by mathieudutour** [comment] 2024-02-14 09:22
`~/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/assets/compiled_raycast_swift/AppleReminders getReminders` should return a big JSON

**Comment by ddotlic** [comment] 2024-02-14 09:24
> should return a big JSON

It returns `zsh: trace trap  ./AppleReminders getReminders`

I ran this from `iTerm` (latest) where it also has access to Reminders. Tried again from Apple's own `Terminal` same thing.

**Comment by mathieudutour** [comment] 2024-02-14 09:36
Oh 👀 

Could you try running the `Color Picker` extension? Do you get the same issue?

**Comment by ddotlic** [comment] 2024-02-14 09:41
> Could you try running the Color Picker extension? Do you get the same issue?

Not only does this extension **work just fine**, but I was not aware of it yet I _need_ that kind of functionality fairly often, thanks for pointing it out! 🎉

I guess this is technically not good news WRT `Reminders` extension, is there anything else I could try?

**Comment by mathieudutour** [comment] 2024-02-14 09:43
So it means that it's not something related to the swift/js bridge, but something related to the swift code itself. I'll see what we can do - but that was already a big help, thanks!

**Comment by ddotlic** [comment] 2024-02-14 09:52
@mathieudutour I am not familiar enough with Swift nor native development on a mac, though I've done decades of native development on Windows - I presume you can "catch an exception" (seems that this isn't strictly the correct term, but close enough) during the execution and then trace the details to the console? You can send me the executable without the need to publish the new version of the plugin.

Alternatively, if the source is accessible, I can try to run this in debug mode from XCode? Again, haven't done much in this regard, but "how hard could it be" 😉

**Comment by mathieudutour** [comment] 2024-02-14 09:53
The source is indeed accessible here: https://github.com/raycast/extensions/tree/main/extensions/apple-reminders/swift/AppleReminders

**Comment by thomaslombart** [comment] 2024-02-14 10:40
@ddotlic, do other commands fail for you, like `Create Reminder`? @rolandleth reported that lists couldn't be loaded in this command.

**Comment by ddotlic** [comment] 2024-02-14 10:48
OK, so I was bored and tried the good old `print debugging` - the Swift code works fine up to the line

```swift
remindersData = reminders.map { $0.toStruct() }
```

where it crashes. I tried using `try/catch` but my Swift skills are pathetic, so I got nothing.

The code is able to get necessary permission and the app does see all of my (mostly already completed) reminders (`1563` of them to be exact).

LMK if I can try something else.

Since the build is "obfuscated" by the use of wrappers over wrappers etc (not judging), I cannot figure out (yet) how to build the Swift part in debug mode.

**Comment by ddotlic** [comment] 2024-02-14 11:08
@thomaslombart Thanks for your patience. I am actually debugging like an idiot, by sprinkling `print` statements over the codebase.

Unfortunately, when I comment out the line you pointed at, the build fails. Since I'm running the build from the command line using `npm run build` what I get back is fairly useless (no details about the error).

How did you open just `AppleReminders` in XCode?

**Comment by ddotlic** [comment] 2024-02-14 11:24
@thomaslombart Duh! OK, now we're "cooking with gas" or as we Europeans should probably say "cooking with induction" 😛 

I can now debug normally - the error I had previously was when commenting out the line you indicated, I commented out the closing parenthesis 🤦‍♂️. Btw, that by itself does nothing.

The issue is index out of bounds at the most unexpected place, month index is 12 at some point, I need to debug this more to tell you more, but we're getting somewhere!

**Comment by ddotlic** [comment] 2024-02-14 12:30
@thomaslombart This appears to be a classic off-by-one: the [Apple docs](https://developer.apple.com/documentation/eventkit/ekrecurrencerule/1507449-monthsoftheyear) for the `monthsOfTheYear` state that values range from 1 to 12, where the code assumes array index, 0 to 11.

The offending line is [this one](https://github.com/raycast/extensions/blob/97fa7795eb742715f5e2c5a91dd10f36f0fea189/extensions/apple-reminders/swift/AppleReminders/Sources/EventKit%2BAdditions.swift#L105).

In theory, using `monthSymbols?[$0.intValue - 1]` should do the trick.

**Comment by thomaslombart** [comment] 2024-02-14 13:37
Oh, that's interesting. So, it means it's crashing for some recurring reminders? Could you share some of your reminders so that I can reproduce it as well?

As for the completed reminders, they're loaded upfront so that you can display them if you want (as shown below). Does it have a noticeable performance impact if you filter them out?

![apple-reminders 2024-02-14 at 14 34 35](https://github.com/raycast/extensions/assets/16003285/762e7405-08c5-4631-b0b2-694b71abd1cc)

Anyway, thanks a lot for investigating this. It's really helpful! 🙌

**Comment by ddotlic** [comment] 2024-02-14 13:44
> Could you share some of your reminders so that I can reproduce it as well?

@thomaslombart I am not sure how I would go about "sharing my own reminders" but this particular one is just a _yearly_ reminder, every 4th Friday of **December** (details unimportant). 

I thought my comments were clear - the code assumes 0 based month indices, where the Apple uses 1 based month indices, you must have seen this kind of misunderstanding a million times, no? 

My reminder being for December, its "index" is 12, out of bounds of a typical month array with 12 entries, last one having an index of 11. I pointed at the line exactly in my comment above and provided the fix - just subtract one.

**Comment by thomaslombart** [comment] 2024-02-14 14:38
I took a deeper look at that and if you run it locally, you get a much more helpful error:

```swift
SwiftError: Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
```

Instead of just:

```swift
SwiftError: Could not get any data
```

So there's two issues here. The first one is the Apple Reminders one that I'll fix in the following hours thanks to you. The second one has to do with how we're sending the errors in production. We'll follow up on that so that if we have other errors in the future, it'll be way easier to identify the cause.

Anyway, thanks again for your help. I'll ship the PR soon 🙌

**Closed** 2024-02-14 15:12 UTC
Labels: bug, extension, extension: apple-reminders

**Comment by rolandleth** [comment] 2024-03-07 09:13
Awesome, can confirm it now works, thank you!
