### ISSUE TITLE
[Spotify Player] menu bar player

### ISSUE THREAD

**Issue by lucasmpramos** [raycast/extensions#11654] opened 2024-04-05 11:41 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

My menu bar player disappears when my Mac sleeps or goes idle for some time. 

When this happens, it doesn't come back even when I'm playing a song. 

The only way I found to bring it back was going to command settings and checking/unchecking the "Hide Icon When Idle" (which refers to the Spotify icon or the Cover icon)

Thanks

### Steps To Reproduce

Make your mac go idle for some time on sleep mode

### Current Behaviour

 it doesn't come back even when I'm playing a song. 

### Expected Behaviour

should go back as soon as I play a song, automatically

**Comment by thomaslombart** [comment] 2024-05-23 12:10
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10466, so I'll mark it as such.

**Closed by thomaslombart** 2024-05-23 12:10 UTC
Labels: bug, extension, extension: spotify-player
