### ISSUE TITLE
[Jira] Highlight active sprints

### ISSUE THREAD

**Issue by FezVrasta** [raycast/extensions#4330] opened 2023-01-19 12:43 UTC
### Extension

https://www.raycast.com/raycast/jira

### Description

When I create a new ticket I usually want to assign it to the active sprint, but when I interact with the sprints dropdown there's no way to know which one is the active one.

On Jira, the dropdown automatically displays the active sprint on top.

<img width="427" alt="CleanShot 2023-01-19 at 1 41 44@2x" src="https://user-images.githubusercontent.com/5382443/213445645-3bf26a8f-f062-49c6-aee0-7176c9734f79.png">

I'd like to see the same behavior on the Raycast extension.

**Comment by thomaspaulmann** [comment] 2023-01-26 12:23
@thomaslombart This sounds like something to consider when we rebuilding the Create Issue screen.

**Comment by thomaslombart** [comment] 2023-02-01 13:58
Unfortunately, the [endpoint used to retrieve sprints](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-autocompletedata-post) doesn't give any additional information about them. Unless I've missed an API giving more details about a sprint, it's not possible to know whether a sprint is active or not.

**Comment by thomaslombart** [comment] 2023-02-01 14:32
It's not so simple because we're using the [Jira Cloud Platform REST API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/) under the hood, which has a URL like the following: `https://api.atlassian.com/ex/jira/<cloudId>/rest/api/3/<resource-name>` which doesn't seem to support the path you linked above. 

We could use another API like the [Jira Software Cloud REST API](https://developer.atlassian.com/cloud/jira/software/rest/intro/#introduction), which has a set of [endpoints for sprints](https://developer.atlassian.com/cloud/jira/software/rest/api-group-sprint/#api-group-sprint). But, it's not possible to call them for on-premise integrations (which is our case):

> If you are integrating an on-premises app with the Jira REST APIs, API calls are authenticated via an OAuth token. To obtain a token, create a set of OAuth credentials with permissions for the APIs that app needs to access. Use the credentials to request a token by calling https://api.atlassian.com/oauth/token. See [Integrating Jira Software Cloud with on-premises tools](https://developer.atlassian.com/cloud/jira/software/integrate-jsw-cloud-with-onpremises-tools/) for details. Note that only the [Development Information](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Development-Information), [Builds](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Builds), and [Deployments](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Deployments) APIs are currently available for on-premises integrations. To simplify development, we have a separate [downloadable API spec](https://developer.atlassian.com/cloud/jira/software/on-premise-swagger.json).

(this quote comes from the [docs](https://developer.atlassian.com/cloud/jira/software/rest/intro/#introduction))

**Comment by FezVrasta** [comment] 2023-02-02 12:46
Maybe a good enough workaround could be to highlight the latest sprint? (the one with the highest number)

**Comment by FezVrasta** [comment] 2023-02-02 12:49
I also see the API you are using should support parsing custom JQL queries, do you think you could use it to run the query that I provided above?

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql/#api-rest-api-3-jql-parse-post

```
sprint IN openSprints() AND sprint NOT IN futureSprints() AND sprint NOT IN closedSprints()
```

**Comment by thomaslombart** [comment] 2023-02-02 15:18
Plot twist: after investigating, I could use Jira Software Cloud APIs for OAuth applications! It turns out it's possible to use these APIs for many months now (cf [this post](https://community.developer.atlassian.com/t/how-to-get-all-the-sprint-information-using-oauth-2-0-3lo-apps/56088/4)).

Only active and future sprints are returned knowing that the state is in between parenthesis:

<img width="745" alt="CleanShot 2023-02-02 at 16 17 37@2x" src="https://user-images.githubusercontent.com/16003285/216364595-988e4b81-f959-468f-848e-fe141a2633cb.png">

Does this fit your use-case?

**Comment by FezVrasta** [comment] 2023-02-02 15:32
Looks great! Will they show at the top? If not, can I type `Tableau active` to find it?

**Comment by thomaslombart** [comment] 2023-02-02 15:50
Yes, let's put them at the top, it makes more sense! Typing `Tableau active` should work as well.

Note that this feature will land on the open-source Jira extension that should be released in the next few weeks. The native one will be deprecated afterward. Sorry in advance for the delay 🙇

**Comment by thomaslombart** [comment] 2023-02-27 14:50
Hey @FezVrasta, the Jira extension is now [open-sourced](https://github.com/raycast/extensions/tree/main/extensions/jira) and in beta. You can install it from the store: https://www.raycast.com/raycast/jira-beta. 

This should fix your issue, so I'll close it. Feel free to reach out or open new issues if something goes wrong.

**Closed by thomaslombart** 2023-02-27 14:50 UTC
Labels: feature request, extension, Dont close

**Comment by thomaslombart** [comment] 2023-03-02 11:32
Hey @FezVrasta, I've been looking at your sprint problem. For reference, here's the file responsible for retrieving the sprints in the `Create Issue` command: https://github.com/raycast/extensions/blob/main/extensions/jira/src/components/FormSprintDropdown.tsx

I get why typing `active` doesn't work. The [endpoint used to retrieve sprints](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-jql#api-rest-api-3-jql-autocompletedata-suggestions-get) is made for retrieving autocomplete suggestions for any search field. Since the sprint's status is actually something we construct on our end (after retrieving the values) after getting the sprints, searching by status won't work.

However, you should be able to get at least some sprints. Here are my questions:
- Do you have a lot of sprints in Jira?
- Were you able to get sprints in the previous extension?

**Comment by FezVrasta** [comment] 2023-03-02 16:43
I was able to get sprints in the previous version, we have 80 sprints across 3 or 4 teams.

**Comment by thomaslombart** [comment] 2023-03-09 14:07
I pushed some changes to the sprints. Now, the active sprints are shown first, followed by the future ones, and then the closed ones. I also removed some filtering, which may fix your issue (though I'm not sure; I couldn't reproduce the issue, so it's kind of hard to debug it knowing the native extension has similar code). Could you please try again?

**Comment by FezVrasta** [comment] 2023-03-09 14:11
Now if I search for EN Sprint 81 it returns a result, thanks! But I only see (future) and (closed) issues when I open the dropdown without typing anything, the active sprint is not displayed.

**Comment by thomaslombart** [comment] 2023-03-13 14:46
Are you seeing other active sprints?

**Comment by FezVrasta** [comment] 2023-03-13 15:41
No, only future and closed ones.

![CleanShot 2023-03-13 at 4 41 27@2x](https://user-images.githubusercontent.com/5382443/224752520-f5e0ad62-5ccd-42c4-bf2e-ebaa82d2d870.png)

**Comment by thomaslombart** [comment] 2023-03-21 10:28
I may have a clue about what's happening here. The default request sent in the previous extension and the beta extension is the exact same by default (`https://api.atlassian.com/ex/jira/${cloudId}/rest/api/3/jql/autocompletedata/suggestions?fieldName=Sprint&fieldValue=sprint`) so the results returned should be the same.

Here are the results for the native one:

![CleanShot 2023-03-21 at 11 21 06@2x](https://user-images.githubusercontent.com/16003285/226578307-238f8740-3464-43fc-b9ee-dfe0c8e9da53.png)

Here are the results for the beta extension:

<img width="1265" alt="CleanShot 2023-03-21 at 11 24 14@2x" src="https://user-images.githubusercontent.com/16003285/226578647-fdeaf607-9e96-4356-8442-262a0fa710a7.png">

However, we're fetching additional info for each sprint in the beta extension. If the call fails, `null` is returned. To verify that, I'll revert the sprint state changes.

**Comment by FezVrasta** [comment] 2023-03-21 11:50
I can also try to run the query on CURL with my own token if you provide it to me.

**Comment by thomaslombart** [comment] 2023-03-21 14:32
The changes have been deployed. Can you let me know if you're able to search for the sprints you couldn't find before? Note that there's no longer the active/future/closed indicator.

If you want to run the query yourself, here it is: `https://api.atlassian.com/ex/jira/a92ec49f-0250-45bb-a456-fee741b3e76/rest/api/3/jql/autocompletedata/suggestions?fieldName-Sprint&fieldValue=sprint`

**Comment by FezVrasta** [comment] 2023-03-21 14:52
The search was working, the problem were the pre populated entries that show up when the dropdown is open. As you could see from the screenshot, the (active) sprints where not displayed in there.
