### ISSUE TITLE
[GitHub] Add repository reference to the `Unread Notifications` Menu Bar Command

### ISSUE THREAD

**Issue by xilopaint** [raycast/extensions#7536] opened 2023-07-17 22:00 UTC
### Extension

https://www.raycast.com/raycast/github

### Description

<img width="316" alt="Screenshot 2023-07-17 at 03 54 25" src="https://github.com/raycast/extensions/assets/11052366/2a3f21ee-8f7b-4d5b-bb73-18737523e679">

As you can see above, there's no way to identify the repository related to the notification before we click on it, so it would be useful to reference the repository as we have on the GitHub notification page:

![Screenshot 2023-07-17 at 18 55 10](https://github.com/raycast/extensions/assets/11052366/b153b67f-6d7a-4928-aceb-128b607af3f2)

### Who will benefit from this feature?

All extension users.

**Comment by thomaslombart** [comment] 2023-07-18 06:19
Thanks for bringing this up. It appears that this is a duplicate of issue #7301, so I'll mark it as such.

**Closed by thomaslombart** 2023-07-18 06:19 UTC
Labels: feature request, extension, extension: github
