### ISSUE TITLE
[Jira Search] Invalid Query: Unknown project or Issue Type

### ISSUE THREAD

**Issue by argishteghazaryan** [raycast/extensions#4465] opened 2023-01-27 06:38 UTC
### Extension

https://www.raycast.com/sven/jira-search

### Description

Hi,

Since a few weeks, I can no longer "text" search Jira tickets when using the Jira Search extension.
Although recent tickets show up when first opening the "Search Issues" command, it results in an error as soon as I start typing text: 
Invalid Query: Unknown project or Issue Type

Can someone please help?

**Comment by svenwiegand** [comment] 2023-02-15 08:58
Sorry for the late reply here. I cannot reproduce this issue. I'm using the search several times a day and for me, it is still working flawlessly. 

My first guess was an expired login, but then you shouldn't even see the most recently used issues.

@argishteghazaryan Any further hints?

**Comment by svenwiegand** [comment] 2023-03-22 09:09
Now I can confirm the problem: I had an old version of the extension on my disk.

@itsrifat This issue occurs, since your changes have been merged. Maybe you want to take a look at this too?

**Closed** 2023-03-22 11:13 UTC
Labels: bug, extension, extension: jira-search
