### ISSUE TITLE
[Spotify Player] Menu Bar Player's "Hide icon when idle" feature is broken

### ISSUE THREAD

**Issue by TaroMilky** [raycast/extensions#13935] opened 2024-08-09 00:58 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.80.0

### macOS Version

14.6.1

### Description

The hide when idle feature either doesn't show the menu bar player at all, or doesn't remove it when Spotify is fully quit. 

### Steps To Reproduce

1. Turn on "hide icon when idle"
2. Open Spotify and play a track
3. observe menu bar player

**Comment by thomaslombart** [comment] 2024-08-09 07:31
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10466, so I'll mark it as such.

**Closed by thomaslombart** 2024-08-09 07:31 UTC
Labels: bug, extension, extension: spotify-player
