### ISSUE TITLE
[Todoist] Please bring back "Search Tasks"

### ISSUE THREAD

**Issue by stevensoekha** [raycast/extensions#6690] opened 2023-05-20 11:02 UTC
### Extension

https://www.raycast.com/doist/todoist

### Description

I don't understand why you'd remove the search tasks feature? I used it heavily to search through my 100+ tickets. All of a sudden this feature is gone :(

I see there's a "Home" feature, which I really dislike, it's preselected on "Today" which is already a bad thing. I now need to click "All Tasks" before being able to perform a search. Also when I try to search I'm getting a 502 back, so it doesn't work for me at all.

Please bring back the search through task feature, so I can instantly find a specific task.

### Who will benefit from this feature?

Everyone.

### Anything else?

![CleanShot 2023-05-20 at 13 01 32](https://github.com/raycast/extensions/assets/36703601/2f4c0a51-7bab-4e4e-b1f9-0f7e878c9996)

**Comment by stevensoekha** [comment] 2023-05-21 18:32
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20

**Comment by thomaslombart** [comment] 2023-05-23 07:39
Hey @stevensoekha, the new `Home` command replaced `Today Tasks`, `Upcoming Tasks`, `Search Tasks` and `Completed Tasks` for a cleaner experience as the extension is less bloated with commands. You can still have a quick-access to your favorite views (`All tasks` for example) by creating a new quicklink though: https://github.com/raycast/extensions/blob/main/extensions/todoist/README.md#create-tasks-view

Note that this feature also allows you to quickly access a certain project or label which wasn't possible before with the extension.

**Comment by thomaslombart** [comment] 2023-05-23 07:39
For the `JS heap out of memory` error, you can track the issue here: #6562.

**Comment by thomaslombart** [comment] 2023-05-23 07:40
So, I'll close this issue as it's a duplicate of another one and that you can re-create `Search Tasks` on your own 😊

**Closed by thomaslombart** 2023-05-23 07:40 UTC
Labels: feature request, extension, extension: todoist

**Comment by thomaslombart** [comment] 2023-06-02 08:58
Hey @stevensoekha, you can now search for all your tasks again using the new `Search` command of the Todoist extension. See #6908.

**Comment by stevensoekha** [comment] 2023-06-04 09:50
@thomaslombart Nicee! Please don't ever remove it again 😰
Thank you very much!
