### ISSUE TITLE
Spotify Player - put this song into playlist {Query}

### ISSUE THREAD

**Issue by reorganice** [raycast/extensions#10322] opened 2024-01-24 21:21 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Description

It would be cool to have this command
…  and a follow up on what playlist to put current song in …

… since spotify united the like with songs beeing in a playlist.

Thank you <3

### Who will benefit from this feature?

everybody who makes playlists

**Comment by the-devbear** [comment] 2024-02-28 13:30
I recently add a new command `Add Playing Song to Playlist` in this PR: #9438.
Is that what you had in mind? If so you can activate it in the settings since it's not initially active.

**Comment by the-devbear** [comment] 2024-03-11 19:34
I couldn't reproduce it. Sorry! But can open a bug ticket and I'll close this one if its fine with you

**Comment by reorganice** [comment] 2024-03-15 23:30
Yes it's all good. Thanks!

**Comment by the-devbear** [comment] 2024-03-16 14:44
@raycastbot close this issue

**Closed** 2024-03-16 14:44 UTC
Labels: feature request, extension, extension: spotify-player
