### ISSUE TITLE
[Todoist] Menu task bar keeps erroring

### ISSUE THREAD

**Issue by RCheesley** [raycast/extensions#14083] opened 2024-08-19 13:27 UTC
### Extension

https://www.raycast.com/doist/todoist

### Raycast Version

1.81.0

### macOS Version

14.5

#### Error:

I'm not quite sure why, but very frequently my Todoist tasks menu bar turns into a triangle in the menu bar, and the tasks are not loaded:

![screenshot-nimbusweb me-2024 08 19-14_22_38](https://github.com/user-attachments/assets/f775f9d2-24a7-47b7-a9e2-28a7b5a17d15)

### Steps To Reproduce

I'm not really sure because it just doesn't load the tasks and won't load them again until I clear cache + reload. I will try to see if I can notice it when it next and if someone can point me where to check, find some log files. I've been through this process at least 5-10 times: If I clear the cache and then reload, it works for a short time and then stops again: https://app.screencastify.com/v3/watch/e1psOpeXxifSXD0gEgL7

### Current Behaviour

Red triangle, tasks not loaded until I clear cache + reload.

### Expected Behaviour

Should show tasks at all times.

**Comment by thomaslombart** [comment] 2024-08-20 11:40
Could you copy the error and paste it here? I think it has to do with loading too many tasks but want to double check first.

**Comment by RCheesley** [comment] 2024-08-20 17:02
Hey there!

Could you guide me on where to find the error? All I see is the menu bar going red and angry, I've never actually seen any error messages.

**Comment by thomaslombart** [comment] 2024-08-21 08:11
In the screencast you send, there's an action called `Copy Error` that allows you to get the stack trace 🙂

**Comment by thomaslombart** [comment] 2024-08-21 12:52
Thanks! It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10127, so I'll mark it as such.

**Closed by thomaslombart** 2024-08-21 12:52 UTC
Labels: bug, extension, extension: todoist
