### ISSUE TITLE
[iMessage 2FA] Delete Message after Copy

### ISSUE THREAD

**Issue by anthonygiuliano** [raycast/extensions#10794] opened 2024-02-16 21:24 UTC
### Extension

https://www.raycast.com/yuercl/imessage-2fa

### Description

It'd be nice if there were a preference that enabled automatically deleting the message containing the 2FA code after using it.

### Who will benefit from this feature?

iPhone users that have become accustomed to this functionality

### Anything else?

Similar to a recent [setting](https://support.apple.com/guide/iphone/automatically-fill-in-verification-codes-ipha6173c19f/ios#:~:text=Automatically%20delete%20one%2Dtime%20verification%20codes&text=You%20can%20choose%20to%20automatically,Up%20Automatically%20on%20or%20off.) added by Apple

**Comment by navtoj** [comment] 2024-02-18 09:11
Duplicate of #9838

**Comment by navtoj** [comment] 2024-02-18 09:11
@raycastbot close this issue

**Closed** 2024-02-18 09:11 UTC
Labels: feature request, extension, extension: imessage-2fa
