### ISSUE TITLE
[Simple Youdao Translate] Fail to read words.

### ISSUE THREAD

**Issue by hongzzz** [raycast/extensions#5366] opened 2023-03-15 08:43 UTC
### Extension

https://www.raycast.com/xeric/simple-youdao

#### Error:
```
Error: Command failed: afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1
Error: AudioFileOpen failed ('dta?')


Error: AudioFileOpen failed ('dta?')
ChildProcess.exithandler:node:child_process:412:12
ChildProcess.emit:node:events:513:28
```

**Comment by xeric** [comment] 2023-03-20 06:38
Hi @hongzzz 
Thanks for reporting the issue, does this issue happened recently or it never works?
Could you help to check below?

1. visit http://dict.youdao.com/dictvoice?audio=test, check if there's any connectivity issue, if works, check next one. 
2. if file '/tmp/tmp_raycast_simpleyd.mp3' is existing, if yes, check next one.
3. please help to run cmd `afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1` from your terminal.

The actual process of pronunciation is downloading the audio file and use afplay command to play it.
I tested it locally, works fine, I need to understand if the problem in your side is in download phase or command execution phase.

**Comment by hongzzz** [comment] 2023-03-20 14:05
> Hi @hongzzz Thanks for reporting the issue, does this issue happened recently or it never works? Could you help to check below?
> 
> 1. visit http://dict.youdao.com/dictvoice?audio=test, check if there's any connectivity issue, if works, check next one.
> 2. if file '/tmp/tmp_raycast_simpleyd.mp3' is existing, if yes, check next one.
> 3. please help to run cmd `afplay "/tmp/tmp_raycast_simpleyd.mp3" -v 1` from your terminal.
> 
> The actual process of pronunciation is downloading the audio file and use afplay command to play it. I tested it locally, works fine, I need to understand if the problem in your side is in download phase or command execution phase.

Hey @xeric , I tried that both 1 and 2 were successful. But for 3, it can not be played. 

Here is screenshot.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/25585061/226363029-46544920-a9c5-4595-8e18-3d4b62ba6ec1.png">

And I tried to open the file via IINA and Quicktime player, also failed
<img width="640" alt="image" src="https://user-images.githubusercontent.com/25585061/226364206-fa6aa514-ce51-467d-a02a-8fa45b6d8749.png">

**Comment by xeric** [comment] 2023-03-20 15:56
Thanks for your information!
your browser can access the audio file, but when the file downloaded, it could not be openned.
What is the size of this mp3 file? If it is not zero size, would you mind to upload this local mp3 file to somewhere for my investigation?

**Comment by xeric** [comment] 2023-03-21 03:19
@hongzzz yes, I feel there's something wrong with your youdao audio url accessing, but you said it works fine in your browser, right? If yes, means the behavior in browser and in Raycast they are different, did you setup any proxy or special DNS for your Raycast? or your browser has setup some proxy or DNS to make it work?
Or can you try it in different network environment?

**Comment by hongzzz** [comment] 2023-03-21 04:17
Raycast is the same network env with my browser.

**Comment by hongzzz** [comment] 2023-03-21 15:43
@xeric Thanks for your help. I just discovered the issue - I had not turned on the TTS function, which resulted in error code 110.

https://ai.youdao.com/DOCSIRMA/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%9C%89%E9%81%93%E8%AF%8D%E5%85%B8%E6%9C%8D%E5%8A%A1/%E6%9C%89%E9%81%93%E8%AF%8D%E5%85%B8%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html

**Comment by xeric** [comment] 2023-03-21 17:13
oh, I see, I did not realize that the audio file is from the pronunciation link of API, I thought your case would run into fallback url, thanks for your feedback and glad to see it turn to work now.

**Comment by xeric** [comment] 2023-03-21 17:16
@raycastbot I think you can close this ticket due to root cause found by ticket opener

**Closed** 2023-03-22 14:37 UTC
Labels: bug, extension, extension: simple-youdao
