### ISSUE TITLE
[Apple Reminders] - Quick AI Reminder Creation Defaults to Wrong List

### ISSUE THREAD

**Issue by silvaMatheus** [raycast/extensions#15063] opened 2024-10-24 11:24 UTC
### Extension

https://www.raycast.com/raycast/apple-reminders

### Raycast Version

1.84.3

### macOS Version

Version 15.0.1 (24A348)

### Description

When using the Quick AI Reminder Creation feature in Raycast, the reminder is always sent to the default list, even when specifying a different list in the command.

I followed the steps outlined in the Raycast documentation but encountered this issue consistently.

### Steps To Reproduce

Steps to Reproduce:
Create a list called "Work" in the Apple Reminders app.
Use the following command with the Quick AI feature in Raycast:
"Send the weekly project status report Friday at 2 PM in the Work list."
The reminder is created, but it is placed in the default list instead of the "Work" list.

### Current Behaviour

The reminder is created in the default list, ignoring the specified list in the command.

### Expected Behaviour

The reminder should be created in the Work list, as specified in the command.

**Comment by thomaslombart** [comment] 2024-10-24 12:56
Could you give me the prompts you used, as well as the list name you want to add the reminder to?

**Comment by silvaMatheus** [comment] 2024-10-27 13:24
Prompt: update github in list Dolarame 

List name: Dolarame

<img width="412" alt="Screenshot 2024-10-27 at 10 23 49" src="https://github.com/user-attachments/assets/e010b8cd-8a10-4b92-8848-2d643afe26c4">

**Comment by thomaslombart** [comment] 2024-10-28 09:51
I can't reproduce it with your prompt and your list name, mine seems to work. Do you have Raycast Pro? The AI works only for pro users.

**Comment by thomaslombart** [comment] 2024-11-22 10:09
I'm closing this issue to maintain a clean backlog. Feel free to comment it if you still have the problem.

**Closed by thomaslombart** 2024-11-22 10:09 UTC
Labels: bug, extension, extension: apple-reminders
