### ISSUE TITLE
[Spotify Player] keeps disconnecting from Spotify API

### ISSUE THREAD

**Issue by lucasmpramos** [raycast/extensions#11666] opened 2024-04-05 20:01 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

#### Error:
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ke (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6250)\n    at pt (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6375)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6140)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-04-05T19:59:39.809Z","data":{"function":"getApplications"}}]}: 


```

### Steps To Reproduce

it just happens randomly. 3 times since yesterday, when I started using. 

I got it disconnected twice today while being active on my computer. 2-3 hours apart each

**Comment by moisesrodriguez** [comment] 2024-04-09 22:16
I have the same issue

Logs
```
{"_isRayError":true,"code":16,"title":"Could not initialize OAuth","name":"Error","message":"OAuth request creation is not available when command is launched in background","stack":"Error: OAuth request creation is not available when command is launched in background\n    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)\n    at Ke (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6250)\n    at pt (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6375)\n    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6140)\n    at process.processImmediate (node:internal/timers:478:21)","breadcrumbs":[{"level":"debug","category":"Request","message":"","timestamp":"2024-04-09T22:14:27.064Z","data":{"function":"getApplications"}}]}: 
```

**Comment by lucasmpramos** [comment] 2024-05-07 18:42
no one?

**Comment by thomaslombart** [comment] 2024-05-23 12:21
Thank you for the report. This issue has been occurring for other users too. We will look into it.

**Comment by thomaslombart** [comment] 2024-07-18 09:29
After reviewing it again, it appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-18 09:30 UTC
Labels: bug, extension, status: stalled, extension: spotify-player
