### ISSUE TITLE
[Browser Bookmarks] Sometimes Favicons show up as generic link icon

### ISSUE THREAD

**Issue by xenostar** [raycast/extensions#8568] opened 2023-09-25 20:12 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Description

Some results from my bookmarks show up with a generic link icon instead of the Favicon for the website. At first I thought this might be because the website required you to log in, but there are other results in my bookmarks that also require a login and yet I still see the Favicons for those bookmarks when using Raycast.

### Steps To Reproduce

1. Open Raycast
2. Search your browser bookmarks
3. Some results have a generic 🔗 Favicon instead of the actual Favicon from the bookmark/website.

In my particular case, I was getting issues with https://app.ynab.com/ while logged in (I have it bookmarked).

### Current Behaviour

Bookmark result shows up with generic 🔗 icon instead of the appropriate Favicon, even though the Favicon is correctly showing in my bookmarks within Chrome.

### Expected Behaviour

Should show the correct Favicon for the bookmark/website in the Raycast search results.

**Comment by thomaslombart** [comment] 2023-09-26 08:06
Thanks for bringing this up. It appears that this is a duplicate of issue #6590, so I'll mark it as such.

**Closed by thomaslombart** 2023-09-26 08:06 UTC
Labels: bug, extension, extension: browser-bookmarks
