### ISSUE TITLE
[Google Chrome] Update fuzzy search to allow for less precise input

### ISSUE THREAD

**Issue by forsythetony** [raycast/extensions#6907] opened 2023-06-02 02:00 UTC
### Extension

https://www.raycast.com/Codely/google-chrome

### Description

Add the ability to modify the search algorithm used for searching (primarily an issue with bookmarks) to be more in line with the behavior of tools like [fzf](https://github.com/junegunn/fzf).

## Current Behavior

I currently have a bookmark named `Jira - Mine 📍(Chewy) [AP1]`. When I begin typing `jira` I see it pop up in the list:

<img width="751" alt="image" src="https://github.com/raycast/extensions/assets/5825210/f776e8f9-4a2f-486d-b5f5-245e02833c76">

I'm expecting that when I continue with typing ` mine` it would resolve to the bookmark but it doesn't seem to match. 

<img width="749" alt="image" src="https://github.com/raycast/extensions/assets/5825210/31cb2e45-7155-4d6b-b3a5-0709beee444d">

## Expected Behavior

A quick test with [fzf](https://github.com/junegunn/fzf) on the command line shows the expected behavior. 

With the following in `test_files.txt`:

```plaintext
Jira - Mine 📍(Chewy) [AP1]
testbookmark 3
someOtherBookmark
```

and running the following command `cat test_files.txt | fzf` we can resolve the bookmark name with just `jira mine`.

<img width="236" alt="image" src="https://github.com/raycast/extensions/assets/5825210/be982526-de67-46c4-99f2-c7d502e82726">

### Who will benefit from this feature?

All users searching for bookmarks (and potentially tabs). This would allow them to get better results without have to specify search terms in the exact order.

**Comment by leeoniya** [comment] 2023-06-02 16:01
dupe of https://github.com/raycast/extensions/issues/4175?

**Comment by forsythetony** [comment] 2023-06-03 17:39
I don't think they're duplicates but I do believe they are related to the same root issue (which is that Raycasts default filtering is, in my opinion, broken). 

A fix for this could be implemented by using custom [filtering logic](https://developers.raycast.com/api-reference/user-interface/list#custom-filtering). I could try taking a look ath this later.

**Closed** 2023-08-02 19:03 UTC
Labels: feature request, extension, status: stalled, extension: google-chrome
