### ISSUE TITLE
[Messages] Fails with JS heap out of memory error

### ISSUE THREAD

**Issue by coopr** [raycast/extensions#14708] opened 2024-09-29 00:15 UTC
### Extension

https://www.raycast.com/thomaslombart/messages

### Raycast Version

1.83.1

### macOS Version

15.0

### Description

Likely related to https://github.com/raycast/extensions/issues/10127#issuecomment-2104485073 

Error: Worker terminated due to reaching memory limit: JS heap out of memory

[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20

### Steps To Reproduce

1. Open Raycast
2. Invoke "Send Message"
3. Start writing message
4. Get "Something went wrong" error

"Clear Local Storage & Cache" does not address the issue - it returns right away.

I have nearly 9,000 contacts - that might have something to do with this error?

### Current Behaviour

"Something went wrong" error

### Expected Behaviour

Message sends

**Comment by thomaslombart** [comment] 2024-09-30 06:32
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/10381, so I'll mark it as such.

**Closed by thomaslombart** 2024-09-30 06:32 UTC
Labels: bug, extension, extension: messages
