### ISSUE TITLE
Wikipedia: Something is wrong

### ISSUE THREAD

**Issue by thomaspaulmann** [raycast/extensions#940] opened 2022-02-18 18:50 UTC
# Extension – [Wikipedia](https://github.com/raycast/extensions/tree/574faa53c231901450838d547a53b5e5f6e25ed3/extensions/wikipedia/)
Author: @vimtor

## Error:
```

```

## Steps To Reproduce

1. Open the Random Page command
2. Raycast closes, nothing happens, if you toggle Raycat you see an error screen

### Raycast version
Version: 1.29.0-alpha.16

**Comment by fe9lix** [comment] 2022-02-21 08:26
@thomaspaulmann I've reported this before, closing because most likely a duplicate of: https://github.com/raycast/extensions/issues/828

**Closed by fe9lix** 2022-02-21 08:26 UTC
Labels: bug, extension
