### ISSUE TITLE
[Easy Dictionary] ...

### ISSUE THREAD

**Issue by passos** [raycast/extensions#2966] opened 2022-09-21 00:24 UTC
# Extension – [Easy Dictionary](https://github.com/raycast/extensions/tree/8538d44b79393334d742b465b9088618184c60ea/extensions/easydict/)
Author: @tisfeng

## Description

it shows "something went wrong" when use "search word"

## Error:
```
Error: write EPROTO 6171078656:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:


__node_internal_captureLargerStackTrace:errors:464:5
__node_internal_errnoException:errors:594:12
WriteWrap.onWriteComplete:stream_base_commons:98:16
```

## Steps To Reproduce

1. install the extension
2. open raycast to "search word", press tab

## The current behavior
it shows "something went wrong"

## The expected behavior
ready to input the word to search

### Raycast version
Version: 1.39.3

**Comment by tisfeng** [comment] 2022-09-21 01:42
@passos  Does it show this error every time you enter the extension?  

What is your mac and system version? Did you turn on `Use System Proxy` option?

**Comment by passos** [comment] 2022-09-21 02:35
> @passos  Does it show this error every time you enter the extension?  
> 
> 
> 
> What is your mac and system version? Did you turn on `Use System Proxy` option?

Yes. It happens every time I enter the extension. I tried turn on and off system proxy, also tried tured off all the third party interfaces and only kept Apple dictionary. It   still crash. 

My system is macOS Monterey with latest updates.

**Comment by tisfeng** [comment] 2022-09-21 03:13
OK, thank for your feedback, I'll look into it.

**Comment by tisfeng** [comment] 2022-09-21 16:04
Hi, I tried several times but could not reproduce the problem you mentioned, in fact, I have not encountered this strange problem since developing this extension.

I did a brief search and it seems that the problem is related to network openssl, which means it might be related to the network environment you are using, but I am not sure, I need more information to make a judgment.

https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number ,

https://github.com/openssl/openssl/issues/18291

**Comment by tisfeng** [comment] 2022-09-21 16:15
Have you encountered this problem with other extensions? As stated earlier, I'm not sure if it's a problem with my extension code or the main program Raycast.

If it's just `Easydict` that has the problem, if it's convenient for you, you can download and install another version, such as the original one https://github.com/tisfeng/Raycast-Easydict/releases/tag/1.1.0 , and see if it still has the problem.

If there is no problem with this version, it is likely that the problem is caused by my later introduction, and I will carefully troubleshoot it later.

**Comment by passos** [comment] 2022-09-23 02:16
Just noticed that this issue is duplicated with #2381 , pls refer to the reply at https://github.com/raycast/extensions/issues/2381#issuecomment-1255669078

**Comment by tisfeng** [comment] 2022-09-23 14:20
If it is confirmed to be a duplication issue, please close it.

**Closed** 2022-09-26 08:45 UTC
Labels: bug, extension
