### ISSUE TITLE
[Spotify Player] Frequently Loses Authorization

### ISSUE THREAD

**Issue by johnshafto** [raycast/extensions#12681] opened 2024-05-31 01:16 UTC
### Extension

https://www.raycast.com/mattisssa/spotify-player

### Raycast Version

1.75.2

### macOS Version

14.1.1

### Description

The Spotify Player extension frequently (multiple times a day) loses its authorization and needs to be re-authorized.

### Steps To Reproduce

1. Use the Spotify Player extension with the menubar now playing item enabled.
2. Notice the little red triangle in the menu bar.
3. Click it and get asked to reauthorize.
4. Reauthorize.
5. Repeat.

### Current Behaviour

Loses authorization randomly.

### Expected Behaviour

Maintain authorization status indefinitely.

**Comment by erics118** [comment] 2024-05-31 01:20
See #11666 and #9988

**Comment by thomaslombart** [comment] 2024-07-03 08:44
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/9988, so I'll mark it as such.

**Closed by thomaslombart** 2024-07-03 08:44 UTC
Labels: bug, extension, extension: spotify-player
