### ISSUE TITLE
[GitHub] Better PR search

### ISSUE THREAD

**Issue by konsalex** [raycast/extensions#7304] opened 2023-06-28 14:23 UTC
### Description

Current PR search is only finding my PRs, while it would be really nice to find PRs open in the repositories I am being involved as administrator.

<img width="740" alt="CleanShot 2023-06-28 at 16 20 02@2x" src="https://github.com/raycast/extensions/assets/12672541/4207eec4-38e3-4188-94e4-d267d9099ee1">

### Who will benefit from this feature?

GitHub users, who manage repositories. I would love to see a list of PRs I probably want to visit and review.

Maybe a reviewer list would be great here. Not sure about the ideal flow.

**Comment by thomaslombart** [comment] 2023-07-12 14:09
Thanks for bringing this up. It appears that this is a duplicate of issue #4058, so I'll mark it as such.

**Closed by thomaslombart** 2023-07-12 14:09 UTC
Labels: feature request, extension, extension: github
