### ISSUE TITLE
[Todoist] ...

### ISSUE THREAD

**Issue by smorin** [raycast/extensions#6589] opened 2023-05-16 16:33 UTC
### Extension

https://www.raycast.com/doist/todoist

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:393:5
[kOnExit]:worker:277:26
Worker.<computed>.onexit:worker:199:20
```

### Steps To Reproduce

1) Click Show projects 
2) Hit return on a selected project

### Current Behaviour

Says there is an error

### Expected Behaviour

Show a list of tasks

**Comment by thomaslombart** [comment] 2023-05-16 20:15
Thanks for bringing this up. It appears that this is a duplicate of issue #6562, so I'll mark it as such.

**Closed by thomaslombart** 2023-05-16 20:15 UTC
Labels: bug, extension, extension: todoist
