### ISSUE TITLE
Unable to add music to library, love function works fine[Music]: 

### ISSUE THREAD

**Issue by LeoLee53** [raycast/extensions#5395] opened 2023-03-16 04:00 UTC
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to duplicate current track to source 1 
28:63: execution error: Music got an error: Can’t set source 1 to current track. (-10006)

**Comment by Rawnly** [comment] 2023-03-16 08:10
Duplicate of #5344, in already working on this, ho to fix this soon

**Comment by Rawnly** [comment] 2023-04-08 23:51
@raycastbot close this issue

**Closed** 2023-04-08 23:52 UTC
Labels: bug, extension, extension: music
