### ISSUE TITLE
[Apple Reminders] Problem with tasks dates off by one day

### ISSUE THREAD

**Issue by fturcheti** [raycast/extensions#9782] opened 2023-12-19 17:30 UTC
### Extension

http://www.raycast.com/raycast/apple-reminders

### Description

I have several tasks assigned for today (but without an specific time) in a list. In the screenshot you can already see that something is wrong because the tasks set for today appear as "1d":
![CleanShot 2023-12-19 at 14 24 01@2x](https://github.com/raycast/extensions/assets/365403/58238e3e-0e1f-4a71-ab63-4858ade9e532)

None of these tasks set for today appear in the Today list of the extension, and a recurring task set for tomorrow appear as it was for today (the one with "6h":
![CleanShot 2023-12-19 at 14 16 39@2x](https://github.com/raycast/extensions/assets/365403/4285444d-3146-441a-a9e3-84b6e6e6d975)

Although they appear in Today's list in Reminders:
![CleanShot 2023-12-19 at 14 21 40@2x](https://github.com/raycast/extensions/assets/365403/83451995-d670-49c0-9824-d0fa6443008e)

### Steps To Reproduce

1. Create a task and set it for today without specifying a time
2. The task appears in Reminders app Today list
3. The task doesn't appear in the extension Today list and appears to be treated as if is was set for tomorrow

**Comment by fturcheti** [comment] 2023-12-22 17:57
> We could not find the extension related to this issue. Please update the issue with the link to the extension.

This is a bug. The link to the extension was added automatically and is correct: http://www.raycast.com/raycast/apple-reminders.

**Comment by fturcheti** [comment] 2023-12-22 18:04
@thomaslombart Can you take a look at this? Sorry, I'm not pressing you, but I'm afraid this wrongly applied "stalled" label will make you ignore the issue.

**Comment by thomaslombart** [comment] 2023-12-26 15:52
Thanks for bringing this up. It appears that this is a duplicate of issue #9507, so I'll mark it as such.

**Closed by thomaslombart** 2023-12-26 15:52 UTC
Labels: bug, extension, status: stalled
