### ISSUE TITLE
[Apple Reminders] Error fetching data

### ISSUE THREAD

**Issue by anxobruguera** [raycast/extensions#9555] opened 2023-12-05 23:44 UTC
### Extension

https://raycast.com/raycast/apple-reminders

#### Error:
```
SwiftError
    at ChildProcess.<anonymous> (/Users/bruguerangel/.config/raycast/extensions/112ad714-bf10-4ccc-a70f-4232bb2241a5/my-reminders.js:50:13331)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

### Steps To Reproduce

1. Access to Raycast
2. Go to "Create reminder"
3. An try to create a reminder
4. A message saying "Error fetching data" appears

**Comment by tleo19** [comment] 2023-12-08 22:15
Make sure Raycast has access to your reminders in System Settings → Privacy & Security.

**Comment by anxobruguera** [comment] 2023-12-09 12:19
I turned the Privacy on but the extension remains unworking.

**Comment by anxobruguera** [comment] 2023-12-12 22:10
[errorLog.pdf](https://github.com/raycast/extensions/files/13653677/errorLog.pdf)
 That are my error logs produced at Raycast, any suggestions?

**Comment by tleo19** [comment] 2023-12-12 22:43
@anxobruguera have you tried to remove and reinstall the extension?

**Comment by thomaslombart** [comment] 2023-12-18 11:03
Thanks for bringing this up. It appears that this is a duplicate of issue #9172, so I'll mark it as such.

**Closed by thomaslombart** 2023-12-18 11:03 UTC
Labels: bug, extension, extension: apple-reminders
