### ISSUE TITLE
[Browser Bookmarks] Crashes in Arc Browser

### ISSUE THREAD

**Issue by its-julian** [raycast/extensions#13012] opened 2024-06-18 06:10 UTC
### Extension

https://www.raycast.com/raycast/browser-bookmarks

### Raycast Version

1.76.1

### macOS Version

Ventura 13.5.2

#### Error:
```
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:406:5
[kOnExit]:worker:313:26
Worker.<computed>.onexit:worker:229:20
```

### Steps To Reproduce

1. Open up bookmarks app, load a few pages of bookmarks (Arc browser)
2. Close app
3. Re-open the app again (crashes)

### Current Behaviour

Current app crashes when opened. I receive error "something went wrong".

Clearing cache & local storage fixes the issue for 1 use. Then once it's reopened again, it crashes again.

I have over 1,000+ bookmarks across separate folders. Seems like the app is crashing due to the bookmark volume?

### Expected Behaviour

App works as expected (doesn't crash), and can handle lots of bookmarks - inside of Arc browser.

**Comment by thomaslombart** [comment] 2024-06-18 07:36
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6810, so I'll mark it as such.

**Closed by thomaslombart** 2024-06-18 07:36 UTC
Labels: bug, extension, extension: browser-bookmarks
