### ISSUE TITLE
[Music]: 

### ISSUE THREAD

**Issue by hugomingoia** [raycast/extensions#7973] opened 2023-08-17 08:04 UTC
### Extension

https://raycast.com/fedevitaledev/music

### Description

Command failed with exit code 1: osascript -e tell application "Music" to set loved of current track to true 
28:62: execution error: Music got an error: A descriptor type mismatch occurred. (-10001)

### Steps To Reproduce

Use "love track" command

**Comment by rawnly** [comment] 2023-08-17 08:06
Are you on Sonoma? if so this is a duplicate of #7852.

**Comment by rawnly** [comment] 2023-10-06 09:16
#8648

**Comment by rawnly** [comment] 2023-10-18 22:34
@raycastbot close this issue

**Closed** 2023-12-21 07:31 UTC
Labels: bug, extension, status: stalled, extension: music
