### ISSUE TITLE
[Color Picker] ...

### ISSUE THREAD

**Issue by pmothais** [raycast/extensions#8534] opened 2023-09-23 14:50 UTC
### Extension

https://www.raycast.com/thomas/color-picker

### Description

When using the extension, it doesn't seem like the color I pick is the right one.

For example I go on the tailwind website https://tailwindcss.com/docs/customizing-colors to check a color.

Let's say I pick a color with the extension, it will be different than what it should be.

If I pick the color Slate 500, I'm expecting #64748b but get #677489 instead. It's a color very similar but not exactly the color I picked.

### Steps To Reproduce

1. Opening the color picker
2. Picking a color
3. Pasting the color somewhere to check its hexa code.

### Current Behaviour

The color picked is not the one it should be.

**Comment by specified1** [comment] 2023-09-25 14:18
It's the same for me. The picked colour is somewhat similar, but it's far from a good match — let alone an exact one.

**Comment by erics118** [comment] 2023-09-28 14:25
This is how the screen works, as the rendered color is different from the actual hex code. If you were to go to Settings->Display and change the color profile used, then you would see that the hex code is different for each color profile.

**Comment by BramMusters** [comment] 2023-09-29 08:32
I noticed it as well. It only appears to happen on my Macbook screen, external screens don't have this problem.

**Comment by pmothais** [comment] 2023-09-29 13:28
Same as @specified1: some other apps bypass this screen color profile. I don't know how they manage to do if you say @erics118 that the issue comes from that.

It is really frustrating to copy a color which is in reality different than the one I think I picked. @specified1 mentioned some other tools, I am personally using Color Picker. When I pick a color using this app, the color picked is the one I expect.

I really love Raycast and it replaced a lot of tools I have been using, but for me, having the color picker like this is a deal breaker 😥.

I hope a solution can be found for me to enjoy Raycast even more 👨🏻‍🎨🎨

**Comment by specified1** [comment] 2023-09-29 13:44
I edited my previous reply to add [the Pika app](https://github.com/superhighfives/pika) which is open source and might shed some light here. I'm unfortunately not a Swift developer.

**Comment by pmothais** [comment] 2023-10-27 07:43
Thanks @specified1 👍🏻

Following up this ticket after a while, can you tell @erics118 that there is nothing to do on your end? It's unfortunate that we are a few having noticed this issue and are "constrained" to use third-party apps which seem to not have the issue whatsoever.

I wish a solution could be found here 🤞🏻

**Comment by specified1** [comment] 2023-10-27 08:09
@pmothais I did provide a link to a repository for an open source colour picker written in Swift that doesn't have this issue, but as I don't know the language I can't contribute with a fix myself, as much as I'd like to. 

Ultimately, having a colour picker that doesn't sample the correct colour defeats the purpose of having the tool in the first place, so for now I have reverted to the ColorSlurp app until the issue is hopefully resolved.

**Comment by otakustay** [comment] 2023-10-27 08:56
I may be able to fix this, but not yet tested for different screens, and I don't know how to publish a testing version so that participants of this thread can help to test through their screens

**Comment by specified1** [comment] 2023-10-27 09:13
@otakustay Could you perhaps attach the built extension folder and we can place it in `~/.config/raycast/extensions`?

**Comment by rightsaidfred99** [comment] 2023-10-28 00:44
I get this too, it's always showing the wrong color. Even picking the macOS menubar shows the wrong grey.

**Comment by otakustay** [comment] 2023-10-30 02:27
[color-picker.zip](https://github.com/raycast/extensions/files/13200103/color-picker.zip)

Hi @specified1 @pmothais , I upload a `color-picker.zip` which contains a single `color-picker` binary, please help me to test if this solves this issue:

1. Open `~/.config/raycast/extensions/40ebc708-964f-473b-8d19-d4e9cbd27ae9/assets/color-picker`, this is the path on my mac, if it is different for users, please use `find -iname "color-picker" ~/.config/raycast/extensions` to locate it
2. Backup `color-picker` binary inside this folder
3. Copy my `color-picker` into it and overwrite
4. Try to pick a color again

To detail, this extension uses macOS's system eyedrop to pick a color, which render a color in the default screen color space, on my Studio Display it's `Display P3`, for example, the "Red 500" color on [tailwind palette](https://tailwindcss.com/docs/customizing-colors) is `#ef4444` in sRGB, but `#dd524c` in Display P3 and `#cf4646` in Adobe RGB, to get a color exactly the same as web page, I believe sRGB is the right color space

We need to test it on different devices and scenario, including:

1. On a MacBooks's internal display, I've tested it on my M2 Air
2. On an Apple Display like Studio Display, XDR and UltraFine, I've tested all of them
3. On an iMac's internal display
4. On a third-pary external monitor connected to MacBook
5. Put RayCast in external monitor and test a color on internal screen
6. Put RayCast in internal screen and test on a external monitor

If the results are consistant and correct, I'll create a pull request to fix this issue, if not, I may have to add a preference item supporting choose color space maually

**Comment by specified1** [comment] 2023-10-31 09:39
For others trying @oktaysenkan's fix, you need to be on OS X 14.0+ Sonoma, otherwise you will get an error launching the picker. 

Also, the OS might block it at first due to the untrusted source, and to get around that you need to go to go to `~/.config/raycast/extensions/40ebc708-964f-473b-8d19-d4e9cbd27ae9/assets/` and open the color-picker binary with Terminal while holding down the option key. You will only have to do this the first time.

@otakustay Your version is much better and it generally gives colours that are indistinguishable from the original. For me, on my MacBook Pro, the Tailwind CSS 'Red 500' colour gives me #F04444 with both 'Color LCD' and 'Display P3' colour profiles. The code is different from the ones you shared but the colours look essentially identical (the picked one is slightly less red if you go by the RGB value, by 1 unit to be precise).

This makes the fixed version suitable for most practical purposes but you will have trouble picking a colour to run a find and replace operation.

**Comment by pmothais** [comment] 2023-11-03 11:06
Hello @otakustay.

I tested your `color-picker` binary. It seems to work much better than the current extension. The color I pick using this new version is exactly the hexa code shown on the tailwindcss website or very very close.

I tried a few colours, including the `slate-500` and `red-500` mentioned in this this issue. They match perfectly.

I'm on `Sonoma 14.1` and Macbook Pro `M1 Pro` version. I didn't test with an external monitor only the built-in one. I changed the colour profile, tested with `P3-1600 nits` and `sRGB`, it works for both. Not for all the colours and different profile though.

I notice a very slight difference on `P3-1600 nits`:
- `green-50` #f0fdf4 → #effdf4
On the `sRGB`profile the match is exact 👍🏻
As comparison, I have #f2fdf5 with the current version of the extension.

I don't know if the extension can know what colour profile the user is on

**Comment by specified1** [comment] 2023-11-03 11:15
> I notice a very slight difference on `P3-1600 nits`:
> 
> * `green-50` #f0fdf4 → #effdf4
>   On the `sRGB`profile the match is exact 👍🏻
>   As comparison, I have #f2fdf5 with the current version of the extension.

I had it happen a few times, always with the red value with an sRGB profile.

The picked value is 1 unit off on the RGB scale sometimes (in your example, #f0fdf4 and #effdf4 are different by 1 unit on red in RGB, where the former is 240 and the latter is 239).

**Comment by otakustay** [comment] 2023-11-04 03:20
The slight difference may come from how float numbers are converted to hex, I'll dig it a little deep to see if can be fixed in binary side

**Comment by otakustay** [comment] 2023-12-25 11:07
Hi @pmothais @specified1 if current fix is acceptable, I'd go to a PR for this

**Comment by pmothais** [comment] 2023-12-27 09:11
Hi @otakustay, I'm happy for a PR for your changes to be checked and approved 👍🏻

**Comment by mikestopcontinues** [comment] 2024-01-27 10:55
Really looking forward to this fix. What remains to do?

**Comment by otakustay** [comment] 2024-01-30 03:29
Sorry I have heavy works recently, luckily Chinese Spring Festival is coming, I'll do this fix around Feb. 10th

**Comment by mikestopcontinues** [comment] 2024-01-30 08:11
@otakustay Very kind! Thank you!

**Comment by otakustay** [comment] 2024-02-10 05:00
The swift part has been changed since my last try, now building this extension can cause some error:

```
npm run build

> build
> ray build -e dist

info  -  entry points [src/pick-color.ts src/menu-bar.tsx src/organize-colors.tsx]
error -  compiling swift package
build failed (src/pick-color.ts:5:26 import { pickColor } from "swift:../swift/color-picker";): failed to compile swift:
exit status 1

If this is unexpected, try to delete the color-picker/swift/color-picker/.raycast-swift-build folder and run this command again
```

I need help to solve this and continue, or anyone that able to build can try this simple code modification:

1. Open `swift/color-picker/Sources/main.swift`
2. Find the line `guard let color = await colorSampler.sample() else { return nil }`
3. Add `?.usingColorSpace(NSColorSpace.sRGB)` after `.sample()`

```diff
-   guard let color = await colorSampler.sample() else { return nil }
+   guard let color = await colorSampler.sample()?.usingColorSpace(NSColorSpace.sRGB) else { return nil }
```

**Closed** 2024-03-01 07:44 UTC
Labels: bug, extension, extension: color-picker
