### ISSUE TITLE
[Apple Notes] Returns "database disk image is malformed" when I try to search notes

### ISSUE THREAD

**Issue by DRosman2** [raycast/extensions#6631] opened 2023-05-18 03:03 UTC
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

<img width="862" alt="Screenshot 2023-05-17 at 11 01 00 PM" src="https://github.com/raycast/extensions/assets/105514454/0e280125-66e0-41de-9b10-2d25e543fc68">

### Steps To Reproduce

1. On MacOS Ventura 13.2.1
2.  Raycast version 1.51.1
3. From menu bar, type Search Notes then click enter
4. Should search notes, says database is malformed instead

**Comment by StevenRCE0** [comment] 2023-05-22 07:13
Duplicate of #5619. 

It's a known problem but we weren't able to reproduce stably so that we can work it out😢

**Closed** 2023-07-21 08:06 UTC
Labels: bug, extension, status: stalled, extension: apple-notes
