### ISSUE TITLE
[Notion] ...

### ISSUE THREAD

**Issue by Michael-AFH** [raycast/extensions#8479] opened 2023-09-20 14:33 UTC
### Extension

https://www.raycast.com/notion/notion

### Description

Request for the ability to customize the form used when creating new tasks. I would like to be able to remove fields that aren't relevant and pre-populate certain fields beforehand. For example, my main use case is to use Raycast to have a Global Hotkey to add a new Task to my Task Database. In this instance, I want the status of this task to always be set to "Inbox" for easy management. 

### Who will benefit from this feature?

Anyone that uses the feature

### Anything else?

The chrome extension "Save to Notion" has this feature and it works perfectly! I would continue to use this, but it's limited to only being triggered in Chrome. Raycast could solve this!

![Screenshot 2023-09-20 at 07 32 12](https://github.com/raycast/extensions/assets/105476431/30c773a6-9545-4533-b56a-6291cc791b20)

**Comment by erics118** [comment] 2023-09-21 23:38
dupe of #5016

**Comment by christianmagill** [comment] 2023-09-21 23:55
@erics118 This seems related to this as well: https://github.com/raycast/extensions/issues/8041

**Comment by erics118** [comment] 2023-09-22 01:14
Yes. #8041 is curently being worked on in #8199. I can take a look as to also make it work with deep links.

The result could be that you can have a "default" view of creating a new page, with certain properties visible, and in a certain order, but also create a quicklink with different visible properties in a different order.

**Comment by christianmagill** [comment] 2023-09-22 01:50
@erics118 That would be awesome! Perhaps splitting/unsplitting date fields could be done similarly. In my usage at least, it's normally a type of input that is tied to a date range.

**Comment by erics118** [comment] 2023-09-22 02:06
Yup, I would add an option to show/hide the end date field.

**Comment by erics118** [comment] 2023-11-12 04:55
no dont close

**Closed** 2024-01-11 05:03 UTC
Labels: feature request, extension, status: stalled
