### ISSUE TITLE
[Arc] Search Tabs Json Parse Error

### ISSUE THREAD

**Issue by Lior-Gal** [raycast/extensions#13979] opened 2024-08-12 08:46 UTC
### Extension

https://raycast.com/the-browser-company/arc

### Raycast Version

1.80.0

### macOS Version

14.5

#### Error:
```
SyntaxError: Bad control character in string literal in JSON at position 13483
    at JSON.parse (<anonymous>)
    at z9 (/Users/{user-email}/.config/raycast/extensions/606e26d8-b3c5-4760-8001-dccce1b872c4/search-tabs.js:94:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps To Reproduce

Arc -> Search Tabs -> [Error]

**Comment by Lior-Gal** [comment] 2024-08-12 13:08
Not any that are open. It never worked for me so probably there is nothing special about my current opened tabs that triggers the error. Could the pined or bookmarked urls be related?

**Comment by xilopaint** [comment] 2024-08-12 13:35
> Could the pined or bookmarked urls be related?

Yes, check if there are any with special characters.

**Comment by Lior-Gal** [comment] 2024-08-18 14:55
I have cleaned pins with 'weird' characters such as '|' & '[]' and that worked! 
TNX!!

**Comment by xilopaint** [comment] 2024-08-18 15:17
@raycastbot assign me

**Comment by xilopaint** [comment] 2024-08-18 16:33
@Lior-Gal, I can't reproduce the issue with the characters you mentioned. Could you tell the exact titles of the tabs that caused the problem so I can fix it?

<img width="886" alt="Screenshot 2024-08-18 at 13 30 27" src="https://github.com/user-attachments/assets/882ec865-2660-4357-83d1-72f75f316429">

<img width="886" alt="Screenshot 2024-08-18 at 13 30 55" src="https://github.com/user-attachments/assets/bcb2658a-2fc5-451d-942d-c1e20699d357">

**Comment by Lior-Gal** [comment] 2024-08-19 07:08
Sadly they were all deleted. Maybe there were as well: ':', ,'\'.  I am Hebrew speaker, so maybe there were as well characters in Hebrew (I don't remember any, but maybe).

**Comment by xilopaint** [comment] 2024-08-20 06:08
> Sadly they were all deleted. Maybe there were as well: ':', ,''. I am Hebrew speaker, so maybe there were as well characters in Hebrew (I don't remember any, but maybe).

I tried these characters, including some Hebrew ones, and couldn't reproduce the issue. If you happen to face the issue again, please open a new issue mentioning the title of the problematic tab. I'm closing this one.

@raycastbot close this issue

<img width="886" alt="Screenshot 2024-08-20 at 03 04 55" src="https://github.com/user-attachments/assets/838a47e6-aef4-475d-bc51-879ba405e1fe">

**Closed** 2024-08-20 06:08 UTC
Labels: bug, extension, extension: arc

**Comment by Pravin-Subramanian21** [comment] 2024-08-21 12:54
I am seeing the same error under Search Tabs and Search Arc feature.

Raycast Version: 1.81 

Arc Version 1.56.0

I tried closing a couple of tabs which I thought might have been an issue, but no help. If there's any particular character that I might have to look out for please let me know.

**Comment by xilopaint** [comment] 2024-08-21 13:37
The only way is for you to try running the command in Raycast for each tab you close. When you identify the tab that is causing the problem, you need to send us the title so we can analyze it.

**Comment by Pravin-Subramanian21** [comment] 2024-08-21 15:52
I was trying that out, and seems that the issue was intermittent. I deleted one of my bookmarks and then tried it which then seemed to have worked. The weird part was that none of the tabs had any special characters. I tried adding some of them but the issue did not occur after that. I am sorted for now. Thanks for your reply.
