### ISSUE TITLE
[Mastodon] Error on login

### ISSUE THREAD

**Issue by bdmorin** [raycast/extensions#13415] opened 2024-07-10 17:28 UTC
### Extension

https://www.raycast.com/SevicheCC/mastodon

### Raycast Version

1.78.1

### macOS Version

14.5

### Description

I'm unable to login to hachyderm.io using the extension. I have no idea if it's hachyderm.io or the extension. The website throws an error.
![CleanShot 2024-07-10 at 12 25 42](https://github.com/raycast/extensions/assets/476219/036a4c38-4899-471d-ac8b-ac58216dd32c)

[logs in]

![CleanShot 2024-07-10 at 12 26 00](https://github.com/raycast/extensions/assets/476219/18170d02-ae11-41b4-a5d2-3747cf7ba56b)

I would copy the url error here, but I don't know if there's sensitive information in the url string.
I've tried it in Firefox and Arc(chrome) both throw errors.

### Steps To Reproduce

1. Install from raycast store
2. launch extension
3. sign in to hachyderm.io
4. see error.

### Current Behaviour

Hachyderm throws error.

### Expected Behaviour

Hachyderm sends appropriate credentials to raycast extension.

**Comment by dvogt23** [comment] 2024-08-14 08:38
Same here :((

<img width="998" alt="Screenshot 2024-08-14 at 10 34 33" src="https://github.com/user-attachments/assets/93da8e1f-41a2-438a-aa34-687d369723d6">

Add my MODIFIED link here:
```
https://mas.to/oauth/authorize?client_id=lH5gNdX0SMoSJV2rQs&redirect_uri=https%3A%2F%2Fraycast.com%2Fredirect%3FpackageName%3DExtension&response_type=code&scope=read%3Astatuses+read%3Abookmarks+read%3Aaccounts+read%3Afavourites+read%3Anotifications+write%3Afavourites+write%3Amedia+write%3Abookmarks+write%3Astatuses+write%3Anotifications&code_challenge=5UXqHZgoLfu3ykjhbQ5NGBp8bh71P8Xp3M&code_challenge_method=S256&state=eyJpZCI6ZpZGVyTmFtZSI6Ik1ljkhxhdm9yIjoicmVsZWFzZSJ9
``` 
but with modified getting this -.-
<img width="468" alt="Screenshot 2024-08-14 at 10 37 30" src="https://github.com/user-attachments/assets/f51b905e-ea55-44d2-a5da-1b49ebdff325">



Would be great, to have a way to login with generated token or username/password as backup :///

any ideas?

**Comment by LitoMore** [comment] 2024-08-14 09:06
@dvogt23 Be careful. Don't post your private credentials to the public.

**Comment by LitoMore** [comment] 2024-08-14 09:07
I cannot reproduce the problem with https://mastodon.social. Do you guys have the `mastodon.social` account? Please let me know if you can reproduce the problem with the `mastodon.social` instance.

**Comment by dvogt23** [comment] 2024-08-14 09:12
Thanks @LitoMore with mastodon.social it works :// what could be wrong with the mas.to link?

**Comment by LitoMore** [comment] 2024-08-14 09:24
It might be related to:

- https://github.com/mastodon/mastodon/issues/12915

It looks more like a bug from the instance.

**Comment by LitoMore** [comment] 2024-08-14 09:25
@raycastbot rename this issue to "[Mastodon] Error on login"

**Comment by dvogt23** [comment] 2024-08-14 10:17
Great tips @LitoMore did contact admin from mas.to and he adjust config like [here](https://github.com/doorkeeper-gem/doorkeeper/issues/1554#issuecomment-1304606633) and it works 🥳

**Comment by LitoMore** [comment] 2024-08-14 10:30
Great. @raycastbot close this issue.

**Closed** 2024-08-14 10:30 UTC
Labels: bug, extension, extension: mastodon
