### ISSUE TITLE
[Bear Notes] Crashes on start

### ISSUE THREAD

**Issue by jrk** [raycast/extensions#3702] opened 2022-11-29 04:27 UTC
### Extension

https://github.com/raycast/extensions/tree/26c23d1e077847c79fda56ac9ad0624f644def05/extensions/bear/

## Error:
```
TypeError: Cannot read properties of null (reading 'matchAll')

ZT:index.js:116:8406

---
113: `,this.lastOut=`
114: `;for(var e=this.indentLevel;e>0;e--)this.buffer+=this.indent}}function Ure(e,t,r){var n="<"+e;if(t&&t.length>0)for(var u=0,a;(a=t[u])!==void 0;)n+=" "+a[0]+'="'+this.esc(a[1])+'"',u++;return r&&(n+=" /"),n+=">",n}hr.prototype=Object.create(On.prototype);hr.prototype.render=Yre;hr.prototype.out=Wre;hr.prototype.cr=Hre;hr.prototype.tag=Ure;hr.prototype.esc=vr;var Q_=He(wn());var Je=require("@raycast/api"),Y_=He(s_()),qn=require("react");var Mt=require("react/jsx-runtime");function W_({note:e}){let[t,r]=Gc(),[n,u]=(0,qn.useState)(),[a,i]=(0,qn.useState)();return(0,qn.useEffect)(()=>{t!=null&&(u(t.getBacklinks(e.id)),i(t.getNoteLinks(e.id)))},[t]),r&&(0,Je.showToast)(Je.Toast.Style.Failure,"Something went wrong",r.message),(0,Mt.jsxs)(Je.List,{isLoading:n==null,navigationTitle:e.title,children:[(0,Mt.jsx)(Je.List.Section,{title:"Note Backlinks",children:n?.map(s=>(0,Mt.jsx)(Je.List.Item,{title:s.title===""?"Untitled Note":s.encrypted?"\u{1F512} "+s.title:s.title,subtitle:s.formattedTags,icon:{source:"command-icon.png"},keywords:[s.id],actions:(0,Mt.jsx)(Tt,{isNotePreview:!1,note:s}),accessoryTitle:`edited ${(0,Y_.formatDistanceToNowStrict)(s.modifiedAt,{addSuffix:!0})}`},s.id))}),(0,Mt.jsx)(Je.List.Section,{title:"Note Links",children:a?.map(s=>(0,Mt.jsx)(Je.List.Item,{title:s.title===""?"Untitled Note":s.encrypted?"\u{1F512} "+s.title:s.title,subtitle:s.formattedTags,icon:{source:"command-icon.png"},keywords:[s.id],actions:(0,Mt.jsx)(Tt,{isNotePreview:!1,note:s}),accessoryTitle:`edited ${(0,Y_.formatDistanceToNowStrict)(s.modifiedAt,{addSuffix:!0})}`},s.id))})]})}var $T=require("@raycast/api"),zT=require("os");var UT=require("react/jsx-runtime"),HT=(0,zT.homedir)()+"/Library/Group Containers/9K33E3U3T4.net.shinyfrog.bear/Application Data/Local Files";function ud(e,t=!0){if(e===null)return"";let r=e,n=r.matchAll(/\[(?<type>file|image):(?<path>.+)\]/g);for(let u of n){if(u.groups===void 0)return r;let a="";if(u.groups.type==="image"&&!t)a=`![](${`${HT}/Note Images/${u.groups.path}`})`;else{let i=encodeURI(`file://${HT}/${u.groups.type==="file"?"Note Files":"Note Images"}/${u.groups.path}`);a=`[Show attached ${u.groups.type}](${i})`}r=r.replace(u[0],a)}return r}function H_({note:e}){let t=e.encrypted?`# ${e.title}
115: 
116: *This note's content is encrypted*`:e.text;return(0,UT.jsx)($T.Detail,{markdown:ud(t),navigationTitle:e.title,actions:(0,UT.jsx)(Tt,{isNotePreview:!0,note:e})})}var xe=require("@raycast/api"),QT=He(wn()),At=require("react/jsx-runtime");function jre(){async function e({url:t,tags:r,pin:n}){if(!t){(0,xe.showToast)(xe.Toast.Style.Failure,"URL is required");return}(0,QT.default)(`bear://x-callback-url/grab-url?url=${encodeURIComponent(t)}&tags=${encodeURIComponent(r)}&pin=${n?"yes":"no"}`),await(0,xe.popToRoot)({clearSearchBar:!0})}return(0,At.jsx)(xe.Action.SubmitForm,{icon:xe.Icon.Globe,title:"Capture in New Note",onSubmit:e})}function U_(){return(0,At.jsxs)(xe.Form,{navigationTitle:"Grab URL",actions:(0,At.jsx)(xe.ActionPanel,{children:(0,At.jsx)(jre,{})}),children:[(0,At.jsx)(xe.Form.TextField,{id:"url",title:"URL",placeholder:"URL of web page to capture (eg. http://raycast.com)"}),(0,At.jsx)(xe.Form.TextField,{id:"tags",title:"Tags",placeholder:"comma,separated,tags"}),(0,At.jsx)(xe.Form.Checkbox,{id:"pin",label:"Pin note to top of note list"})]})}var Q=require("@raycast/api"),GT=He(wn()),ad=require("react"),le=require("react/jsx-runtime");function ene(e){let t=/(^|\n)(?<level>#{1,6})[^\S\t\n\r](?<text>.*)\n/g,r=e.matchAll(t),n=[];for(let u of r){let a={level:u.groups?.level.length??1,text:u.groups?.text??"Some Header"};n.push(a)}return n}function $_({note:e}){let[t,r]=(0,ad.useState)([]);(0,ad.useEffect)(()=>{r(ene(e.text))},[]);let n=()=>{let u=async a=>{if(!a.text){(0,Q.showToast)(Q.Toast.Style.Failure,"Please enter text");return}(0,GT.default)(`bear://x-callback-url/add-text?id=${e.id}${a.header==="none"?"":"&header="+encodeURIComponent(a.header)}&mode=${a.mode}&new_line=${a.newLine?"yes":"no"}&tags=${encodeURIComponent(a.tags)}&open_note=${a.openNote!=="no"?"yes":"no"}&new_window=${a.openNote==="new"?"yes":"no"}&show_window=${a.openNote!=="no"?"yes":"no"}&edit=${a.openNote==="no"?"no":"yes"}&timestamp=${a.timestamp?"yes":"no"}&text=${encodeURIComponent(a.text)}`,{background:a.openNote==="no"}),await(0,Q.closeMainWindow)(),await(0,Q.popToRoot)({clearSearchBar:!0})};return(0,le.jsx)(Q.Action.SubmitForm,{icon:Q.Icon.Plus,title:"Append Text",onSubmit:u})};return(0,le.jsxs)(Q.Form,{navigationTitle:`Add Text To: ${e.title}`,actions:(0,le.jsx)(Q.ActionPanel,{children:(0,le.jsx)(n,{})}),children:[(0,le.jsxs)(Q.Form.Dropdown,{id:"mode",title:"Mode",children:[(0,le.jsx)(Q.Form.Dropdown.Item,{value:"prepend",title:"Prepend"}),(0,le.jsx)(Q.Form.Dropdown.Item,{value:"append",title:"Append"}),(0,le.jsx)(Q.Form.Dropdown.Item,{value:"replace",title:"Replace"}),(0,le.jsx)(Q.Form.Dropdown.Item,{value:"replace_all",title:"Replace All"})]}),(0,le.jsx)(Q.Form.TextArea,{id:"text",title:"Text",placeholder:"Text to add to note ..."}),(0,le.jsx)(Q.Form.Separator,{}),(0,le.jsx)(Q.Form.TextField,{id:"tags",title:"Tags",placeholder:"comma,separated,tags"}),(0,le.jsxs)(Q.Form.Dropdown,{id:"header",title:"Append To Header",children:[(0,le.jsx)(Q.Form.Dropdown.Item,{value:"none",title:"-"}),t.map(({level:u,text:a})=>(0,le.jsx)(Q.Form.Dropdown.Item,{value:a,title:`h${u}: ${a}`},a))]}),(0,le.jsxs)(Q.Form.Dropdown,{id:"openNote",title:"Open Note",children:[(0,le.jsx)(Q.Form.Dropdown.Item,{value:"no",title:"Don't Open Note"}),(0,le.jsx)(Q.Form.Dropdown.Item,{value:"main",title:"In Main Window"}),(0,le.jsx)(Q.Form.Dropdown.Item,{value:"new",title:"In New Window"})]}),(0,le.jsx)(Q.Form.Checkbox,{id:"newLine",label:"Force new line"}),(0,le.jsx)(Q.Form.Checkbox,{id:"timestamp",label:"Prepend time and date"}),(0,le.jsx)(Q.Form.Checkbox,{id:"pin",label:"Pin note in notes list"})]})}var te=require("@raycast/api"),VT=He(wn()),Te=require("react/jsx-runtime");function tne(){async function e(t){if(!t.text){(0,te.showToast)(te.Toast.Style.Failure,"Please enter text");return}(0,VT.default)(`bear://x-callback-url/create?title=${encodeURIComponent(t.title)}&tags=${encodeURIComponent(t.tags)}&open_note=${t.openNote!=="no"?"yes":"no"}&new_window=${t.openNote==="new"?"yes":"no"}&show_window=${t.openNote!=="no"?"yes":"no"}&edit=${t.openNote==="no"?"no":"yes"}&timestamp=${t.timestamp?"yes":"no"}&text=${encodeURIComponent(t.text)}`,{background:t.openNote==="no"}),await(0,te.closeMainWindow)(),await(0,te.popToRoot)({clearSearchBar:!0})}return(0,Te.jsx)(te.Action.SubmitForm,{icon:te.Icon.Document,title:"Create Note",onSubmit:e})}function z_(){return(0,Te.jsxs)(te.Form,{navigationTitle:"Create Note",actions:(0,Te.jsx)(te.ActionPanel,{children:(0,Te.jsx)(tne,{})}),children:[(0,Te.jsx)(te.Form.TextField,{id:"title",title:"Title",placeholder:"Note Title ..."}),(0,Te.jsx)(te.Form.TextArea,{id:"text",title:"Text",placeholder:"Text to add to note ..."}),(0,Te.jsx)(te.Form.TextField,{id:"tags",title:"Tags",placeholder:"comma,separated,tags"}),(0,Te.jsx)(te.Form.Separator,{}),(0,Te.jsxs)(te.Form.Dropdown,{id:"openNote",title:"Open Note",children:[(0,Te.jsx)(te.Form.Dropdown.Item,{value:"no",title:"Don't Open Note"}),(0,Te.jsx)(te.Form.Dropdown.Item,{value:"main",title:"In Main Window"}),(0,Te.jsx)(te.Form.Dropdown.Item,{value:"new",title:"In New Window"})]}),(0,Te.jsx)(te.Form.Checkbox,{id:"timestamp",label:"Prepend time and date"}),(0,Te.jsx)(te.Form.Checkbox,{id:"pin",label:"Pin note in notes list"})]})}var re=require("react/jsx-runtime");function rne(e){let t=new S_,r=new C_,n;try{let u=ud(e,!1);return n=r.render(t.parse(u)),n}catch(u){return console.log(`Error rendering with commonmark: ${String(u)}`),(0,N.showToast)(N.Toast.Style.Failure,"Error rendering markdown"),""}}function nne({note:e}){return(0,re.jsx)(N.Action.Push,{title:"Show Note Preview",target:(0,re.jsx)(H_,{note:e}),icon:N.Icon.Text,shortcut:{modifiers:["cmd"],key:"p"}})}function Tt({isNotePreview:e,note:t}){let{focusCursorAtEnd:r}=(0,N.getPreferenceValues)(),n=r?"yes":"no";return(0,re.jsxs)(N.ActionPanel,{children:[(0,re.jsxs)(N.ActionPanel.Section,{title:"Open",children:[(0,re.jsx)(N.Action.Open,{title:"Open in Bear",target:`bear://x-callback-url/open-note?id=${t.id}&edit=${n}`,icon:N.Icon.Sidebar}),t.encrypted?null:(0,re.jsx)(N.Action.Open,{title:"Open in New Bear Window",target:`bear://x-callback-url/open-note?id=${t.id}&new_window=yes&edit=${n}`,icon:N.Icon.Window})]}),t.encrypted?null:(0,re.jsxs)(N.ActionPanel.Section,{title:"Edit",children:[(0,re.jsx)(N.Action.Push,{title:"Add Text",icon:N.Icon.Plus,shortcut:{modifiers:["cmd"],key:"t"},target:(0,re.jsx)($_,{note:t})}),(0,re.jsx)(N.Action,{title:"Move to Archive",onAction:()=>{(0,Q_.default)(`bear://x-callback-url/archive?id=${t.id}&show_window=yes`,{background:!0}),(0,N.showToast)(N.Toast.Style.Success,"Moved note to archive")},icon:{source:N.Icon.List,tintColor:N.Color.Orange},shortcut:{modifiers:["ctrl","shift"],key:"x"}}),(0,re.jsx)(N.Action,{title:"Move to Trash",onAction:()=>{(0,Q_.default)(`bear://x-callback-url/trash?id=${t.id}&show_window=yes`,{background:!0}),(0,N.showToast)(N.Toast.Style.Success,"Moved note to trash")},icon:{source:N.Icon.Trash,tintColor:N.Color.Red},shortcut:{modifiers:["ctrl"],key:"x"}})]}),(0,re.jsxs)(N.ActionPanel.Section,{title:"Show in Raycast",children:[e?null:(0,re.jsx)(nne,{note:t}),(0,re.jsx)(N.Action.Push,{title:"Show Note Links",target:(0,re.jsx)(W_,{note:t}),icon:N.Icon.Link,shortcut:{modifiers:["cmd"],key:"l"}})]}),(0,re.jsxs)(N.ActionPanel.Section,{title:"Copy",children:[t.encrypted?null:(0,re.jsx)(N.Action.CopyToClipboard,{title:"Copy Markdown",content:ud(t.text,!1),icon:N.Icon.Clipboard,shortcut:{modifiers:["cmd"],key:"c"}}),t.encrypted?null:(0,re.jsx)(N.Action.CopyToClipboard,{title:"Copy HTML",content:rne(t.text),icon:N.Icon.Terminal,shortcut:{modifiers:["cmd","shift"],key:"c"}}),(0,re.jsx)(N.Action.CopyToClipboard,{title:"Copy Link to Note",content:`bear://x-callback-url/open-note?id=${t.id}`,icon:N.Icon.Link,shortcut:{modifiers:["cmd","opt"],key:"c"}}),t.encrypted?null:(0,re.jsx)(N.Action.CopyToClipboard,{title:"Copy Unique Identifier",content:"note.id",icon:N.Icon.QuestionMark,shortcut:{modifiers:["cmd","opt","shift"],key:"c"}})]}),(0,re.jsxs)(N.ActionPanel.Section,{title:"Create",children:[(0,re.jsx)(N.Action.Push,{title:"New Note",icon:N.Icon.Document,shortcut:{modifiers:["cmd"],key:"n"},target:(0,re.jsx)(z_,{})}),(0,re.jsx)(N.Action.Push,{title:"New Web Capture",icon:N.Icon.Globe,shortcut:{modifiers:["cmd","shift"],key:"n"},target:(0,re.jsx)(U_,{})})]})]})}var Re=require("react/jsx-runtime");function ZT(){let[e,t]=(0,Pn.useState)(""),[r,n]=Gc(),[u,a]=(0,Pn.useState)();(0,Pn.useEffect)(()=>{r!=null&&a(r.getNotes(e))},[r,e]),n&&(0,ye.showToast)(ye.Toast.Style.Failure,"Something went wrong",n.message);let i=(u??[]).length>0&&(0,ye.getPreferenceValues)().showPreviewInListView;return(0,Re.jsx)(ye.List,{isLoading:u==null,onSearchTextChange:t,searchBarPlaceholder:"Search note text or id ...",isShowingDetail:i,children:u?.map(s=>(0,Re.jsx)(ye.List.Item,{title:s.title===""?"Untitled Note":s.encrypted?"\u{1F512} "+s.title:s.title,subtitle:i?void 0:s.formattedTags,icon:{source:"command-icon.png"},keywords:[s.id],actions:(0,Re.jsx)(Tt,{isNotePreview:!1,note:s}),accessoryTitle:i?void 0:`edited ${(0,id.formatDistanceToNowStrict)(s.modifiedAt,{addSuffix:!0})}`,detail:(0,Re.jsx)(ye.List.Item.Detail,{markdown:s.encrypted?"*This note's content is encrypted*":s.text,metadata:(0,Re.jsx)(une,{note:s})})},s.id))})}function une({note:e}){return(0,Re.jsxs)(ye.List.Item.Detail.Metadata,{children:[(0,Re.jsx)(ye.List.Item.Detail.Metadata.TagList,{title:"Tags",children:e.tags.length===0?(0,Re.jsx)(ye.List.Item.Detail.Metadata.TagList.Item,{text:"Untagged"}):e.tags.map(t=>(0,Re.jsx)(ye.List.Item.Detail.Metadata.TagList.Item,{text:t,color:ye.Color.Yellow},t))}),(0,Re.jsx)(ye.List.Item.Detail.Metadata.Label,{title:"Last modified",text:(0,id.formatDistanceToNowStrict)(e.modifiedAt,{addSuffix:!0})}),(0,Re.jsx)(ye.List.Item.Detail.Metadata.Label,{title:"Created",text:(0,id.formatDistanceToNowStrict)(e.createdAt,{addSuffix:!0})}),(0,Re.jsx)(ye.List.Item.Detail.Metadata.Label,{title:"Word count",text:`${e.wordCount} words`})]})}0&&(module.exports={});
117: /*! http://mths.be/fromcodepoint v0.2.1 by @mathias */
118: /*! http://mths.be/repeat v0.2.0 by @mathias */
119: 
---

zt:index.js:5:2490
    at ray-navigation-stack
Rr:index.js:5:2088
```

### Steps To Reproduce

This started for me some time in just the past few days (after months of use). It instantly barfs when triggering the `Search Notes` action, before typing anything or otherwise interacting in any way.

**Comment by yagopv** [comment] 2022-11-29 12:49
happen to me as well

**Comment by hmarr** [comment] 2022-11-29 23:12
Thanks for reporting this, I think I found the cause—#3717 should fix it.

**Comment by hmarr** [comment] 2022-11-29 23:14
Ah @ron-myers I just saw your comment now. I'm pretty certain [this line](https://github.com/raycast/extensions/blob/769c05a218b87a654b3b2d079ac6465f9d8f559a/extensions/bear/src/bear-db.ts#L163) is the culprit as it was introduced recently in a PR I submitted and would be hit on every search.

**Comment by ron-myers** [comment] 2022-11-29 23:30
Good stuff @hmarr :) - I was adding the same protection - I will leave it to you to get it merged in.

**Closed** 2022-11-30 08:28 UTC
Labels: bug, extension, extension: bear

**Comment by lucaschultz** [comment] 2022-12-01 09:16
That was a quick fix, thank you @hmarr an @ron-myers 💪

**Comment by yagopv** [comment] 2022-12-01 09:18
fixed for me as well. thanks!

**Comment by jrk** [comment] 2022-12-04 06:10
Confirmed: fixed here, too. Thanks!
