### ISSUE TITLE
[Apple Notes] Bug when trying to search notes

### ISSUE THREAD

**Issue by RihardsVeters** [raycast/extensions#10468] opened 2024-01-31 08:18 UTC
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

Hi! I’m experiencing problem with Apple Notes extension. I’m not able to search my notes anymore. Is it known bug or something I’ve done wrong?
![image](https://github.com/raycast/extensions/assets/41144957/76b86f13-2aa6-4bc6-a189-002dab0dd9a8)

### Steps To Reproduce

open search notes extension, see error.

**Comment by RihardsVeters** [comment] 2024-03-21 08:31
Someone is going to fix this??

**Comment by pernielsentikaer** [comment] 2024-03-21 08:33
@tumispro haven't we seen this before?

**Comment by mathieudutour** [comment] 2024-03-21 08:35
yes: https://github.com/raycast/extensions/issues?q=is%3Aissue+is%3Aopen+database+disk

**Comment by thomaslombart** [comment] 2024-03-22 11:17
Thanks for bringing this up. It appears that this is a duplicate of issue https://github.com/raycast/extensions/issues/6916, so I'll mark it as such.

**Closed by thomaslombart** 2024-03-22 11:17 UTC
Labels: bug, extension, extension: apple-notes
